"""
GF(37) Mathematical Engine — Pure computation, no interpretation.

Deterministic functions over (ℤ/37ℤ)×. No labels, no metadata,
no framework annotations. Those belong in gf37_classes.py.

Import:
    from cylicamp.gf37_engine import GF37
    G = GF37()
    G.order(16)          # → 9
    G.dlog(24)           # → 29
    G.legendre(8)        # → -1  (NQR)
    G.coset_H9(3)        # → '4H9'
    G.orbit_26(24)       # → (24, 32, 18)
    G.is_primitive_root(2) # → True
"""

P = 37
G_DEFAULT = 2   # primitive root; ord₃₇(2) = 36

# ── Subgroups (computed once, as frozensets) ───────────────────────────────────

def _generate_subgroup(gen_exp: int, p: int = P, g: int = G_DEFAULT) -> frozenset:
    """Multiplicative subgroup generated by g^gen_exp (mod p)."""
    gen = pow(g, gen_exp, p)
    s, x = set(), 1
    while x not in s:
        s.add(x)
        x = x * gen % p
    return frozenset(s)

# Unique subgroups of (ℤ/37ℤ)× (one per divisor of 36)
H1  = frozenset({1})                                          # order 1
H2  = _generate_subgroup(18)                                  # order 2: {1,36}
H3  = _generate_subgroup(12)                                  # order 3: IC = {1,10,26}
H4  = _generate_subgroup(9)                                   # order 4: {1,6,31,36}
H6  = _generate_subgroup(6)                                   # order 6
H9  = _generate_subgroup(4)                                   # order 9: Sylow 3
H12 = _generate_subgroup(3)                                   # order 12
H18 = frozenset(a for a in range(1, P) if pow(a, 18, P) == 1)  # QR subgroup
H36 = frozenset(range(1, P))                                  # full group

SUBGROUPS = {1: H1, 2: H2, 3: H3, 4: H4, 6: H6,
             9: H9, 12: H12, 18: H18, 36: H36}

# Cosets of H9 = {1,7,9,10,12,16,26,33,34}
def _cosets(H: frozenset, p: int = P) -> dict:
    """Compute cosets of subgroup H in (ℤ/p ℤ)×."""
    remaining = set(range(1, p))
    cosets = {}
    for rep in sorted(remaining):
        if rep in remaining:
            c = frozenset(rep * h % p for h in H)
            cosets[rep] = c
            remaining -= c
    return cosets

_H9_COSETS_RAW = _cosets(H9)
# Label by minimal representative
_H9_COSET_LABEL = {}
for rep, c in _H9_COSETS_RAW.items():
    for elem in c:
        _H9_COSET_LABEL[elem] = rep

_H3_COSETS_RAW = _cosets(H3)
_H3_COSET_LABEL = {}
for rep, c in _H3_COSETS_RAW.items():
    for elem in c:
        _H3_COSET_LABEL[elem] = rep


# ── Precomputed DLP table (base 2, mod 37) ─────────────────────────────────────

_DLP = {}
_POWERS = {}
_x = 1
for _k in range(36):
    _DLP[_x] = _k
    _POWERS[_k] = _x
    _x = _x * 2 % P


# ── Core API ───────────────────────────────────────────────────────────────────

class GF37:
    """Computational interface to (ℤ/37ℤ)×."""

    p: int = P
    generator: int = G_DEFAULT
    order_of_group: int = 36

    # ── Element functions ────────────────────────────────────────────────────

    def order(self, a: int) -> int:
        """Multiplicative order of a in (ℤ/37ℤ)×."""
        a = a % P
        if a == 0:
            raise ValueError("0 has no multiplicative order")
        k = self.dlog(a)
        from math import gcd
        return 36 // gcd(k, 36)

    def dlog(self, a: int, base: int = G_DEFAULT) -> int:
        """Discrete logarithm: smallest k ≥ 0 with base^k ≡ a (mod 37)."""
        a = a % P
        if a == 0:
            raise ValueError("log of 0 undefined")
        if base == G_DEFAULT:
            return _DLP[a]
        # BSGS for arbitrary base
        from math import isqrt
        n = P - 1
        m = isqrt(n) + 1
        table = {}
        bj = 1
        for j in range(m):
            table[bj] = j
            bj = bj * base % P
        bm_inv = pow(pow(base, m, P), P - 2, P)
        cur = a
        for i in range(m + 1):
            if cur in table:
                k = (i * m + table[cur]) % n
                if k > 0 or pow(base, 0, P) == a:
                    return k
            cur = cur * bm_inv % P
        raise ValueError(f"dlog({a}, base={base}) not found")

    def pow(self, k: int) -> int:
        """Return 2^k mod 37."""
        return _POWERS[k % 36]

    def legendre(self, a: int) -> int:
        """Legendre symbol (a/37): +1 QR, -1 NQR, 0 if 37|a."""
        a = a % P
        if a == 0:
            return 0
        r = pow(a, 18, P)   # a^((p-1)/2)
        return 1 if r == 1 else -1

    def is_quadratic_residue(self, a: int) -> bool:
        return self.legendre(a) == 1

    def is_primitive_root(self, a: int) -> bool:
        """True if a generates (ℤ/37ℤ)×."""
        a = a % P
        if a == 0:
            return False
        # Check a^(36/q) ≢ 1 for each prime q | 36
        for q in (2, 3):
            if pow(a, 36 // q, P) == 1:
                return False
        return True

    def primitive_roots(self) -> list:
        """All 12 primitive roots mod 37."""
        return sorted(a for a in range(1, P) if self.is_primitive_root(a))

    def euler_test(self, a: int) -> int:
        """Return a^18 mod 37 (Euler criterion value: 1 or 36≡-1)."""
        return pow(a % P, 18, P)

    # ── Subgroup / coset functions ────────────────────────────────────────────

    def subgroup(self, order: int) -> frozenset:
        """Unique subgroup of given order (must divide 36)."""
        if order not in SUBGROUPS:
            raise ValueError(f"No subgroup of order {order} in (ℤ/37ℤ)×")
        return SUBGROUPS[order]

    def coset_H9(self, a: int) -> int:
        """Representative of H9-coset containing a. Returns minimal rep."""
        a = a % P
        return _H9_COSET_LABEL.get(a, a)

    def coset_H3(self, a: int) -> int:
        """Representative of H3-coset containing a (= 137-orbit coset)."""
        a = a % P
        return _H3_COSET_LABEL.get(a, a)

    def cosets(self, subgroup_order: int) -> dict:
        """All cosets of the subgroup of given order. Returns {rep: frozenset}."""
        H = self.subgroup(subgroup_order)
        return _cosets(H)

    def orbit_26(self, a: int) -> tuple:
        """137-map orbit: 3-cycle of a under ×26 mod 37."""
        a = a % P
        path = []
        for _ in range(3):
            path.append(a)
            a = 26 * a % P
        return tuple(path)

    # ── Group-level functions ─────────────────────────────────────────────────

    def subgroup_lattice(self) -> dict:
        """Divisor lattice {order: subgroup} for all divisors of 36."""
        return dict(SUBGROUPS)

    def quadratic_residues(self) -> frozenset:
        return H18

    def nonresidues(self) -> frozenset:
        return frozenset(range(1, P)) - H18

    def all_orders(self) -> dict:
        """Map a → ord(a) for all a in (ℤ/37ℤ)×."""
        return {a: self.order(a) for a in range(1, P)}

    def all_dlogs(self) -> dict:
        """Complete discrete-log table {a: log₂(a)} for a=1..36."""
        return dict(_DLP)

    def rabinowitsch_residues(self) -> dict:
        """Six Rabinowitsch primes → (residue mod 37, legendre, H9-coset)."""
        primes = [2, 3, 5, 11, 17, 41]
        return {
            q: {
                'residue': q % P,
                'legendre': self.legendre(q % P),
                'H9_coset_rep': self.coset_H9(q % P),
                'dlog': self.dlog(q % P),
            }
            for q in primes
        }

    def euler_partition(self) -> dict:
        """Partition (ℤ/37ℤ)× into QR (even dlog) and NQR (odd dlog)."""
        qr  = sorted(a for a in range(1, P) if _DLP[a] % 2 == 0)
        nqr = sorted(a for a in range(1, P) if _DLP[a] % 2 == 1)
        return {'QR': qr, 'NQR': nqr}


# ── Module-level convenience instance ────────────────────────────────────────

_G = GF37()
order              = _G.order
dlog               = _G.dlog
legendre           = _G.legendre
is_primitive_root  = _G.is_primitive_root
primitive_roots    = _G.primitive_roots
euler_test         = _G.euler_test
subgroup           = _G.subgroup
cosets             = _G.cosets
orbit_26           = _G.orbit_26
quadratic_residues = _G.quadratic_residues
nonresidues        = _G.nonresidues


# ── Self-test ─────────────────────────────────────────────────────────────────

def _selftest():
    G = GF37()

    # Orders
    assert G.order(2) == 36
    assert G.order(26) == 3
    assert G.order(6) == 4
    assert G.order(16) == 9

    # DLP
    assert G.dlog(1) == 0
    assert G.dlog(2) == 1
    assert G.dlog(24) == 29   # 2^29 mod 37 = 24 ∈ CB∩SEED_ORB

    # Legendre / Euler
    for a in [3, 4, 9, 11, 25]:     assert G.legendre(a) == 1
    for a in [2, 5, 8, 17, 18]:     assert G.legendre(a) == -1
    assert G.euler_test(3) == 1
    assert G.euler_test(2) == P - 1   # -1 mod 37 = 36

    # Rabinowitsch (Euler's criterion explicit values from theorem)
    rab = {2: -1, 3: 1, 4: 1, 5: -1, 11: 1, 17: -1}
    for a, expected in rab.items():
        assert G.legendre(a) == expected, f"legendre({a}) ≠ {expected}"

    # Primitive roots
    pr = G.primitive_roots()
    assert len(pr) == 12
    assert 2 in pr and 18 in pr and 32 in pr

    # Subgroups
    assert G.subgroup(3) == frozenset({1, 10, 26})
    assert G.subgroup(9) == frozenset({1,7,9,10,12,16,26,33,34})
    assert G.subgroup(4) == frozenset({1,6,31,36})

    # Orbits
    assert set(G.orbit_26(24)) == {18, 24, 32}
    assert set(G.orbit_26(4)) == {3, 4, 30}

    # H9 cosets: none of the six Rabinowitsch residues is in H9
    h9 = G.subgroup(9)
    rab_residues = [q % P for q in [2, 3, 5, 11, 17, 41]]
    assert not any(r in h9 for r in rab_residues), "Rabinowitsch residues should avoid H9"

    # Euler partition: QR ↔ even dlog
    ep = G.euler_partition()
    assert all(_DLP[a] % 2 == 0 for a in ep['QR'])
    assert all(_DLP[a] % 2 == 1 for a in ep['NQR'])
    assert len(ep['QR']) == 18 and len(ep['NQR']) == 18

    print("GF37Engine: all self-tests passed.")


if __name__ == "__main__":
    _selftest()

    G = GF37()
    print(f"\nPrimitive roots mod 37 ({len(G.primitive_roots())}): {G.primitive_roots()}")
    print(f"\nRabinowitsch residues:")
    for q, info in G.rabinowitsch_residues().items():
        leg = '+1 (QR)' if info['legendre'] == 1 else '-1 (NQR)'
        print(f"  q={q:>2}  r={info['residue']:>2}  {leg}  H9-coset-rep={info['H9_coset_rep']}  log₂={info['dlog']}")

    print(f"\nH9 cosets (4 cosets of order-9 subgroup):")
    for rep, c in sorted(G.cosets(9).items()):
        in_h9 = rep in G.subgroup(9)
        print(f"  {rep}·H9 = {sorted(c)}{'  ← identity coset' if in_h9 else ''}")
