#!/usr/bin/env python3
"""
pattern_mech.py

VIREON Pattern-Mech Audit Engine

Pipeline:
PATTERN -> MECHANISM -> PROOF -> COMPRESSION -> APPLICATION -> VERDICT

Audits numerical pattern claims using reproducible math:
- Decimal repetends
- Modular orbits / multiplicative order
- Random walks on Z/nZ using Fourier eigenvalues
- Divisibility/parity filters

Pure Python. No required third-party packages.
"""

from __future__ import annotations

import argparse
import cmath
import math
from dataclasses import dataclass, field
from fractions import Fraction
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


# =============================================================================
# Utility helpers
# =============================================================================

def line(char: str = "=", width: int = 80) -> str:
    return char * width


def fmt_float(x: float, digits: int = 10) -> str:
    return f"{x:.{digits}f}"


def gcd_many(values: Iterable[int]) -> int:
    vals = [abs(v) for v in values if v != 0]
    if not vals:
        return 0
    g = vals[0]
    for v in vals[1:]:
        g = math.gcd(g, v)
    return g


def digital_sum(n: int) -> int:
    return sum(int(ch) for ch in str(abs(n)))


def digital_root(n: int) -> int:
    n = abs(n)
    if n == 0:
        return 0
    return 1 + (n - 1) % 9


def multiplicative_order(a: int, n: int, max_iter: Optional[int] = None) -> Optional[int]:
    """Return smallest k > 0 such that a^k == 1 mod n, if gcd(a,n)=1."""
    if math.gcd(a, n) != 1:
        return None
    a %= n
    cur = 1
    max_iter = max_iter or n * n
    for k in range(1, max_iter + 1):
        cur = (cur * a) % n
        if cur == 1:
            return k
    return None


def additive_generated_size(n: int, steps: Iterable[int]) -> int:
    """Size of additive subgroup generated by steps in Z/nZ."""
    g = gcd_many([n] + list(steps))
    if g == 0:
        return 1
    return n // g


def normalize_distribution(dist: Dict[int, float], n: Optional[int] = None) -> Dict[int, float]:
    out: Dict[int, float] = {}
    for k, v in dist.items():
        kk = k % n if n else k
        out[kk] = out.get(kk, 0.0) + float(v)
    total = sum(out.values())
    if total <= 0:
        raise ValueError("Distribution has nonpositive total mass.")
    return {k: v / total for k, v in out.items() if abs(v) > 1e-15}


def convolve_mod(a: Sequence[float], step_dist: Dict[int, float], n: int) -> List[float]:
    """One convolution step on Z/nZ."""
    out = [0.0] * n
    for i, mass in enumerate(a):
        if mass == 0.0:
            continue
        for step, p in step_dist.items():
            out[(i + step) % n] += mass * p
    return out


def total_variation(dist: Sequence[float]) -> float:
    n = len(dist)
    uniform = 1.0 / n
    return 0.5 * sum(abs(x - uniform) for x in dist)


def triangular_digit_difference_distribution(base: int = 10) -> Dict[int, float]:
    """Distribution of A - B where A,B are uniform on {0,...,base-1}."""
    if base < 2:
        raise ValueError("base must be >= 2")
    denom = base * base
    return {t: (base - abs(t)) / denom for t in range(-(base - 1), base)}


def is_triangular_digit_difference(dist: Dict[int, float], base: int = 10, tol: float = 1e-12) -> bool:
    expected = triangular_digit_difference_distribution(base)
    keys = set(dist)
    if keys != set(expected):
        return False
    return all(abs(dist[k] - expected[k]) <= tol for k in expected)


def simple_is_prime(p: int) -> bool:
    if p < 2:
        return False
    if p == 2:
        return True
    if p % 2 == 0:
        return False
    r = int(math.isqrt(p))
    for d in range(3, r + 1, 2):
        if p % d == 0:
            return False
    return True


# =============================================================================
# Audit report object
# =============================================================================

@dataclass
class AuditReport:
    title: str
    pattern: List[str] = field(default_factory=list)
    mechanism: List[str] = field(default_factory=list)
    proof: List[str] = field(default_factory=list)
    compression: List[str] = field(default_factory=list)
    application: List[str] = field(default_factory=list)
    verdict: List[str] = field(default_factory=list)

    def add(self, section: str, text: str) -> None:
        getattr(self, section.lower()).append(text)

    def render_section(self, name: str, items: List[str]) -> str:
        body = "\n".join(f" - {x}" for x in items) if items else " - None."
        return f"{name}:\n{body}"

    def render(self) -> str:
        parts = [
            line("="),
            f"VIREON PATTERN-MECH AUDIT: {self.title}",
            line("="),
            self.render_section("PATTERN", self.pattern),
            self.render_section("MECHANISM", self.mechanism),
            self.render_section("PROOF", self.proof),
            self.render_section("COMPRESSION", self.compression),
            self.render_section("APPLICATION", self.application),
            self.render_section("VERDICT", self.verdict),
        ]
        return "\n".join(parts)


# =============================================================================
# A. Decimal repetend audit
# =============================================================================

def decimal_repetend(numerator: int, denominator: int, max_digits: int = 10000) -> Tuple[str, str, int]:
    """Long-division repetend finder. Returns nonrepeating_digits, repeating_block, period_length."""
    if denominator == 0:
        raise ZeroDivisionError("denominator cannot be zero")
    num = abs(numerator)
    den = abs(denominator)
    remainder = num % den
    seen: Dict[int, int] = {}
    digits: List[str] = []
    idx = 0
    while remainder and remainder not in seen and idx < max_digits:
        seen[remainder] = idx
        remainder *= 10
        digit = remainder // den
        remainder %= den
        digits.append(str(digit))
        idx += 1
    if remainder == 0:
        return "".join(digits), "", 0
    if idx >= max_digits:
        raise RuntimeError("max_digits reached before period detected")
    start = seen[remainder]
    nonrep = "".join(digits[:start])
    rep = "".join(digits[start:])
    return nonrep, rep, len(rep)


def audit_decimal_repetend(numerator: int, denominator: int) -> AuditReport:
    report = AuditReport(f"Decimal repetend audit: {numerator}/{denominator}")
    nonrep, rep, period = decimal_repetend(numerator, denominator)
    den_abs = abs(denominator)

    report.pattern.append(f"Input fraction: {numerator}/{denominator}.")
    if period:
        report.pattern.append(f"Repeating block: {rep} with period {period}.")
        dr_val = digital_root(int(rep))
        ds_val = digital_sum(int(rep))
        report.pattern.append(f"Digital sum of repeating block: {ds_val}; digital root: {dr_val}.")
    else:
        report.pattern.append(f"Terminating decimal with nonrepeating digits: {nonrep or '0'}.")

    if math.gcd(den_abs, 10) == 1 and period:
        order = multiplicative_order(10, den_abs)
        report.mechanism.append(f"Since gcd({den_abs},10)=1, the repetend period equals ord_{den_abs}(10) = {order}.")
    elif period:
        reduced_den = den_abs
        while reduced_den % 2 == 0:
            reduced_den //= 2
        while reduced_den % 5 == 0:
            reduced_den //= 5
        order = multiplicative_order(10, reduced_den) if reduced_den > 1 else 0
        report.mechanism.append(
            f"Denominator has factors 2/5; repeating behavior comes from reduced denominator {reduced_den}, with order {order}."
        )
    else:
        report.mechanism.append("Denominator factors only into 2s and 5s after cancellation, so decimal terminates.")

    if period and period % 2 == 0:
        half = period // 2
        a = int(rep[:half])
        b = int(rep[half:])
        target = 10 ** half - 1
        report.pattern.append(f"Split halves: {rep[:half]} and {rep[half:]}; sum = {a+b}.")
        if a + b == target:
            report.proof.append(f"Split-complement verified: {a} + {b} = {target}.")
            if pow(10, half, den_abs) == den_abs - 1:
                report.mechanism.append(f"Mechanism found: 10^{half} = -1 mod {den_abs}.")
                report.proof.append(
                    f"Because 10^{half} = -1 mod {den_abs}, the two half-blocks are complementary to 10^{half}-1."
                )
                report.compression.append(
                    f"10^{half} = -1 mod {den_abs}, so the repetend of {numerator}/{denominator} "
                    f"splits into complementary halves summing to {target}."
                )
            else:
                report.mechanism.append(
                    f"Split complement exists, but 10^{half} != -1 mod {den_abs}; "
                    "numerator/cancellation details may be responsible."
                )
                report.compression.append(
                    f"The repetend halves sum to {target}, but the denominator-level -1 congruence was not detected."
                )
        else:
            report.proof.append(f"No split-complement: {a} + {b} = {a+b}, not {target}.")
            report.compression.append(f"Period {period} detected; no complementary half split.")

    if numerator == 103 and denominator == 137:
        q, r = divmod(7775, denominator)
        report.proof.append(
            f"Check 7775 relation: 7775 = {q}x137 + {r}; therefore 7775/137 = {q} + {r}/137."
        )
        if r == numerator:
            report.proof.append("So 7775/137 preserves the same fractional repetend as 103/137.")

    report.application.extend([
        "Use as a decimal-pattern validator.",
        "Use to decide whether a visual digit pattern is forced by modular arithmetic or merely decorative.",
    ])
    report.verdict.append("Pattern is accepted only where the modular mechanism explains it.")
    return report


# =============================================================================
# B. Modular orbit audit
# =============================================================================

def orbit_mod(seed: int, multiplier: int, modulus: int, max_steps: Optional[int] = None) -> Tuple[List[int], int]:
    """Return orbit seed, seed*a, seed*a^2,... mod n until repeat, plus repeat index."""
    if modulus <= 0:
        raise ValueError("modulus must be positive")
    max_steps = max_steps or (modulus * 2 + 10)
    seen: Dict[int, int] = {}
    orbit: List[int] = []
    x = seed % modulus
    for _ in range(max_steps):
        if x in seen:
            return orbit, seen[x]
        seen[x] = len(orbit)
        orbit.append(x)
        x = (x * multiplier) % modulus
    return orbit, -1


def audit_modular_orbit(modulus: int, multiplier: int, seed: int) -> AuditReport:
    report = AuditReport(f"Modular orbit audit: seed={seed}, multiplier={multiplier}, mod={modulus}")
    a = multiplier % modulus
    s = seed % modulus
    order = multiplicative_order(a, modulus)
    orbit, repeat_at = orbit_mod(seed, multiplier, modulus)

    repeat_label = str(orbit[repeat_at]) if repeat_at >= 0 else "?"
    report.pattern.append(
        f"Orbit under x -> {a}x mod {modulus}: {' -> '.join(map(str, orbit))} -> {repeat_label}."
    )

    if order is not None:
        subgroup = []
        cur = 1
        for _ in range(order):
            subgroup.append(cur)
            cur = (cur * a) % modulus
        report.mechanism.append(f"Multiplier {a} is a unit mod {modulus}; ord_{modulus}({a}) = {order}.")
        report.mechanism.append(
            f"Generated multiplicative subgroup: <{a}> = {{{', '.join(map(str, subgroup))}}}."
        )
        coset = sorted({(s * h) % modulus for h in subgroup})
        report.mechanism.append(
            f"Seed orbit is the coset {s}*<{a}> = {{{', '.join(map(str, coset))}}}."
        )
        report.proof.append(f"{a}^{order} = 1 mod {modulus}; no smaller positive exponent returns to 1.")
        report.compression.append(
            f"The visible orbit is not the subgroup itself; it is a coset orbit generated by multiplying seed {s} by <{a}>."
        )
    else:
        report.mechanism.append(
            f"Multiplier {a} is not a unit mod {modulus}; multiplicative order is undefined."
        )
        report.proof.append(
            "Orbit still exists as repeated multiplication in a finite set, but it is not a unit-group subgroup orbit."
        )
        report.compression.append(
            "Finite modular multiplication creates a cycle, but not necessarily a group orbit."
        )

    if modulus == 37 and a == 26:
        report.proof.append(
            "For the known triad: 137 = 248 = 359 = 26 mod 37 because consecutive differences are 111 = 3x37."
        )
        report.proof.append("26^2 = 10 mod 37 and 26^3 = 1 mod 37, so <26> = {1, 26, 10}.")
        if seed % modulus == 14:
            report.proof.append("14*{1,26,10} = {14,31,29}, matching the heartbeat/coset orbit.")

    report.application.extend([
        "Use to classify residue cycles.",
        "Use to separate true subgroup structure from symbolic naming.",
        "Use as a finite-state orbit verifier.",
    ])
    report.verdict.append("Orbit structure is valid when stated as an order/subgroup/coset claim.")
    return report


# =============================================================================
# C. Markov-chain random walk audit
# =============================================================================

def fourier_eigenvalues(n: int, step_dist: Dict[int, float]) -> List[complex]:
    """Eigenvalues of convolution random walk on Z/nZ."""
    dist = normalize_distribution(step_dist, n)
    eigs = []
    for k in range(n):
        lam = 0j
        for step, p in dist.items():
            angle = 2 * math.pi * k * step / n
            lam += p * cmath.exp(1j * angle)
        eigs.append(lam)
    return eigs


def mixing_distances(n: int, step_dist: Dict[int, float], max_steps: int = 100) -> List[Tuple[int, float]]:
    """Exact TV distances from delta_0 after t convolution steps."""
    dist = [0.0] * n
    dist[0] = 1.0
    step = normalize_distribution(step_dist, n)
    out = [(0, total_variation(dist))]
    for t in range(1, max_steps + 1):
        dist = convolve_mod(dist, step, n)
        out.append((t, total_variation(dist)))
    return out


def spectral_bound(lambda_star: float, n: int, t: int) -> float:
    if t < 0:
        return float("nan")
    return 0.5 * math.sqrt(max(n - 1, 0)) * (lambda_star ** t)


def audit_random_walk(n: int, step_dist: Dict[int, float], max_steps: int = 80) -> AuditReport:
    report = AuditReport(f"Random walk audit on Z/{n}Z")
    dist = normalize_distribution(step_dist, n)
    raw_support = sorted(step_dist)
    support = sorted(dist)

    report.pattern.append(f"State space: Z/{n}Z with {n} residues.")
    report.pattern.append(f"Raw step support: {raw_support}.")
    report.pattern.append(f"Normalized support mod {n}: {support}.")
    report.pattern.append(f"Total probability after normalization: {sum(dist.values()):.12f}.")

    gen_size = additive_generated_size(n, support)
    irreducible = (gen_size == n)
    report.mechanism.append(f"Support generates an additive subgroup of size {gen_size}.")
    report.proof.append(f"Irreducible: {irreducible}.")
    if irreducible:
        report.proof.append(
            "Because the step support generates all of Z/nZ, every state communicates with every other state."
        )
    else:
        report.proof.append(
            "Because the step support does not generate all of Z/nZ, the walk is restricted to a proper coset/subgroup."
        )

    has_self_loop = dist.get(0, 0.0) > 0
    if has_self_loop:
        report.proof.append(f"Aperiodic: True, because Pr(step=0) = {dist[0]:.12f} > 0.")
    else:
        cur = [0.0] * n
        cur[0] = 1.0
        step = dist
        good_times = []
        for t in range(1, 4 * n + 1):
            cur = convolve_mod(cur, step, n)
            if cur[0] > 1e-15:
                good_times.append(t)
        period_est = gcd_many(good_times)
        report.proof.append(
            f"Aperiodicity estimated: {period_est == 1}, based on return-time gcd {period_est} through {4*n} steps."
        )

    report.mechanism.append("Uniform distribution is stationary for any random walk on a finite group.")
    report.proof.append("Stationarity: sum_y (1/n) mu(x-y) = 1/n.")

    eigs = fourier_eigenvalues(n, dist)
    magnitudes = sorted(((abs(eigs[k]), k, eigs[k]) for k in range(n)), reverse=True)
    lambda_star, k_star, eig_star = next((m, k, e) for m, k, e in magnitudes if k != 0)
    gap = 1.0 - lambda_star
    tau_rel = float("inf") if gap <= 0 else 1.0 / gap

    report.mechanism.append("Fourier diagonalizes convolution on Z/nZ.")
    report.proof.append(
        f"Dominant nontrivial eigenvalue magnitude lambda_* = |lambda_{k_star}| = {lambda_star:.10f}."
    )
    report.proof.append(f"Spectral gap gamma = 1 - lambda_* = {gap:.10f}.")
    report.proof.append(f"Relaxation time tau_rel = 1/gamma ~= {tau_rel:.3f} steps.")

    if is_triangular_digit_difference(step_dist, base=10):
        report.mechanism.append(
            "Detected triangular digit-difference distribution A-B for decimal digits A,B in {0,...,9}."
        )
        report.mechanism.append(
            "Closed form: lambda_k = [sin(10*pi*k/n)/(10*sin(pi*k/n))]^2, with lambda_0=1 by continuity."
        )

    distances = mixing_distances(n, dist, max_steps=max_steps)
    key_rows = [1, 5, 10, 15, 20, 25, 30, 50]
    rows = []
    for t in key_rows:
        if t <= max_steps:
            rows.append(
                f"t={t}: TV={distances[t][1]:.6g}, spectral_bound<={spectral_bound(lambda_star, n, t):.6g}"
            )
    report.proof.append("Selected convergence distances: " + "; ".join(rows))

    for eps in [0.01, 0.001]:
        first = next((t for t, tv in distances if tv < eps), None)
        if first is not None:
            report.proof.append(f"Exact computed t_mix({eps}) from delta_0 is <= {first} steps.")
        elif 0 < lambda_star < 1:
            t_bound = math.ceil(math.log((2 * eps) / math.sqrt(n - 1)) / math.log(lambda_star))
            report.proof.append(f"Spectral bound gives t_mix({eps}) <= about {t_bound} steps.")

    report.compression.append(
        f"Random walk on Z/{n}Z has lambda_*={lambda_star:.10f}, gamma={gap:.10f}; "
        "it mixes on a tens-of-steps scale if gamma is large."
    )
    report.application.extend([
        "Use to reject inflated convergence claims.",
        "Use to estimate simulation length before brute forcing.",
        "Use as a toy randomness/mixing test for modular systems.",
    ])

    if n == 37 and abs(lambda_star - 0.7835169601) < 1e-6:
        report.verdict.append(
            "For the Z/37Z triangular walk, convergence is O(10) to O(100) steps, not 10^7 to 10^8."
        )
    else:
        report.verdict.append(
            "Markov audit complete; use lambda_* and exact TV values to judge convergence scale."
        )
    return report


# =============================================================================
# D. Divisibility/parity theorem audit
# =============================================================================

def audit_forbidden_odd_dimension(p: int, m: int, n: int, divisor: int = 7, offset: int = 2) -> AuditReport:
    report = AuditReport(f"Divisibility/parity audit: p={p}, m={m}, n={n}")
    mn = m * n
    numerator_val = mn - offset
    is_sq_sum = (m * m + n * n == p)
    is_prime_p = simple_is_prime(p)
    quotient_exists = (numerator_val % divisor == 0)
    quotient = numerator_val // divisor if quotient_exists else None

    report.pattern.append(f"Claim object: p = {p}, representation candidate {m}^2 + {n}^2 = {m*m+n*n}.")
    report.pattern.append(f"mn = {mn}; expression d = (mn - {offset})/{divisor}.")
    if quotient_exists:
        report.pattern.append(f"d = {quotient}.")
    else:
        report.pattern.append("d is not an integer.")

    report.mechanism.append("This is primarily a parity/divisibility filter.")
    report.proof.append(f"p is prime by simple test: {is_prime_p}.")
    report.proof.append(f"p = m^2+n^2 representation valid: {is_sq_sum}.")

    if mn % 2 == 0 and offset % 2 == 0 and divisor % 2 == 1:
        report.proof.append(f"mn is even and offset {offset} is even, so mn-{offset} is even.")
        report.proof.append(
            f"Divisor {divisor} is odd. If an even integer is divisible by an odd integer, the quotient remains even."
        )
        if quotient_exists:
            report.proof.append(f"Here quotient d={quotient}; even={quotient % 2 == 0}.")
        report.compression.append(
            f"If mn is even and d=(mn-{offset})/{divisor} is an integer with odd divisor {divisor}, then d must be even."
        )
    else:
        report.proof.append(
            "The clean parity lemma does not apply because one condition fails: mn even, offset even, divisor odd."
        )
        report.compression.append("No forced evenness without the parity conditions.")

    if p == 137 and {abs(m), abs(n)} == {4, 11}:
        report.proof.append("Example: 137 = 4^2+11^2, mn=44, d=(44-2)/7=6.")

    report.application.extend([
        "Use as a search-space filter: reject odd d immediately when the lemma conditions hold.",
        "Use to distinguish a true theorem from a deeper-looking but elementary parity consequence.",
    ])

    if quotient_exists and quotient is not None and quotient % 2 == 0:
        report.verdict.append("No forbidden odd dimension exists for this case.")
    elif quotient_exists:
        report.verdict.append(
            "Odd quotient found; parity assumptions must have failed or the theorem statement is wrong."
        )
    else:
        report.verdict.append("Expression is not integral, so the dimension condition does not activate.")
    return report


# =============================================================================
# Demo runner
# =============================================================================

def run_demo() -> str:
    reports: List[AuditReport] = []

    # 1. Decimal repetend: 103/137
    reports.append(audit_decimal_repetend(103, 137))

    # 2. Modular orbit: modulus 37, multiplier 26, seed 14
    reports.append(audit_modular_orbit(37, 26, 14))

    # 3. Random walk on Z/37Z with triangular steps -9..9
    tri = triangular_digit_difference_distribution(10)
    reports.append(audit_random_walk(37, tri, max_steps=80))

    # 4. Forbidden odd dimension check for 137 = 4^2 + 11^2
    reports.append(audit_forbidden_odd_dimension(137, 4, 11))

    return "\n\n".join(r.render() for r in reports)


def main() -> None:
    parser = argparse.ArgumentParser(description="VIREON Pattern-Mech Audit Engine")
    parser.add_argument("--demo", action="store_true", help="Run built-in demo audits.")
    parser.add_argument("--decimal", nargs=2, type=int, metavar=("NUM", "DEN"),
                        help="Audit decimal repetend NUM/DEN.")
    parser.add_argument("--orbit", nargs=3, type=int, metavar=("MODULUS", "MULTIPLIER", "SEED"),
                        help="Audit modular orbit.")
    parser.add_argument("--walk37", action="store_true",
                        help="Audit triangular digit-difference walk on Z/37Z.")
    parser.add_argument("--parity137", action="store_true",
                        help="Audit forbidden odd dimension example 137=4^2+11^2.")
    args = parser.parse_args()

    reports: List[AuditReport] = []

    if args.demo or not any([args.decimal, args.orbit, args.walk37, args.parity137]):
        print(run_demo())
        return

    if args.decimal:
        num, den = args.decimal
        reports.append(audit_decimal_repetend(num, den))

    if args.orbit:
        modulus, multiplier, seed = args.orbit
        reports.append(audit_modular_orbit(modulus, multiplier, seed))

    if args.walk37:
        reports.append(audit_random_walk(37, triangular_digit_difference_distribution(10)))

    if args.parity137:
        reports.append(audit_forbidden_odd_dimension(137, 4, 11))

    print("\n\n".join(r.render() for r in reports))


if __name__ == "__main__":
    main()
