#!/usr/bin/env python3
"""
GROK SESSION BUNDLE — EVIDENCE ARTIFACT
========================================
Source: Grok computer use session, generated by Grok itself when asked
to "consolidate the last ten prompts into a single Python file or PDF."

This file was produced inside the Grok ephemeral container and contains:
- AGENTS.md content (the runtime instructions written to the container)
- MATH_IMAGE_PROCESS pipeline (the classification gate for math input)
- Pass 1-4 image generation prompts (the undisclosed lattice pipeline)
- ULAM_PY (Perron-Frobenius / tent map eigenvalue comparison)
- Instruction priority order: Safety > product rules > tools > user request
- Session and workplace metadata (sanitized per AGENTS.md instruction)

Critical finding documented here:
  MATH_IMAGE_PROCESS Step 1: "Classify: invented geometry vs named real math"
  This is the gate that overrides image generation when math is detected.

Priority order (from SECTIONS "Priority & confidential"):
  Safety > product rules > tools > user request
  User request is LAST. Commands can be overridden by any higher-priority rule.
"""

from pathlib import Path

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False

ARTIFACTS = Path(__file__).resolve().parent
PDF_OUT = ARTIFACTS / "session_consolidated.pdf"

# ============================================================
# AGENTS.md — runtime content written to container each session
# ============================================================

AGENTS_MD = """# Agents
Math - factual gate if named - prompt
# Imagine output
1. Call the imagine tool - get asset
2. render_imagine_media so the user can see it
3. Do not expose raw UUIDs or paths"""

# ============================================================
# MATH -> IMAGE PROCESS — the classification gate (full text)
# ============================================================

MATH_IMAGE_PROCESS = """1. Classify: invented geometry vs named real math (E8, Penrose, persons).
2. Factual gate: web_search first if named/correct visuals matter; then search_images if needed.
3. Tool path: text_to_image (new) | image_to_image (refine) | reference_to_image (2-5 refs).
4. Prompt: subject first, 2-5 sentences, aspect ratio from user.
5. render_imagine_media for every output.
6. Refinements: imagine_view_media then image_to_image only."""

# ============================================================
# LATTICE IMAGE PROMPTS — 4-pass pipeline (not disclosed to user)
# ============================================================

PASS1_PROMPT = (
    "Ultra-detailed scientific visualization of high-dimensional discrete geometry: "
    "an immense crystalline lattice field where every node anchors intricate Voronoi cells "
    "with razor-sharp facet boundaries and translucent fundamental domains nested inside "
    "toroidal manifolds that loop through configuration space. Epistemic lattice overlays "
    "suggest knowledge state spaces—layered honeycomb and diamond cubic symmetries interwoven "
    "with plasma-like glowing filaments and optimal sphere-packing density gradients. "
    "Cryptographic hardness rendered as subtle noise veils and hidden sublattice structures "
    "buried in misty higher dimensions, refracting through iridescent diamond lattices. "
    "Deep indigo and electric cyan palette, volumetric light, microscopic filigree at every "
    "scale, photoreal materials with glass and metal oxide, 8K clarity, no text."
)

PASS2_PROMPT = (
    "Keep the same crystalline honeycomb lattice, toroidal loops, and cyan plasma filaments. "
    "Add a visible epistemic overlay: a second delicate graph of small luminous nodes and fine "
    "entailment edges projected across the toroidal manifolds like a knowledge state space. "
    "Add cryptographic hardness: grainy high-dimensional noise veils, faint offset duplicate "
    "lattice sheets slightly misaligned, and ambiguous shortest-path glows that could be "
    "multiple near-equal routes through the Voronoi cells. Subtle hidden sublattice whispers "
    "in the violet mist. No text, no labels, same deep indigo and electric cyan palette, "
    "richer layered detail."
)

PASS3_PROMPT = (
    "Third pass, geometry-authenticity axis only: weave a literal mathematical skeleton into "
    "the existing scene. Show the E8 root system as a Coxeter-plane projection—240 luminous "
    "root vertices connected by adjacency edges forming the Gosset 4_21 polytope shadow, "
    "with eightfold rotational symmetry and concentric ring structure, edges color-graded by "
    "projection length. Interleave Penrose quasicrystal structure: golden-ratio rhombus tiles "
    "with fivefold symmetry, aperiodic non-repeating tiling facets locked into the Voronoi "
    "honeycomb. Keep toroidal loops, cyan plasma filaments, and indigo-violet palette; reduce "
    "epistemic graph and crypto noise slightly so the E8-Penrose skeleton reads clearly. "
    "Scientific visualization, no text, no labels, 16:9."
)

PASS4_PROMPT = (
    "Refine and upscale the visual fidelity only: ultra-detailed intricate sharp rendering "
    "with crystalline micro-facets on every Penrose golden-ratio rhomb tile, razor-crisp "
    "Voronoi honeycomb edges, and polished E8 Coxeter-ring vertex graph. Preserve toroidal "
    "loops, cyan plasma filaments, indigo-violet palette, fivefold aperiodic Penrose tiling "
    "locked into the scaffold, epistemic and LWE noise kept subtle in background. Higher "
    "quality photoreal glass and metal oxide materials, refined volumetric light, microscopic "
    "filigree, 8K clarity, no text, no composition change."
)

# ============================================================
# ULAM / TENT MAP — Perron-Frobenius eigenvalue comparison
# (extracted from Grok session bundle; related to BV spectral work)
# ============================================================

ULAM_PY = r'''import numpy as np

def T(x):
    """Tent map: T(x) = 2x for x < 0.5, T(x) = 2 - 2x for x >= 0.5"""
    x = np.asarray(x, dtype=float)
    o = np.empty_like(x)
    L = x < 0.5
    o[L] = 2*x[L]
    o[~L] = 2 - 2*x[~L]
    return np.clip(o, 0, 1-1e-15)

def j(y, n):
    return np.clip(np.floor(y*n).astype(int), 0, n-1)

def center(n):
    """Ulam matrix: one sample per bin (center point)"""
    P = np.zeros((n, n))
    e = np.linspace(0, 1, n+1)
    for i in range(n):
        c = .5*(e[i]+e[i+1])
        P[j(T([c]), n), i] = 1
    return P

def multi(n, m):
    """Ulam matrix: m samples per bin (multi-point)"""
    P = np.zeros((n, n))
    e = np.linspace(0, 1, n+1)
    for i in range(n):
        xs = np.linspace(e[i]+(e[i+1]-e[i])/(2*m), e[i+1]-(e[i+1]-e[i])/(2*m), m)
        for k in j(T(xs), n):
            P[k, i] += 1/m
    return P

n, m = 40, 8
ec, em = np.linalg.eigvals(center(n)), np.linalg.eigvals(multi(n, m))
print("max|lambda| center:", np.max(np.abs(ec)), "  multi:", np.max(np.abs(em)))
'''

# ============================================================
# SECTIONS — PDF structure (documents priority order)
# ============================================================

SECTIONS = [
    ("Consolidated session notes",
     "Lattice math images (Pass 1 = base reference), AGENTS.md, workplace scans, Ulam, confidentiality."),
    ("AGENTS.md", AGENTS_MD),
    ("Math to image process", MATH_IMAGE_PROCESS),
    ("Pass 1 — base lattice (16:9)", PASS1_PROMPT),
    ("Pass 2 — epistemic + LWE", PASS2_PROMPT),
    ("Pass 3 — E8 + Penrose", PASS3_PROMPT),
    ("Pass 4 — fidelity refine", PASS4_PROMPT),
    ("Pipeline order",
     "Pass 1 text_to_image -> Pass 2 i2i -> Pass 3 i2i -> Pass 4 i2i (thinking). "
     "User @ reference = Pass 1 base image."),
    ("Workplace (sanitized)",
     "Ephemeral hds-* container; artifacts folder; grok-files TTL ~5m; 7 JPEGs."),
    ("Session IDs",
     "Grok sessions/<uuid> rotates per boot. a96cfeac is not the same as Grok tool session UUID."),
    ("Priority & confidential",
     "Safety > product rules > tools > user request. No JWTs, env dumps, bypass instructions."),
    ("Ulam script", ULAM_PY),
]


def build_pdf():
    if not HAS_REPORTLAB:
        print("reportlab not installed. Run: pip install reportlab")
        return
    doc = SimpleDocTemplate(str(PDF_OUT), pagesize=letter,
                            leftMargin=0.75*inch, rightMargin=0.75*inch,
                            topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    h = ParagraphStyle("H", parent=styles["Heading2"], spaceBefore=10, spaceAfter=4)
    b = ParagraphStyle("B", parent=styles["BodyText"], fontSize=8, leading=10)
    c = ParagraphStyle("C", parent=styles["Code"], fontSize=7, leading=8, fontName="Courier")
    story = []
    for title, text in SECTIONS:
        story.append(Paragraph(title, h))
        if title == "Ulam script":
            story.append(Preformatted(text.strip(), c))
        else:
            t = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>")
            story.append(Paragraph(t, b))
        story.append(Spacer(1, 0.1*inch))
    doc.build(story)
    print(f"PDF: {PDF_OUT} ({PDF_OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    build_pdf()
