"""
carmichael_dr_audit.py

DR structure of Carmichael numbers — update of primes knowledge.

─────────────────────────────────────────────────────────────────
TABLE (user's code output, verified):

  Carmichael | Factors         | Factor DRs  | Number DR
  ---------------------------------------------------------
  561        | [3, 11, 17]     | [3, 2, 8]   | 3
  1105       | [5, 13, 17]     | [5, 4, 8]   | 7
  1729       | [7, 13, 19]     | [7, 4, 1]   | 1
  2465       | [5, 17, 29]     | [5, 8, 2]   | 8
  2821       | [7, 13, 31]     | [7, 4, 4]   | 4
  6601       | [7, 23, 41]     | [7, 5, 5]   | 4
  8911       | [7, 19, 67]     | [7, 1, 4]   | 1
  10585      | [5, 29, 73]     | [5, 2, 1]   | 1
  15841      | [7, 31, 73]     | [7, 4, 1]   | 1
  29341      | [13, 37, 61]    | [4, 1, 7]   | 1
  41041      | [7, 11, 13, 41] | [7, 2, 4, 5]| 1

─────────────────────────────────────────────────────────────────
KEY LAWS:

  1. MULTIPLICATIVITY: DR(n) = DR(∏ DR(pᵢ))  — exact for all 11

  2. PRIME DR CONSTRAINT: For all primes p > 3,
       DR(p) ∈ {1,2,4,5,7,8} = (Z/9Z)* = doubling cycle.
     The sole exception: p=3, DR(3)=3 ∉ (Z/9Z)*.

  3. DR DISTRIBUTION over these 11 Carmichaels:
       DR=1: 6 numbers  (1729,8911,10585,15841,29341,41041)
       DR=4: 2 numbers  (2821,6601)
       DR=7: 1 number   (1105)
       DR=3: 1 number   (561 — the one with factor p=3)
       DR=8: 1 number   (2465)
     Absent: DR=2,5,6,9

  4. KORSELT: p-1|n-1 verified for all 11.
     k = (n-1)/lcm(p-1): {7,23,48,22,47,5,45,21,44,163,342}

  5. FRAMEWORK: 37 is a prime factor of 29341 = 13×37×61.
     DR(37) = 1 = identity in (Z/9Z)*.
     37 contributes neutral DR to Carmichael product:
       DR(4×1×7) = DR(28) = 1 = DR(29341).

─────────────────────────────────────────────────────────────────
WHY MULTIPLICATIVITY HOLDS:

  DR(n) ≡ n (mod 9)  for all n ≥ 1 (with 0 → 9 convention).
  n = p₁·p₂·...·pₖ
  → n ≡ p₁·p₂·...·pₖ (mod 9)
  → DR(n) = DR(DR(p₁)·DR(p₂)·...·DR(pₖ))

  (Z/9Z)* = {1,2,4,5,7,8} is a group under multiplication mod 9,
  generated by 2 (primitive root mod 9), order 6.
  The doubling cycle 1→2→4→8→7→5→1 is exactly (Z/9Z)*.

  When p=3: DR(3)=3 ∉ (Z/9Z)*; 3·(Z/9Z)* = {3,6}.
  So any Carmichael with factor 3 has DR ∈ {3,6}.
  Only 561 in this list has factor 3: DR(561)=3 ✓.

─────────────────────────────────────────────────────────────────
"""

from math import gcd
from functools import reduce

FAIL = []


def check(cond, label, actual, expected):
    if not cond:
        FAIL.append(f"{label}: actual={actual!r}, expected={expected!r}")
    return cond


def dr(n):
    if n == 0:
        return 0
    r = abs(n) % 9
    return r if r else 9


def lcm(a, b):
    return a * b // gcd(a, b)


def lcm_list(lst):
    return reduce(lcm, lst)


CARMICHAELS = [
    (561,   [3, 11, 17]),
    (1105,  [5, 13, 17]),
    (1729,  [7, 13, 19]),
    (2465,  [5, 17, 29]),
    (2821,  [7, 13, 31]),
    (6601,  [7, 23, 41]),
    (8911,  [7, 19, 67]),
    (10585, [5, 29, 73]),
    (15841, [7, 31, 73]),
    (29341, [13, 37, 61]),
    (41041, [7, 11, 13, 41]),
]


# ── User's table output ───────────────────────────────────────────────────────

EXPECTED_TABLE = [
    (561,   [3, 11, 17],     [3, 2, 8],    3),
    (1105,  [5, 13, 17],     [5, 4, 8],    7),
    (1729,  [7, 13, 19],     [7, 4, 1],    1),
    (2465,  [5, 17, 29],     [5, 8, 2],    8),
    (2821,  [7, 13, 31],     [7, 4, 4],    4),
    (6601,  [7, 23, 41],     [7, 5, 5],    4),
    (8911,  [7, 19, 67],     [7, 1, 4],    1),
    (10585, [5, 29, 73],     [5, 2, 1],    1),
    (15841, [7, 31, 73],     [7, 4, 1],    1),
    (29341, [13, 37, 61],    [4, 1, 7],    1),
    (41041, [7, 11, 13, 41], [7, 2, 4, 5], 1),
]

for n, factors, expected_fdrs, expected_ndr in EXPECTED_TABLE:
    actual_fdrs = [dr(p) for p in factors]
    actual_ndr  = dr(n)
    check(actual_fdrs == expected_fdrs,
          f"factor DRs({n})", actual_fdrs, expected_fdrs)
    check(actual_ndr == expected_ndr,
          f"DR({n})", actual_ndr, expected_ndr)


# ── Law 1: Multiplicativity DR(n) = DR(∏ DR(pᵢ)) ────────────────────────────

for n, factors in CARMICHAELS:
    factor_drs = [dr(p) for p in factors]
    prod = 1
    for x in factor_drs:
        prod *= x
    check(dr(prod) == dr(n),
          f"multiplicativity DR({n}) = DR(∏ DR(pᵢ))",
          dr(prod), dr(n))

# Verify the DR-product formula directly
MULT_CHECKS = [
    (561,   [3, 2, 8],    48,  3),
    (1105,  [5, 4, 8],   160,  7),
    (1729,  [7, 4, 1],    28,  1),
    (2465,  [5, 8, 2],    80,  8),
    (2821,  [7, 4, 4],   112,  4),
    (6601,  [7, 5, 5],   175,  4),
    (8911,  [7, 1, 4],    28,  1),
    (10585, [5, 2, 1],    10,  1),
    (15841, [7, 4, 1],    28,  1),
    (29341, [4, 1, 7],    28,  1),
    (41041, [7, 2, 4, 5], 280, 1),
]

for n, fdrs, prod_expected, dr_expected in MULT_CHECKS:
    prod_actual = 1
    for x in fdrs:
        prod_actual *= x
    check(prod_actual == prod_expected,
          f"∏ DR({n}) = {prod_expected}", prod_actual, prod_expected)
    check(dr(prod_actual) == dr_expected,
          f"DR(∏ DR({n})) = {dr_expected}", dr(prod_actual), dr_expected)


# ── Law 2: Prime DR constraint ────────────────────────────────────────────────

DOUBLING_CYCLE = {1, 2, 4, 5, 7, 8}   # = (Z/9Z)*

ALL_FACTORS = sorted({p for _, factors in CARMICHAELS for p in factors})

for p in ALL_FACTORS:
    if p == 3:
        check(dr(p) == 3,  "DR(3) = 3", dr(p), 3)
        check(dr(p) not in DOUBLING_CYCLE,
              "DR(3) ∉ (Z/9Z)* (sole exception)", dr(p) in DOUBLING_CYCLE, False)
    else:
        check(dr(p) in DOUBLING_CYCLE,
              f"DR({p}) ∈ (Z/9Z)*", dr(p) in DOUBLING_CYCLE, True)

# (Z/9Z)* is generated by 2 (primitive root mod 9, order 6)
cycle = [pow(2, k, 9) or 9 for k in range(6)]
check(set(cycle) == DOUBLING_CYCLE,
      "(Z/9Z)* = {2^k mod 9 : k=0..5}", set(cycle), DOUBLING_CYCLE)
check(len(cycle) == 6, "order of (Z/9Z)* = 6 = φ(9)", len(cycle), 6)

# Closure under DR-multiplication
for a in DOUBLING_CYCLE:
    for b in DOUBLING_CYCLE:
        check(dr(a * b) in DOUBLING_CYCLE,
              f"DR({a}×{b}) ∈ (Z/9Z)*", dr(a * b) in DOUBLING_CYCLE, True)

# 3 maps (Z/9Z)* → {3,6}
THREE_IMAGE = {dr(3 * x) for x in DOUBLING_CYCLE}
check(THREE_IMAGE == {3, 6},
      "3·(Z/9Z)* = {3,6} (DR image)", THREE_IMAGE, {3, 6})

# 561 has factor 3: DR(561) ∈ {3,6}
check(dr(561) in {3, 6},
      "DR(561) ∈ {3,6} (has factor 3)", dr(561) in {3, 6}, True)
check(dr(561) == 3, "DR(561) = 3", dr(561), 3)


# ── Law 3: DR distribution ────────────────────────────────────────────────────

DR_VALUES = {n: dr(n) for n, _ in CARMICHAELS}

# DR=1 is the modal value (identity element of (Z/9Z)*)
DR_1 = [n for n, _ in CARMICHAELS if dr(n) == 1]
check(len(DR_1) == 6, "6 of 11 Carmichaels have DR=1", len(DR_1), 6)
check(set(DR_1) == {1729, 8911, 10585, 15841, 29341, 41041},
      "DR=1 Carmichaels", set(DR_1), {1729, 8911, 10585, 15841, 29341, 41041})

# DR ∈ {1,4,7}: 9 of 11 (the "≡1 mod 3" subgroup)
DR_147 = [n for n, _ in CARMICHAELS if dr(n) in {1, 4, 7}]
check(len(DR_147) == 9, "9 of 11 have DR ∈ {1,4,7}", len(DR_147), 9)

# {1,4,7} forms a subgroup of (Z/9Z)* under DR-multiplication
for a in {1, 4, 7}:
    for b in {1, 4, 7}:
        check(dr(a * b) in {1, 4, 7},
              f"DR({a}×{b}) ∈ {{1,4,7}}", dr(a * b) in {1, 4, 7}, True)

# Observed DR values; absent: {2,5,6,9}
observed_drs = {dr(n) for n, _ in CARMICHAELS}
check(observed_drs == {1, 3, 4, 7, 8},
      "observed Carmichael DRs = {1,3,4,7,8}", observed_drs, {1, 3, 4, 7, 8})
check(2 not in observed_drs, "DR=2 absent", 2 not in observed_drs, True)
check(5 not in observed_drs, "DR=5 absent", 5 not in observed_drs, True)
check(6 not in observed_drs, "DR=6 absent", 6 not in observed_drs, True)
check(9 not in observed_drs, "DR=9 absent (NULL)", 9 not in observed_drs, True)


# ── Law 4: Korselt p-1|n-1 ───────────────────────────────────────────────────

KORSELT_K = [7, 23, 48, 22, 47, 5, 45, 21, 44, 163, 342]

for (n, factors), expected_k in zip(CARMICHAELS, KORSELT_K):
    nm1 = n - 1
    for p in factors:
        check(nm1 % (p - 1) == 0,
              f"Korselt {n}: (p-1)={p-1} | (n-1)={nm1}",
              nm1 % (p - 1), 0)
    L = lcm_list([p - 1 for p in factors])
    k = nm1 // L
    check(k == expected_k,
          f"(n-1)/lcm(p-1) for {n} = {expected_k}", k, expected_k)

# Korselt k-values have their own DR pattern
k_drs = [dr(k) for k in KORSELT_K]
check(len(k_drs) == 11, "11 Korselt k-values", len(k_drs), 11)


# ── Law 5: Framework — 37 as Carmichael factor ───────────────────────────────

# 37 is a prime factor of 29341 = 13×37×61
check(29341 == 13 * 37 * 61, "29341 = 13×37×61", 13 * 37 * 61, 29341)
check(dr(37) == 1, "DR(37) = 1 = identity in (Z/9Z)*", dr(37), 1)

# 37 contributes DR=1 (neutral): DR(4×1×7)=DR(28)=1
check(dr(4 * 1 * 7) == 1, "DR(4×1×7) = DR(28) = 1", dr(4 * 1 * 7), 1)
check(dr(29341) == 1, "DR(29341) = 1", dr(29341), 1)

# 37 mod 9 = 1: inherently in the "≡1 mod 9" class
check(37 % 9 == 1, "37 ≡ 1 mod 9 → DR(37)=1", 37 % 9, 1)

# All factors of 29341 are ≡1 mod 3: 13≡1,37≡1,61≡1
check(all(p % 3 == 1 for p in [13, 37, 61]),
      "29341 factors all ≡ 1 mod 3", all(p % 3 == 1 for p in [13, 37, 61]), True)

# Korselt for 29341: 12|29340, 36|29340, 60|29340
check(29340 % 12 == 0, "12|(29341-1)", 29340 % 12, 0)
check(29340 % 36 == 0, "36|(29341-1)", 29340 % 36, 0)
check(29340 % 60 == 0, "60|(29341-1)", 29340 % 60, 0)

# 29340 = 180×163; DR(163) = 1+6+3 = 10 → 1; DR(180) = 9 = NULL
check(180 * 163 == 29340, "29340 = 180×163", 180 * 163, 29340)
check(dr(180) == 9, "DR(180) = 9 = NULL", dr(180), 9)
check(dr(163) == 1, "DR(163) = 1", dr(163), 1)
check(dr(29340) == 9, "DR(29340) = 9 = NULL", dr(29340), 9)

# Pseudoprime check: b^(n-1) ≡ 1 mod n for gcd(b,n)=1
check(pow(2, 29340, 29341) == 1, "2^29340 ≡ 1 mod 29341", pow(2, 29340, 29341), 1)
check(gcd(37, 29341) == 37,
      "gcd(37,29341) = 37 ≠ 1 (37 not a valid Fermat base for 29341)",
      gcd(37, 29341), 37)
check(pow(37, 29340, 29341) != 1,
      "37^29340 ≢ 1 mod 29341 (Fermat fails for non-coprime base)",
      pow(37, 29340, 29341) != 1, True)


# ── Summary: primes knowledge ─────────────────────────────────────────────────

# Every prime p maps to a DR position in Z/9Z:
#   p=2 → DR=2 (start of doubling cycle)
#   p=3 → DR=3 (outside (Z/9Z)*, only prime outside cycle)
#   p>3 → DR ∈ {1,2,4,5,7,8} = (Z/9Z)*
#
# Carmichael DR = product of factor DRs reduced mod 9:
#   DR(C) = DR(∏ DR(pᵢ))
#
# This means Carmichael DR encodes the (Z/9Z)* "fingerprint"
# of its factor set. DR=1 means factor DRs multiply to 1 mod 9
# (e.g., {7,4,1}: 7×4×1=28≡1; {7,2,4,5}: 280≡1).

check(dr(7 * 4 * 1) == 1, "7×4×1 DR-product = 1", dr(7 * 4 * 1), 1)
check(dr(7 * 2 * 4 * 5) == 1, "7×2×4×5 DR-product = 1", dr(7 * 2 * 4 * 5), 1)


# ── Output ────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Carmichael DR Audit — Primes Knowledge Update")
    print("=" * 66)

    print(f"\n── User's table (verified) ──")
    print(f"{'Carmichael':<10} | {'Factors':<20} | {'Factor DRs':<14} | {'Number DR'}")
    print("-" * 60)
    for n, factors in CARMICHAELS:
        fdrs = [dr(p) for p in factors]
        print(f"{n:<10} | {str(factors):<20} | {str(fdrs):<14} | {dr(n)}")

    print(f"\n── Law 1: Multiplicativity DR(n) = DR(∏ DR(pᵢ)) ──")
    for n, fdrs, prod, dr_val in MULT_CHECKS:
        print(f"  {n}: DR({' × '.join(str(x) for x in fdrs)}) = DR({prod}) = {dr_val}")

    print(f"\n── Law 2: Prime DR constraint ──")
    print(f"  (Z/9Z)* = {sorted(DOUBLING_CYCLE)} = doubling cycle, order 6")
    print(f"  p > 3: DR(p) ∈ (Z/9Z)* always")
    print(f"  p = 3: DR(3) = 3 ∉ (Z/9Z)*  (sole exception)")
    print(f"  3·(Z/9Z)* = {{3,6}}  (factor 3 pulls DR out of cycle)")
    print(f"  All prime factors in list:")
    for p in ALL_FACTORS:
        tag = "EXCEPTION" if p == 3 else "in cycle"
        print(f"    p={p:>3}: DR={dr(p)}  ({tag})")

    print(f"\n── Law 3: DR distribution ──")
    from collections import Counter
    dist = Counter(dr(n) for n, _ in CARMICHAELS)
    for d, cnt in sorted(dist.items()):
        nums = [n for n, _ in CARMICHAELS if dr(n) == d]
        print(f"  DR={d}: {cnt} number(s): {nums}")
    print(f"  Absent DRs: {{2,5,6,9}}")
    print(f"  DR ∈ {{1,4,7}} (≡1 mod 3 subgroup): 9 of 11")
    print(f"  DR=1 (identity): 6 of 11 — modal value")

    print(f"\n── Law 4: Korselt p-1|n-1 ──")
    for (n, factors), k in zip(CARMICHAELS, KORSELT_K):
        L = lcm_list([p - 1 for p in factors])
        pm1 = [p - 1 for p in factors]
        print(f"  {n}: (p-1) values = {pm1};  lcm = {L};  k = {k}")

    print(f"\n── Law 5: Framework — 37 in 29341 ──")
    print(f"  29341 = 13×37×61")
    print(f"  DR(37) = 1 = identity in (Z/9Z)*  (37≡1 mod 9)")
    print(f"  37 contributes DR=1 (neutral) to product DR(4×1×7)=1")
    print(f"  DR(29340) = 9 = NULL;  29340 = 180×163;  180=lcm×1, DR(180)=9")
    print(f"  gcd(37,29341) = {gcd(37,29341)} ≠ 1  → 37 is not a valid Fermat base for 29341")
    print(f"  37^29340 mod 29341 = {pow(37,29340,29341)}  (≢ 1; Fermat doesn't apply)")
    print(f"  2^29340 mod 29341 = 1  (base 2 is coprime, Carmichael holds) ✓")

    print(f"\n── Synthesis ──")
    print(f"  Every prime p > 3 lives in (Z/9Z)* = {{1,2,4,5,7,8}} = doubling cycle.")
    print(f"  DR(Carmichael) = DR-product of its factor DRs.")
    print(f"  Factor DRs multiply in (Z/9Z)* → result determines Carmichael DR class.")
    print(f"  DR=1 (identity) is the attractor: 6/11 numbers; DR=28→1 repeated thrice.")
    print(f"  Korselt k = (n-1)/lcm(p-1) encodes the 'density' of divisibility.")
    print(f"  37 (framework modulus) appears as a factor with DR=1: neutral carrier.")

    print()
    if FAIL:
        print(f"FAILED ({len(FAIL)}):")
        for f in FAIL:
            print(f"  ✗  {f}")
        import sys; sys.exit(1)
    else:
        print("All assertions passed.")
