# math/theorems/f37_hexagonal_decomposition_audit.py
"""
F_37× Hexagonal Decomposition — Full Algebraic Structure Audit
==============================================================

The multiplicative group F_37× is cyclic of order 36.
This audit verifies the two-face decomposition:

    10³ ≡  1 (mod 37)  → repeating decimal structure (1/37 period = 3)
    27³ ≡ −1 (mod 37)  → projective hexagonal lift

And the orbit construction:

    C3 = ⟨10⟩ = {1, 10, 26}       (rotational 3-cycle)
    −C3        = {36, 27, 11}      (antipodal image)
    C3 ∪ (−C3) = ⟨27⟩             (cyclic hexagon C6)

    C6 / {±1}  ≅ C3               (quotient collapses hexagon to triangle)
"""

P = 37

# ── 1. Multiplicative order of 10 ────────────────────────────────────────────

assert pow(10, 1, P) != 1
assert pow(10, 3, P) == 1        # order 3
assert pow(10, 2, P) == 26       # 10² = 26
# order 3 is the minimal such exponent:
assert pow(10, 2, P) != 1

ord10 = next(k for k in range(1, P) if pow(10, k, P) == 1)
assert ord10 == 3


# ── 2. Uniqueness of the order-3 subgroup ─────────────────────────────────────
# F_37× is cyclic of order 36; by Sylow / cyclic group theory,
# there is exactly one subgroup of each order dividing 36.

all_order3 = [x for x in range(1, P) if pow(x, 3, P) == 1]
assert sorted(all_order3) == [1, 10, 26]   # exactly one order-3 subgroup


# ── 3. Negated orbit −C3 ─────────────────────────────────────────────────────

C3     = {1, 10, 26}
neg_C3 = {(-x) % P for x in C3}
assert neg_C3 == {36, 27, 11}

# C3 and −C3 are disjoint (would coincide only if −1 ∈ C3)
assert C3.isdisjoint(neg_C3)
assert (P - 1) not in C3     # −1 = 36 ∉ C3


# ── 4. Union = ⟨27⟩ = C6 ─────────────────────────────────────────────────────

hexagon = C3 | neg_C3
assert hexagon == {1, 10, 11, 26, 27, 36}

# Verify this equals the cyclic subgroup generated by 27
C6_gen = set()
curr = 1
for _ in range(6):
    C6_gen.add(curr)
    curr = (curr * 27) % P
assert C6_gen == hexagon

# Order of 27
ord27 = next(k for k in range(1, P) if pow(27, k, P) == 1)
assert ord27 == 6

assert pow(27, 2, P) == 26
assert pow(27, 3, P) == P - 1   # 27³ ≡ −1  ← projective half-turn
assert pow(27, 6, P) == 1


# ── 5. Two-face identity: 10³≡1 and 27³≡−1 ────────────────────────────────────

# These are the "two faces":
assert pow(10, 3, P) ==  1       # generates repeating decimal (period = ord_37(10))
assert pow(27, 3, P) == P - 1   # lifts to projective symmetry (half-period)

# Connection: 27 = 10^k for some k (both live in F_37×, which is cyclic)
# Find k such that 10^k ≡ 27 (mod 37) — the discrete log of 27 base 10 requires
# a generator; use primitive root 2 as bridge.
# ord(2) in F_37×: check
ord2 = next(k for k in range(1, P) if pow(2, k, P) == 1)
assert ord2 == 36    # 2 is a primitive root of F_37

# Discrete logs base 2:
dlog = {pow(2, k, P): k for k in range(36)}
assert dlog[10] % 3 == 0    # 10 has order 3  ⟹  dlog(10) divisible by 12 (36/3)
assert dlog[27] % 6 == 0    # 27 has order 6  ⟹  dlog(27) divisible by 6  (36/6)

# 27 ≡ −10 (mod 37):
assert (27 + 10) % P == 0        # 27 = −10 ✓


# ── 6. Decimal period = ord_37(10) = 3 ────────────────────────────────────────

from decimal import Decimal, getcontext
getcontext().prec = 60

s = str(Decimal(1) / Decimal(37))[2:]   # digits after "0."
# Extract period: first 9 digits should be 027027027
assert s[:9] == "027027027"
assert s[:3] == "027"


# ── 7. Quotient C6 / {±1} ≅ C3 ───────────────────────────────────────────────

# {±1} = {1, 36} is the unique subgroup of order 2 in C6
assert {1, P-1}.issubset(hexagon)

# The three cosets of {1,36} in C6:
cosets = []
seen = set()
for x in sorted(hexagon):
    coset = frozenset({x, (-x) % P}) & hexagon
    if coset not in seen:
        cosets.append(sorted(coset))
        seen.add(coset)
assert len(cosets) == 3
assert sorted(tuple(c) for c in cosets) == sorted([(1,36),(10,27),(11,26)])

# Squaring map: each coset maps to a single element of C3
sq_map = {frozenset({a, (-a)%P}): (a**2) % P for a in hexagon}
sq_images = sorted(set(sq_map.values()))
assert sq_images == sorted(C3)


# ── Report ────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("F_37× Hexagonal Decomposition Audit")
    print()
    print(f"  |F_37×| = {P-1}  (cyclic, primitive root: 2, ord(2)={ord2})")
    print()
    print("  Two faces:")
    print(f"    10³ ≡  1 (mod 37)  ord(10) = {ord10}  → decimal period = 3")
    print(f"    27³ ≡ −1 (mod 37)  ord(27) = {ord27}  → projective half-turn")
    print(f"    27 ≡ −10 (mod 37)  ✓")
    print()
    print(f"  C3 = ⟨10⟩ = {sorted(C3)}")
    print(f"  −C3       = {sorted(neg_C3)}")
    print(f"  C3 ∪ −C3  = {sorted(hexagon)} = ⟨27⟩ = C6  ✓")
    print(f"  C3 ∩ −C3  = ∅  ✓  (−1 ∉ C3)")
    print()
    print(f"  Unique order-3 subgroup: {sorted(all_order3)}  ✓")
    print(f"  1/37 = 0.{s[:9]}...  period={s[:3]}  ✓")
    print()
    print("  C6 / {{±1}} cosets → C3 via x↦x²:")
    for coset, sq in sq_map.items():
        print(f"    {sorted(coset)}  →  {sq}")
    print(f"  Images = {sq_images} = C3  ✓")
    print()
    print("All assertions passed.")
