# math/theorems/mirror_table_mod37_audit.py
"""
Mirror Table Audit — Subgroup ⟨27⟩ ⊂ ℤ/37ℤ and ABAB ≡ T (mod 37)
====================================================================

The subgroup generated by 27 in (ℤ/37ℤ)×:
    ⟨27⟩ = {1, 27, 26, 36, 10, 11}   (order 6)

For each T in ⟨27⟩, the base AB satisfies  AB ≡ 11·T (mod 37),
because  ABAB = AB × 101  and  101 ≡ 27 (mod 37),  so
    ABAB ≡ T (mod 37)  ⟺  AB × 27 ≡ T (mod 37)
                        ⟺  AB ≡ T × 27⁻¹ ≡ T × 11 (mod 37)
    [since 27 × 11 = 297 = 8×37 + 1 ≡ 1 (mod 37)]

Valid 2-digit AB pairs: all ab ∈ [10,99] with ab×101 ≡ T (mod 37).
These come in runs separated by 37: base, base+37, base+74 (if ≤ 99).

Doubling map on fraction values:
    T × inv_denom × 2 ≡ T × 36 ≡ −T (mod 37)
so the doubled-fraction column is exactly negation — pairing the
subgroup elements as antipodal pairs: {1,36}, {27,10}, {26,11}.

inv_denom = 18:  12800 ≡ −2 (mod 37);  (−2)⁻¹ ≡ 18 (mod 37).
"""

import json

P         = 37
INV_DENOM = 18   # (−2)⁻¹ mod 37


# ── Verify inverse of 27 is 11 ────────────────────────────────────────────────

assert (27 * 11) % P == 1,  "FAIL: 11 is not 27⁻¹ mod 37"
assert 101 % P == 27,       "FAIL: 101 not ≡ 27 mod 37"
assert (INV_DENOM * (-2)) % P == 1, "FAIL: 18 is not (−2)⁻¹ mod 37"


# ── Subgroup generation ───────────────────────────────────────────────────────

TARGET_SUBGROUP = [1, 27, 26, 36, 10, 11]

gen = []
curr = 1
for _ in range(6):
    gen.append(curr)
    curr = (curr * 27) % P

assert gen == TARGET_SUBGROUP, f"FAIL: subgroup mismatch: {gen}"


# ── Mirror table ──────────────────────────────────────────────────────────────

ROWS = [
    {"T": 1,  "AB_base": 11, "Valid_AB": [11, 48, 85]},
    {"T": 27, "AB_base": 1,  "Valid_AB": [38, 75]},
    {"T": 26, "AB_base": 27, "Valid_AB": [27, 64]},
    {"T": 36, "AB_base": 26, "Valid_AB": [26, 63]},
    {"T": 10, "AB_base": 36, "Valid_AB": [36, 73]},
    {"T": 11, "AB_base": 10, "Valid_AB": [10, 47, 84]},
]

audited = []
total_pairs = 0

for row in ROWS:
    T = row["T"]

    calc_base = (11 * T) % P
    assert calc_base == row["AB_base"], \
        f"FAIL: base mismatch for T={T}: expected {row['AB_base']}, got {calc_base}"

    pairs = [ab for ab in range(10, 100) if (ab * 101) % P == T]
    assert pairs == row["Valid_AB"], \
        f"FAIL: pairs mismatch for T={T}: expected {row['Valid_AB']}, got {pairs}"

    total_pairs += len(pairs)
    frac_val    = (T * INV_DENOM) % P
    doubled     = (frac_val * 2) % P

    # doubled ≡ T × 18 × 2 = T × 36 ≡ −T (mod 37)
    assert doubled == (-T) % P, \
        f"FAIL: doubled ≠ −T for T={T}: {doubled} ≠ {(-T)%P}"

    audited.append({
        "T": T, "base_AB": calc_base, "valid_AB": pairs,
        "fraction_mod37": frac_val, "doubled_mod37": doubled,
        "antipodal_partner": (-T) % P,
    })

assert total_pairs == 14   # 3+2+2+2+2+3

# ── Antipodal pairs of the subgroup ──────────────────────────────────────────
# Doubling = negation ⟹ pairs {T, −T mod 37} within ⟨27⟩

antipodal_pairs = {(min(T, (-T)%P), max(T, (-T)%P))
                   for T in TARGET_SUBGROUP}
assert antipodal_pairs == {(1, 36), (10, 27), (11, 26)}, \
    f"FAIL: unexpected antipodal pairs: {antipodal_pairs}"


# ── Report ────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Mirror Table Audit — ⟨27⟩ ⊂ ℤ/37ℤ")
    print()
    print(f"  101 ≡ {101%P} (mod 37)   [ABAB = AB×101]")
    print(f"  27⁻¹ ≡ 11 (mod 37)  [11×27=297=8×37+1]")
    print(f"  Subgroup ⟨27⟩: {gen}  ✓")
    print()
    print(f"  {'T':>3}  {'base':>5}  {'valid AB pairs':<18}  {'frac×18':>7}  {'×2=−T':>6}")
    for r in audited:
        print(f"  {r['T']:>3}  {r['base_AB']:>5}  {str(r['valid_AB']):<18}  "
              f"{r['fraction_mod37']:>7}  {r['doubled_mod37']:>6}")
    print()
    print(f"  Total valid 2-digit AB pairs: {total_pairs}")
    print(f"  Antipodal pairs {{T,−T}}: {sorted(antipodal_pairs)}")
    print(f"    — doubling map = negation on ⟨27⟩")
    print(f"    — mirrors the Hopf antipodal structure (v,−v same fiber)")
    print()
    print("All assertions passed.")
