# -*- coding: utf-8 -*-
"""
================================================================================
⟨11⟩ — THE ORDER-6 SUBGROUP OF GF(37)*
================================================================================

Author: Michael Warren Song (CyclicAmp)

THEOREM [P/V]:
  The element 11 ∈ GF(37)* has order 6.
  The cyclic subgroup ⟨11⟩ = IC ∪ NEG_H = {1, 10, 11, 26, 27, 36}.

  This is the unique subgroup of order 6 in GF(37)* (which is cyclic of order 36).

POWER SEQUENCE:
  11¹ mod 37 = 11  ∈ NEG_H
  11² mod 37 = 10  ∈ IC       ← the 137-map orbit generator
  11³ mod 37 = 36  ∈ NEG_H   ← −1 mod 37
  11⁴ mod 37 = 26  ∈ IC       ← the 137-map multiplier (137 mod 37 = 26)
  11⁵ mod 37 = 27  ∈ NEG_H
  11⁶ mod 37 =  1  ∈ IC       ← identity (closes the cycle)

SUBGROUP STRUCTURE ⟨11⟩ ≅ ℤ₆:
  ⟨11⟩ is cyclic of order 6 = 2 × 3.
  Two normal subgroups:
    Index-3 subgroup ⟨11²⟩ = ⟨36⟩ = {1, 36} ≅ ℤ₂   (generated by −1)
    Index-2 subgroup ⟨11²⟩ = ⟨10⟩  = {1, 10, 26} = IC ≅ ℤ₃

  IC = ⟨11²⟩: the order-3 subgroup (cube roots of 1 mod 37).
  NEG_H = 11 · IC = {11·1, 11·10, 11·26} mod 37 = {11, 36, 27}: the non-identity coset.

  Thus ⟨11⟩ = IC ∪ NEG_H, where:
    IC  = cube roots of +1 mod 37 = {1, 10, 26}
    NEG_H = cube roots of −1 mod 37 = {11, 27, 36}

137-MAP CONNECTION [V]:
  The 137-map multiplier is 26 = 11⁴ mod 37.
  The 137-map orbit ⟨26⟩ = {26, 10, 1} = IC = ⟨11²⟩.
  The 137-map is the square of 11 acting on GF(37)*.

  Therefore: ⟨11⟩ is the natural ambient subgroup for the 137-map.
  The 137-map lives inside ⟨11⟩ as its index-2 subgroup.

QR STRUCTURE [V]:
  All six elements of ⟨11⟩ are quadratic residues mod 37:
  ⟨11⟩ ⊆ QR.
  This is consistent with the QR-homogeneity theorem:
  IC and NEG_H are both ALL QR named sets.

  Note: 11 being QR means ⟨11⟩ ⊆ QR — a generator that is QR generates
  only QR elements (QR is closed under multiplication).

EPISTEMIC STATUS:
  [P] ord₃₇(11) = 6 — verified by direct computation; follows from group theory.
  [P] ⟨11⟩ = IC ∪ NEG_H — exact.
  [P] 26 = 11⁴ mod 37 — exact.
  [P] IC = ⟨11²⟩ — exact.
  [P] NEG_H = 11 · IC — exact.
  [V] All elements of ⟨11⟩ are QR — verified.
  [V] ⟨11⟩ is closed under multiplication — verified.
================================================================================
"""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

P = 37
IC    = {1, 10, 26}
NEG_H = {11, 27, 36}


def run():
    print("=" * 70)
    print("⟨11⟩ — THE ORDER-6 SUBGROUP OF GF(37)*")
    print("=" * 70)

    # Power sequence
    print(f"\nPower sequence of 11 mod 37:")
    orbit = []
    x = 11
    for k in range(1, P):
        label = 'IC' if x in IC else ('NEG_H' if x in NEG_H else '')
        orbit.append((k, x))
        print(f"  11^{k} mod 37 = {x:2d}  [{label}]")
        if x == 1 and k > 1:
            break
        x = x * 11 % P

    order = orbit[-1][0]
    subgroup = {v for _, v in orbit}
    assert order == 6
    assert subgroup == IC | NEG_H
    print(f"\nord₃₇(11) = {order}  check")
    print(f"⟨11⟩ = {sorted(subgroup)}")
    print(f"IC ∪ NEG_H = {sorted(IC | NEG_H)}")
    print(f"⟨11⟩ = IC ∪ NEG_H  check")

    # Closure
    violations = [(a, b, a*b%P) for a in subgroup for b in subgroup
                  if a*b % P not in subgroup]
    assert len(violations) == 0
    print(f"Closed under multiplication: True  check")

    # QR structure
    QR = {pow(x, 2, P) for x in range(1, P)}
    assert subgroup <= QR
    print(f"All elements of ⟨11⟩ are QR  check")

    # Subgroup structure
    print(f"\nSubgroup structure ⟨11⟩ ≅ ℤ₆:")
    assert IC == {pow(11, k, P) for k in [2, 4, 6]}
    assert NEG_H == {pow(11, k, P) for k in [1, 3, 5]}
    print(f"  Index-2 subgroup IC = ⟨11²⟩ = {{1,10,26}} ≅ ℤ₃  check")
    print(f"  {P-1} = −1 mod 37: −1 = 11³ ∈ NEG_H  check")
    assert pow(11, 3, P) == P - 1 and P - 1 in NEG_H

    # NEG_H = 11 * IC
    coset = {11 * x % P for x in IC}
    assert coset == NEG_H
    print(f"  NEG_H = 11 · IC = {sorted(coset)}  check")

    # 137-map connection
    assert pow(11, 4, P) == 26
    assert {pow(26, k, P) for k in range(1, 4)} == IC
    print(f"\n137-map connection:")
    print(f"  137-map multiplier 26 = 11⁴ mod 37  check")
    print(f"  137-map orbit ⟨26⟩ = IC = ⟨11²⟩  check")
    print(f"  The 137-map is the square of 11 acting on GF(37)*  check")

    print(f"\nAll verifications passed.")


if __name__ == "__main__":
    run()
