# -*- coding: utf-8 -*-
"""
================================================================================
PRIME STREAMS — (Z/9Z)* AND GF(37) STRUCTURE
================================================================================

Author: Michael Warren Song (CyclicAmp)

================================================================================
THE 6 PRIME STREAMS = (Z/9Z)* [P]
================================================================================

The 6 columns hosting all primes > 3 are exactly the units of Z/9Z:
    (Z/9Z)* = {1, 2, 4, 5, 7, 8}

This is the F spectral class of the DR transition matrix — the eigenspace
with eigenvalues that are 6th roots of unity. The excluded channels
{3, 6, 9} = O∪S class cannot host primes > 3 (divisible by 3).

CYCLIC GROUP STRUCTURE:
  (Z/9Z)* is cyclic of order 6, generated by 2:
    2^0 mod 9 = 1  (Stream 1, identity)
    2^1 mod 9 = 2  (Stream 2)
    2^2 mod 9 = 4  (Stream 4)
    2^3 mod 9 = 8  (Stream 8)
    2^4 mod 9 = 7  (Stream 7)
    2^5 mod 9 = 5  (Stream 5)

The same element 2 generates GF(37)* with ord₃₇(2)=36=6².
DR arithmetic is GF(37) structure projected onto Z/9Z via the DR map.

================================================================================
TWO DISTINCT STREAM STRUCTURES [P]
================================================================================

HARMONIC MIRRORS (additive complements, sum=9):
  Stream 1 ↔ Stream 8  (1+8=9)  QR ↔ QNR  upper twin(m≡0) ↔ lower twin(m≡0)
  Stream 2 ↔ Stream 7  (2+7=9)  QNR ↔ QR  lower twin(m≡2) ↔ upper twin(m≡1)
  Stream 4 ↔ Stream 5  (4+5=9)  QR ↔ QNR  upper twin(m≡2) ↔ lower twin(m≡1)

  Each mirror pair contains one QNR DR (lower twin class) and one QR DR
  (upper twin class) — the twin prime QR/QNR split expressed as additive
  complements to 9. Pair (1,8) is within one m-class (m≡0). Pairs (2,7)
  and (4,5) each cross m-classes: one element from m≡2, one from m≡1.

MAGNETIC CROSS-CURRENTS (multiplicative inverses mod 9):
  2 × 5 = 10 ≡ 1 mod 9  →  Stream 1  (2 and 5 are inverses)
  4 × 7 = 28 ≡ 1 mod 9  →  Stream 1  (4 and 7 are inverses)
  8 × 8 = 64 ≡ 1 mod 9  →  Stream 1  (8 is self-inverse)
  1 × 1 =  1 ≡ 1 mod 9  →  Stream 1  (1 is identity)

  Inverse collisions collapse to Stream 1 (the identity DR).
  These are group-law collisions, not coincidences.

GF(37) NAMED SET ASSIGNMENTS BY STREAM:
  Stream 1: residues {1,10,19,28} mod 37 → IC={1,10}, critical line 19
  Stream 2: residues {2,11,20,29} mod 37 → NEG_H={11}
  Stream 4: residues {4,13,22,31} mod 37 → SA={4}, CASCADE={13}
  Stream 5: residues {5,14,23,32} mod 37 → TESLA={23}, SEED={32}
  Stream 7: residues {7,16,25,34} mod 37 → SA={25}, D7={34}
  Stream 8: residues {8,17,26,35} mod 37 → CASCADE={8}, IC={26}, NQR_17={17,35}

  Stream 8 (lower twin, QNR) contains IC element 26 — the 137-map multiplier.
  Stream 4 (upper twin, QR) contains CASCADE element 13.
  The named sets cross-pollinate across the QR/QNR divide.

================================================================================
THE 55+2 DELTA: SEED → WALL → NQR_17 [V]
================================================================================

  55 mod 37 = 18 ∈ SEED = {18,24,32}   DR=1 (Stream 1, prime 55? No: 55=5×11)
  57 mod 37 = 20 ∈ DARK_A = {2,15,20}  DR=3 (O-class wall, 57=3×19, composite)
  59 mod 37 = 22 ∈ NQR_17 = {17,22,35} DR=5 (Stream 5, 59 is prime)

  Path: SEED → DARK_A(wall, DR=3 dead zone) → NQR_17 (prime restored)
  The system bounces off the O-class wall and lands the next prime in NQR_17.

================================================================================
PRIME 37 AND 137 IN THE GRID [V]
================================================================================

  37:  DR(37) = 1  → Stream 1.  37 mod 37 = 0  → SEAM.
       The prime that IS the modulus lives in Stream 1 as the SEAM itself.

  137: DR(137) = 2  → Stream 2.  137 mod 37 = 26 ∈ IC.
       A lower-twin-class prime (Stream 2, QNR) whose GF(37) residue is
       the 137-map multiplier (IC, QR). 137 bridges the QNR column to the
       IC identity cycle.

EPISTEMIC STATUS:
  [P] F-class = (Z/9Z)* — proved: DR∈{1,2,4,5,7,8} iff gcd(n,9)=1 — exact.
  [P] (Z/9Z)* cyclic order 6, generator 2 — standard group theory.
  [P] ord₃₇(2)=36=6² — verified.
  [P] Mirror pairs = twin prime QR/QNR pairs — proved from DR congruences.
  [P] Cross-currents = multiplicative inverses in (Z/9Z)* — group law.
  [V] Stream residues mod 37 hitting named sets — exact.
  [V] 55+2 delta: SEED→DARK_A→NQR_17 — exact.
  [V] DR(37)=1, 37 mod 37=0; DR(137)=2, 137 mod 37=26∈IC — exact.
================================================================================
"""

P = 37
SEED    = {18, 24, 32}
SA      = {4, 9, 25, 30}
ST      = {3, 12, 21, 30}
IC      = {1, 10, 26}
NEG_H   = {11, 27, 36}
CASCADE = {8, 13, 24}
DARK_A  = {2, 15, 20}
D7      = {7, 33, 34}
TESLA   = {6, 8, 23}
NQR_17  = {17, 22, 35}
named   = SEED | SA | ST | IC | NEG_H | CASCADE | DARK_A | D7 | TESLA | NQR_17

F_CLASS = {1, 2, 4, 5, 7, 8}
O_CLASS = {3, 6}
S_CLASS = {9}


def dr(n):
    n = abs(n)
    if n == 0: return 0
    r = n % 9
    return 9 if r == 0 else r


def orbit_label(r):
    if r == 0: return 'SEAM'
    cats = []
    if r in IC:      cats.append('IC')
    if r in SA:      cats.append('SA')
    if r in ST:      cats.append('ST')
    if r in SEED:    cats.append('SEED')
    if r in NEG_H:   cats.append('NEG_H')
    if r in CASCADE: cats.append('CASCADE')
    if r in DARK_A:  cats.append('DARK_A')
    if r in D7:      cats.append('D7')
    if r in TESLA:   cats.append('TESLA')
    if r in NQR_17:  cats.append('NQR_17')
    return ','.join(cats) if cats else '-'


def run():
    print("=" * 70)
    print("PRIME STREAMS — (Z/9Z)* AND GF(37) STRUCTURE")
    print("=" * 70)

    # (Z/9Z)* = F-class, cyclic order 6, generator 2
    z9_units = {n for n in range(1, 10) if __import__('math').gcd(n, 9) == 1}
    assert z9_units == F_CLASS
    print(f"\n(Z/9Z)* = {sorted(z9_units)} = F-class  check")

    gen_cycle = []
    x = 1
    for _ in range(6):
        gen_cycle.append(x)
        x = (x * 2) % 9 or 9
    assert set(gen_cycle) == F_CLASS
    print(f"Generator 2 cycle: {gen_cycle}  check")

    assert pow(2, 36, P) == 1 and pow(2, 18, P) != 1
    print(f"ord₃₇(2)=36=6²  check")

    # Harmonic mirrors (sum=9)
    print(f"\nHarmonic mirrors (sum=9):")
    for a, b in [(1,8),(2,7),(4,5)]:
        assert a + b == 9
        print(f"  Stream {a} + Stream {b} = 9  check")

    # Cross-currents (inverses mod 9)
    print(f"\nMagnetic cross-currents (multiplicative inverses mod 9):")
    for a, b in [(2,5),(4,7),(8,8),(1,1)]:
        assert (a * b) % 9 == 1
        print(f"  {a} × {b} = {a*b} ≡ 1 mod 9  check")

    # Stream residues mod 37
    print(f"\nGF(37) residues by stream:")
    for d in sorted(F_CLASS):
        residues = [r for r in range(1, P) if dr(r) == d]
        labels = [orbit_label(r) for r in residues]
        named_hits = [(r, l) for r, l in zip(residues, labels) if l != '-']
        print(f"  Stream {d}: residues {residues} → named: {named_hits}")

    # 55+2 delta
    print(f"\n55+2 delta:")
    for n, label in [(55,'55'),(57,'57=3×19 WALL'),(59,'59 prime')]:
        r = n % P
        print(f"  {label}: mod37={r} [{orbit_label(r)}] DR={dr(n)}")
    assert 55 % P == 18 and 18 in SEED
    assert 57 % P == 20 and 20 in DARK_A and dr(57) == 3
    assert 59 % P == 22 and 22 in NQR_17
    print(f"  SEED → DARK_A(wall, DR=3) → NQR_17  check")

    # 37 and 137
    print(f"\nPrimes 37 and 137 in the grid:")
    assert dr(37) == 1 and 37 % P == 0
    assert dr(137) == 2 and 137 % P == 26 and 26 in IC
    print(f"  37:  DR=1 (Stream 1), 37 mod 37=0 → SEAM  check")
    print(f"  137: DR=2 (Stream 2), 137 mod 37=26 ∈ IC (137-map multiplier)  check")

    print(f"\nAll assertions passed.")


if __name__ == "__main__":
    run()
