"""
primorial_mirror_audit.py

Audits "Symmetrical Folding of Twin Primes" around P₃# = 30.

Claims:
  1. 30±1, 30±11, 30±13 produce three twin prime pairs
  2. The three pairs populate all three DR tracks
  3. Twin prime centers always divisible by 6 (P₂#)
  4. Centers 18, 30, 42 have gap 12 in both directions
  5. "The geometry scales indefinitely"
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'primes'))
from prime_engine import is_prime, digital_root, _GRID_LABEL

# ---------------------------------------------------------------------------
# 1.  Arithmetic verification: 30±1, 30±11, 30±13
# ---------------------------------------------------------------------------
print("="*62)
print("1.  Arithmetic: P₃# = 30 fold")
print("="*62)

axis = 30
# Three twin pairs generated by folding around 30:
#   (30-1, 30+1) = (29, 31)     center=30
#   (30-13, 30-11) = (17, 19)   center=18
#   (30+11, 30+13) = (41, 43)   center=42
raw_pairs = [(29, 31), (17, 19), (41, 43)]

pairs = []
for p, q in raw_pairs:
    dr_p = digital_root(p)
    dr_q = digital_root(q)
    is_twin = is_prime(p) and is_prime(q) and (q - p == 2)
    center = (p + q) // 2
    pairs.append((p, q, dr_p, dr_q, is_twin, center))
    print(f"  ({p}, {q}):  prime({p})={is_prime(p)}  prime({q})={is_prime(q)}  "
          f"gap={q-p}  twin={is_twin}  DR=({dr_p},{dr_q})  center={center}")

print(f"\n  All three twin pairs confirmed: {all(p[4] for p in pairs)}")

# ---------------------------------------------------------------------------
# 2.  All three DR tracks populated
# ---------------------------------------------------------------------------
print()
print("="*62)
print("2.  DR tracks populated by the fold")
print("="*62)

dr_tracks = {(dr_p, dr_q) for p, q, dr_p, dr_q, twin, center in pairs if twin}
expected  = {(2,4), (8,1), (5,7)}
print(f"  Observed DR pairs: {sorted(dr_tracks)}")
print(f"  Expected:          {sorted(expected)}")
print(f"  All three tracks:  {dr_tracks == expected}")
print(f"""
  CLAIM STATUS: CORRECT for P₃#=30.
  One fold around 30 produces pairs in all three valid DR tracks.
  This is an arithmetic fact about this specific primorial.
""")

# ---------------------------------------------------------------------------
# 3.  Twin prime centers always divisible by 6
# ---------------------------------------------------------------------------
print("="*62)
print("3.  Twin prime centers always divisible by 6")
print("="*62)
print("""
  THEOREM: For any twin prime pair (p, p+2) with p > 3,
           the center (p+1) is divisible by 6.

  PROOF:
    p > 3 prime → p ≡ 1 or 5 (mod 6).
    If p ≡ 1 (mod 6): p+2 ≡ 3 (mod 6) → 3|(p+2) → p+2 composite. ✗
    So p ≡ 5 (mod 6) ≡ -1 (mod 6).
    Then p+1 ≡ 0 (mod 6). ∎

  Center = p+1 is always a multiple of 6.
""")

# Verify empirically
from prime_engine import twin_prime_generator
violations = []
for p, p2, *_ in twin_prime_generator(5):
    if p > 100000:
        break
    center = p + 1
    if center % 6 != 0:
        violations.append((p, p2, center))
print(f"  Violations (p>3, p≤100,000): {len(violations)}  (expected 0)")
print(f"  Theorem confirmed: every twin prime center is divisible by 6 ✓")

# ---------------------------------------------------------------------------
# 4.  Centers: 18, 30, 42, gap = 12
# ---------------------------------------------------------------------------
print()
print("="*62)
print("4.  Centers 18, 30, 42 — gap = 12")
print("="*62)

centers = [c for p, q, dr_p, dr_q, twin, c in pairs if twin]
centers.sort()
print(f"  Centers: {centers}")
gaps = [centers[i+1] - centers[i] for i in range(len(centers)-1)]
print(f"  Gaps between centers: {gaps}")
print(f"  All gaps = 12: {all(g == 12 for g in gaps)}")
print(f"  12 = 2 × 6 = 2 × P₂#  →  symmetric around the axis ✓")

# ---------------------------------------------------------------------------
# 5.  "Scales indefinitely": test axes 18, 30, 42, 54, 66, ...
# ---------------------------------------------------------------------------
print()
print("="*62)
print("5.  'Scales indefinitely': test ±1 fold at axis ± 12k")
print("="*62)
print("""
  CLAIM: "The geometry scales indefinitely."
  TEST: Apply the ±1 fold (axis±1 = twin pair) at every center
        in the sequence 18, 30, 42, 54, 66, 78, 90, ... (step 12).
""")

print(f"  {'axis':>6}  {'axis-1':>8}  {'axis+1':>8}  "
      f"{'both prime':>11}  {'twin pair':>10}")
print(f"  {'-'*50}")
scale_works = 0
scale_fails = 0
for k in range(20):
    a = 18 + 12 * k
    lo, hi = a - 1, a + 1
    both = is_prime(lo) and is_prime(hi)
    twin = both and (hi - lo == 2)
    mark = "✓" if twin else "✗"
    print(f"  {a:>6}  {lo:>8}  {hi:>8}  {str(both):>11}  {str(twin):>10}  {mark}")
    if twin:
        scale_works += 1
    else:
        scale_fails += 1

print(f"""
  Result: {scale_works} axes produce twin pairs, {scale_fails} do not.
  The ±1 fold fails at the first counter-example (axis=54: 53✓, 55=5×11✗).

  CLAIM STATUS: FALSE as stated.
  "Scales indefinitely" is not established.
  The three specific pairs (18,30,42) form a cluster around P₃#=30.
  The sequence 18, 30, 42, 54, 66, ... does NOT produce twin pairs
  at every step.

  WHAT IS TRUE:
    Twin prime centers are dense near primorials (by construction:
    primorials are divisible by all small primes, so primorial±k is
    coprime to small primes for many k values).
    But density ≠ every step producing a twin prime.
""")

# ---------------------------------------------------------------------------
# 6.  Test the fold at other primorials: P₄# = 210
# ---------------------------------------------------------------------------
print("="*62)
print("6.  Does the fold work at P₄# = 210?")
print("="*62)

axis2 = 210
print(f"  P₄# = {axis2} = 2×3×5×7")
print(f"  ±1 fold: ({axis2-1}, {axis2+1})")
print(f"    {axis2-1} prime: {is_prime(axis2-1)}")
print(f"    {axis2+1} prime: {is_prime(axis2+1)}")
twin_210 = is_prime(axis2-1) and is_prime(axis2+1)
print(f"    Twin pair (209,211): {twin_210}")
print(f"    Note: 209 = 11 × 19  →  NOT prime")
print(f"""
  P₄# = 210 does NOT produce a twin prime via ±1 fold.
  The fold is not a general primorial property — it's specific to P₃#=30
  (and to any twin prime center, trivially: every twin prime center (p+1)
  produces a twin pair by the ±1 fold by definition).
""")

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
print("="*62)
print("SUMMARY")
print("="*62)
print("""
  Claim                                        Status
  ----------------------------------------------------------
  P₃# = 30 is a twin prime center              CORRECT ✓
  30±1, 30±11, 30±13 → three twin pairs        CORRECT ✓  (verified)
  Three pairs cover all DR tracks (2,4)(5,7)(8,1)  CORRECT ✓
  Twin prime centers always divisible by 6     PROVEN ✓
  Centers 18, 30, 42 with gap 12               CORRECT ✓
  "Scales indefinitely" at step 12             FALSE ✗
    Counter-example: axis=54 → 53✓ but 55=5×11
  Fold works at all primorials                 FALSE ✗
    Counter-example: P₄#=210 → 209=11×19 not prime

  WHAT IS GENUINELY ESTABLISHED:
    P₃#=30 is a structural sweet spot: it is a twin prime center
    AND equidistant from two other twin prime pairs whose centers
    are multiples of 6. The three pairs collectively cover all three
    DR tracks. This is a real, verifiable property of P₃#=30.

  WHAT IS NOT ESTABLISHED:
    A general "scaling" principle. The cluster (17,19),(29,31),(41,43)
    is a prime constellation — a specific pattern of primes close together.
    Prime constellations are studied in the k-tuple conjecture;
    this one is {-13,-11,-1,+1,+11,+13} relative to 30.
    Its existence is a fact. Its indefinite repetition is not proven.
""")
