"""
scalar_triad_137_248_359.py

137, 248, 359 all satisfy n ≡ 26 (mod 37).

Structural reason: they form an arithmetic progression with step 111 = 3×37.
  248 - 137 = 111 = 3 × 37
  359 - 248 = 111 = 3 × 37

The residue 26 = 137 mod 37 = 10² mod 37 generates the unique cyclic
subgroup of order 3 in (Z/37Z)×:   ⟨26⟩ = {1, 10, 26}

This is the same subgroup generated by 10 (since ord₃₇(10)=3):
  10¹ ≡ 10,   10² ≡ 26,   10³ ≡ 1   (mod 37)
  26¹ ≡ 26,   26² ≡ 10,   26³ ≡ 1   (mod 37)

10 and 26 are inverse generators of the same order-3 subgroup.

Also verified in this file:
  - Primes with digit sum 13 and digital root 4: {751, 157, 571, 373}
  - 142857 × (any of those primes) → digit sum 36, digital root 9
  - 103/137 ≡ 31 (mod 37)  — 31 is in the 3-cycle {14, 31, 29}
  - 9999 ≡ 9 (mod 37);  1111 ≡ 1 (mod 37)
  - lcm(37,7,23,19) = 113183  (≡ 0 mod each simultaneously)
"""

from sympy import isprime, factorint
from math import lcm

def dr(n): return 0 if n == 0 else 1 + (n - 1) % 9
def ds(n): return sum(int(d) for d in str(n))


# ──────────────────────────────────────────────────────────────────────────────
# THE TRIAD: 137, 248, 359 ≡ 26 (mod 37)
# ──────────────────────────────────────────────────────────────────────────────

TRIAD = [137, 248, 359]
for n in TRIAD:
    assert n % 37 == 26

# Arithmetic structure: step = 111 = 3 × 37
assert 248 - 137 == 111
assert 359 - 248 == 111
assert 111 == 3 * 37

# Any element 137 + k×111 shares the same residue mod 37
for k in range(10):
    assert (137 + k * 111) % 37 == 26


# ──────────────────────────────────────────────────────────────────────────────
# ORDER-3 SUBGROUP OF (Z/37Z)×
# ──────────────────────────────────────────────────────────────────────────────

# (Z/37Z)× is cyclic of order φ(37)=36.
# The unique subgroup of order 3 is generated by any element of order 3.

# 10 generates it (since ord₃₇(10)=3):
assert pow(10, 1, 37) == 10
assert pow(10, 2, 37) == 26
assert pow(10, 3, 37) == 1

# 26 also generates it (inverse generator):
assert pow(26, 1, 37) == 26
assert pow(26, 2, 37) == 10   # 26×26=676=18×37+10
assert pow(26, 3, 37) == 1

ORDER_3_SUBGROUP = {1, 10, 26}
assert {pow(10, k, 37) for k in range(3)} == ORDER_3_SUBGROUP
assert {pow(26, k, 37) for k in range(3)} == ORDER_3_SUBGROUP

# Every element of the triad reduces to the generator 26:
for n in TRIAD:
    assert n % 37 == 26
    assert 26 in ORDER_3_SUBGROUP

# 26⁻¹ mod 37 = 10  (since 26×10=260=7×37+1)
assert pow(26, -1, 37) == 10
assert (26 * 10) % 37 == 1


# ──────────────────────────────────────────────────────────────────────────────
# PRIMES WITH DIGIT SUM 13, DIGITAL ROOT 4: {751, 157, 571, 373}
# ──────────────────────────────────────────────────────────────────────────────

DS13_PRIMES = [751, 157, 571, 373]

for p in DS13_PRIMES:
    assert isprime(p)
    assert ds(p) == 13
    assert dr(p) == 4

# Distinct mod-37 residues
residues_37 = [p % 37 for p in DS13_PRIMES]
assert residues_37 == [11, 9, 16, 3]
assert len(set(residues_37)) == 4   # all distinct
assert set(residues_37) & ORDER_3_SUBGROUP == set()   # none in {1, 10, 26}
assert set(residues_37) & {14, 31, 29} == set()       # none in the 3-cycle of 14

# mod-19 residues (all distinct)
residues_19 = [p % 19 for p in DS13_PRIMES]
assert residues_19 == [10, 5, 1, 12]
assert len(set(residues_19)) == 4

residues_7  = [p % 7  for p in DS13_PRIMES];  assert residues_7  == [2, 3, 4, 2]
residues_23 = [p % 23 for p in DS13_PRIMES];  assert residues_23 == [15, 19, 19, 5]


# ──────────────────────────────────────────────────────────────────────────────
# 142857 × (digit-sum-13 prime) → digit sum 36, digital root 9
# ──────────────────────────────────────────────────────────────────────────────

PRODUCTS = {p: 142857 * p for p in DS13_PRIMES}

expected = {
    751: 107285607,
    157: 22428549,
    571: 81571347,
    373: 53285661,
}
assert PRODUCTS == expected

for p, prod in PRODUCTS.items():
    assert ds(prod) == 36   # digit sum = 36
    assert dr(prod) == 9    # digital root = 9

# Reason: dr(142857)=9, dr(p)=4, so dr(product) = dr(9×4) = dr(36) = 9.
# These specific products have digit sum exactly 36 (not 27 or 45).
assert dr(142857) == 9
for p in DS13_PRIMES:
    assert dr(p) == 4
    assert dr(142857 * p) == 9


# ──────────────────────────────────────────────────────────────────────────────
# 103/137 ≡ 31 (mod 37) — 31 is in the 3-cycle {14, 31, 29}
# ──────────────────────────────────────────────────────────────────────────────

# 103 mod 37 = 29,  137 mod 37 = 26
assert 103 % 37 == 29
assert 137 % 37 == 26

# 103/137 mod 37 = 103 × 137⁻¹ mod 37 = 29 × 26⁻¹ mod 37 = 29 × 10 mod 37
assert pow(26, -1, 37) == 10
assert (29 * 10) % 37 == 31
assert (103 * pow(137, -1, 37)) % 37 == 31
assert 31 in {14, 31, 29}


# ──────────────────────────────────────────────────────────────────────────────
# 9999 STRUCTURE: 9999 ≡ 9 (mod 37), 1111 ≡ 1 (mod 37)
# ──────────────────────────────────────────────────────────────────────────────

assert factorint(9999) == {3: 2, 11: 1, 101: 1}
assert factorint(1111) == {11: 1, 101: 1}
assert 9 * 1111 == 9999

assert 1111 % 37 == 1
assert 9999 % 37 == 9     # = 9 × 1 ≡ 9 (mod 37)

assert (7518 + 2481) % 37 == 9   # split-complement sum ≡ 9 (mod 37)


# ──────────────────────────────────────────────────────────────────────────────
# lcm(37, 7, 23, 19) = 113183
# ──────────────────────────────────────────────────────────────────────────────

L = lcm(37, lcm(7, lcm(23, 19)))
assert L == 113183
assert 37 * 7 * 23 * 19 == 113183   # all prime — LCM equals product

for m in [37, 7, 23, 19]:
    assert L % m == 0


# ──────────────────────────────────────────────────────────────────────────────
# 10-DIGIT SEQUENCE PAIR
# ──────────────────────────────────────────────────────────────────────────────

A10 = 7518248175   # first 10 digits of 103/137 decimal
B10 = 5718428157

assert ds(A10) == 48;  assert dr(A10) == 3
assert ds(B10) == 48;  assert dr(B10) == 3

assert A10 % 37 == 23
assert B10 % 37 == 13
assert B10 % 19 == 0    # B10 divisible by 19

assert ds(A10 + B10) == 42
assert ds(A10 - B10) == 45
assert dr(A10 - B10) == 9


# ──────────────────────────────────────────────────────────────────────────────
# OUTPUT
# ──────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Triad 137/248/359 and the Order-3 Subgroup of (Z/37Z)×")
    print("=" * 66)

    print("\n── TRIAD ──")
    for n in TRIAD:
        print(f"  {n}  mod 37 = {n%37}  (= 26 = 137 mod 37 = 10² mod 37)")
    print(f"  Step: {248-137} = 3 × 37  (arithmetic progression)")

    print("\n── ORDER-3 SUBGROUP ⟨26⟩ = {{1, 10, 26}} ──")
    print(f"  10¹ mod 37 = {pow(10,1,37)},  10² mod 37 = {pow(10,2,37)},  10³ mod 37 = {pow(10,3,37)}")
    print(f"  26¹ mod 37 = {pow(26,1,37)},  26² mod 37 = {pow(26,2,37)},  26³ mod 37 = {pow(26,3,37)}")
    print(f"  10 and 26 are inverse generators;  26⁻¹ mod 37 = {pow(26,-1,37)}")

    print("\n── DIGIT-SUM-13, DIGITAL-ROOT-4 PRIMES ──")
    print(f"  All prime, digit sum=13, digital root=4")
    for p in DS13_PRIMES:
        print(f"  {p}: mod 37={p%37:2d}  mod 19={p%19:2d}  mod 7={p%7}  mod 23={p%23:2d}")
    print(f"  mod-37 residues {residues_37}: all distinct, none in {{1,10,26}} or {{14,31,29}}")

    print("\n── 142857 × (digit-sum-13 prime) ──")
    for p, prod in PRODUCTS.items():
        print(f"  142857 × {p} = {prod}  digit_sum={ds(prod)}  digital_root={dr(prod)}")
    print(f"  digit sum = 36 = 6², digital root = 9 in all cases")

    print("\n── 103/137 ≡ 31 (mod 37) ──")
    print(f"  103 mod 37 = {103%37},  137⁻¹ mod 37 = {pow(137,-1,37)}")
    print(f"  103/137 mod 37 = 29 × 10 = {29*10} ≡ {(29*10)%37}  ∈ {{14,31,29}}")
    print(f"  (3-cycle under x ↦ 26x mod 37: 14→31→29→14)")

    print("\n── 9999 ≡ 9 (mod 37) ──")
    print(f"  9999 = {factorint(9999)}")
    print(f"  1111 mod 37 = {1111%37}  →  9999 = 9×1111 ≡ 9×1 = {9999%37} (mod 37)")

    print("\n── lcm(37,7,23,19) ──")
    print(f"  {L} ≡ 0 mod {{37, 7, 23, 19}} simultaneously")

    print()
    print("All assertions passed.")
