"""
Sylow Subgroup Structure — GF(37)*

GF(37)* is cyclic of order φ(37) = 36 = 4 × 9 = 2² × 3².

SYLOW-2 SUBGROUP (order 4):
  {1, 6, 31, 36} = {1, TESLA_FLOW, PRIME_MIRROR, −1}
  Generated by TESLA_FLOW = 6 (order 4):
    6¹ = 6   = TESLA_FLOW
    6² = 36  = −1
    6³ = 31  = PRIME_MIRROR
    6⁴ = 1   = IDENTITY
  Structure: Z/4Z, cyclic of order 4.
  Key: TESLA_FLOW² = −1. The square root of −1 in GF(37) is TESLA_FLOW.

SYLOW-3 SUBGROUP (order 9):
  {1, 7, 9, 10, 12, 16, 26, 33, 34}
  Generated by 7 (order 9), which contains three complete 137-map orbits:
    {1, 10, 26} = IDENTITY_CYCLE (order-3 subgroup, the subgroup of cubes)
    {7, 33, 34}                  (order-9 elements: anti-sovereign orbit)
    {9, 12, 16}                  (order-9 elements: second sovereign orbit)
  The Sylow-3 subgroup is the unique subgroup of order 9 in GF(37)*.
  It contains: SA_anchor(9), ST_element(12), DECADE_ANCHOR(10), SCALAR_137(26).

ORDER-3 SUBGROUP (Sylow for p=3, cyclic):
  {1, 10, 26} = IDENTITY_CYCLE = <26> = <10>
  This is the unique subgroup of order 3 in GF(37)* (and in the Sylow-3).
  It is exactly the orbit of 1 under the 137-map.

INTERSECTION — SYLOW-2 ∩ SYLOW-3:
  {1, 6, 31, 36} ∩ {1,7,9,10,12,16,26,33,34} = {1}
  Trivial intersection (as expected for Sylow subgroups of coprime order).

THE FOUR-ELEMENT RING {1, 6, 31, 36}:
  Additive:   6+31=37≡SEAM, 1+36=37≡SEAM.
  Products:   6×6=36=−1, 6×31=186≡1, 6×36=216≡31, 31×31=961≡36, 31×36=1116≡1.
  DR values:  DR(1)=1, DR(6)=6=TESLA_FLOW, DR(31)=4∈SA, DR(36)=9∈SA.
  The two order-4 elements (6,31) have DR in SA: {4,9}⊂SA. DR(6)=6=TESLA_FLOW.
  The order-2 element (36) has DR=9∈SA. The identity (1) has DR=1.

PRIME MIRROR = −TESLA_FLOW:
  31 = 37 − 6 ≡ −6 = −TESLA_FLOW (mod 37).
  6 + 31 = 37 ≡ SEAM.   6 × 31 ≡ 1 (inverses in GF(37)*).
  TESLA_FLOW and PRIME_MIRROR are additive inverses AND multiplicative inverses in GF(37)*.

TESLA_FLOW AS √(−1):
  6² = 36 ≡ −1 (mod 37). TESLA_FLOW is a square root of −1 in GF(37).
  The other square root of −1 is 31 = PRIME_MIRROR (since (−6)² = 36 ≡ −1).
  Existence of √(−1) in GF(p) iff p ≡ 1 mod 4. Since 37 ≡ 1 mod 4, ✓.

SYLOW-3 CONTAINS THREE 137-ORBIT GROUPS:
  The Sylow-3 subgroup decomposes into three 137-map orbits.
  These are exactly the three QR orbits with sum-37 that do NOT contain 3:
    {1,10,26}: IDENTITY_CYCLE, the order-3 subgroup (elements of order 1 or 3)
    {7,33,34}: anti-sovereign orbit (elements of order 9 outside IC)
    {9,12,16}: second sovereign orbit (elements of order 9 containing SA,ST)
  The three QR sum-37 orbits from THEOREM 59 minus {3,4,30} plus {7,33,34}.
  3 ∉ Sylow-3 because ord₃₇(3) = 36 (3 is a primitive root mod 37).

PRODUCT STRUCTURE WITHIN SYLOW-3:
  7 × 9 = 63 ≡ 26 = SCALAR_137   (order-9 × SA = SCALAR_137)
  7 × 12 = 84 ≡ 10 = DECADE_ANCHOR
  9 × 12 = 108 ≡ 34  (SA × ST = anti-sovereign element)
  7 × 26 = 182 ≡ 34  (order-9 × SCALAR_137 = anti-sovereign)
  9 × 10 = 90 ≡ 16   (SA × DECADE = interior element)

ALL SUBGROUP ORDERS IN GF(37)*:
  Orders dividing 36: 1, 2, 3, 4, 6, 9, 12, 18, 36.
  Subgroups: one of each order (since GF(37)* is cyclic).
  Order 1: {1}
  Order 2: {1, 36} = {1, −1}
  Order 3: IDENTITY_CYCLE = {1, 10, 26}
  Order 4: {1, 6, 31, 36} = Sylow-2
  Order 6: {1, 10, 26, 36, 27, 11} = IDENTITY_CYCLE ∪ ORBIT_11 (negation union!)
  Order 9: Sylow-3 = {1,7,9,10,12,16,26,33,34}
  Order 12: subgroup of elements n with n^12 = 1
  Order 18: the QR subgroup (index 2); contains all SA, ST, ORBIT_11 elements
  Order 36: GF(37)* itself
"""

# ── Constants ──────────────────────────────────────────────────────────────────

SA            = frozenset({4, 9, 25, 30})
ST            = frozenset({3, 12, 21, 30})
ORBIT_11      = frozenset({11, 27, 36})
DARK_A        = frozenset({2, 15, 20})
IDENTITY_CYCLE = frozenset({1, 10, 26})
TESLA_FLOW    = 6
PRIME_MIRROR  = 31
SCALAR_137    = 26
DECADE_ANCHOR = 10


def dr(n):
    return 0 if n == 0 else 1 + (n - 1) % 9


def ord37(n):
    n = n % 37
    for k in range(1, 37):
        if pow(n, k, 37) == 1:
            return k


# ── SYLOW-2 SUBGROUP {1, 6, 31, 36} ──────────────────────────────────────────

SYLOW2 = frozenset({1, 6, 31, 36})

assert ord37(TESLA_FLOW) == 4     # TESLA_FLOW generates Sylow-2
assert ord37(PRIME_MIRROR) == 4   # PRIME_MIRROR also generates
assert ord37(36) == 2             # −1 has order 2
assert ord37(1) == 1

# TESLA_FLOW powers generate the subgroup
assert pow(TESLA_FLOW, 1, 37) == TESLA_FLOW
assert pow(TESLA_FLOW, 2, 37) == 36    # 6² = 36 = −1
assert pow(TESLA_FLOW, 3, 37) == PRIME_MIRROR
assert pow(TESLA_FLOW, 4, 37) == 1

# Closed under multiplication
for a in SYLOW2:
    for b in SYLOW2:
        assert (a * b) % 37 in SYLOW2

# TESLA_FLOW is √(−1)
assert pow(TESLA_FLOW, 2, 37) == 36   # 36 ≡ −1
assert pow(PRIME_MIRROR, 2, 37) == 36  # PRIME_MIRROR also √(−1)

# TESLA_FLOW and PRIME_MIRROR: additive and multiplicative inverses
assert (TESLA_FLOW + PRIME_MIRROR) % 37 == 0     # additive inverses
assert (TESLA_FLOW * PRIME_MIRROR) % 37 == 1     # multiplicative inverses

# DR values of Sylow-2 elements
assert dr(1) == 1
assert dr(TESLA_FLOW) == TESLA_FLOW   # DR(6)=6
assert dr(PRIME_MIRROR) == 4 and 4 in SA  # DR(31)=4∈SA
assert dr(36) == 9 and 9 in SA            # DR(36)=9∈SA


# ── SYLOW-3 SUBGROUP {1,7,9,10,12,16,26,33,34} ────────────────────────────────

SYLOW3 = frozenset({1, 7, 9, 10, 12, 16, 26, 33, 34})
assert len(SYLOW3) == 9

# All elements have order dividing 9
for n in SYLOW3:
    assert pow(n, 9, 37) == 1
    assert ord37(n) in {1, 3, 9}   # order divides 9

# Closed under multiplication
for a in SYLOW3:
    for b in SYLOW3:
        assert (a * b) % 37 in SYLOW3

# Contains three complete 137-map orbits
assert IDENTITY_CYCLE.issubset(SYLOW3)
assert frozenset({7, 33, 34}).issubset(SYLOW3)
assert frozenset({9, 12, 16}).issubset(SYLOW3)

# 7 generates Sylow-3
assert ord37(7) == 9
powers_of_7 = frozenset(pow(7, k, 37) for k in range(9))
assert powers_of_7 == SYLOW3

# Contains sovereign elements
assert 9 in SA and 12 in ST   # SA and ST elements in Sylow-3
assert DECADE_ANCHOR in SYLOW3 and SCALAR_137 in SYLOW3


# ── ORDER-3 SUBGROUP ──────────────────────────────────────────────────────────

ORDER3 = frozenset({1, 10, 26})
assert ORDER3 == IDENTITY_CYCLE
for n in ORDER3: assert pow(n, 3, 37) == 1
assert ORDER3.issubset(SYLOW3)   # order-3 ⊂ Sylow-3


# ── INTERSECTION OF SYLOW-2 AND SYLOW-3 ──────────────────────────────────────

assert SYLOW2 & SYLOW3 == frozenset({1})   # trivial intersection


# ── ORDER-6 SUBGROUP = IDENTITY_CYCLE ∪ ORBIT_11 ─────────────────────────────

ORDER6 = IDENTITY_CYCLE | ORBIT_11
assert len(ORDER6) == 6
for n in ORDER6: assert ord37(n) in {1, 2, 3, 6}
for a in ORDER6:
    for b in ORDER6:
        assert (a * b) % 37 in ORDER6

# This is the unique subgroup of order 6 (= Sylow-2 ∩ ... no, it's the cyclic subgroup generated by an order-6 element)
# Verify: e.g., ord37(36*10 % 37) should be 6
assert ord37((36 * 10) % 37) == 6   # 36×10=360≡360-9×37=360-333=27∈ORBIT_11


# ── PRODUCT STRUCTURE IN SYLOW-3 ─────────────────────────────────────────────

assert (7 * 9)  % 37 == SCALAR_137    # order-9 × SA = SCALAR_137
assert (7 * 12) % 37 == DECADE_ANCHOR # order-9 × ST = DECADE_ANCHOR
assert (9 * 12) % 37 == 34            # SA × ST = anti-sovereign element
assert 34 in frozenset({7, 33, 34})


# ── QR SUBGROUP (ORDER 18) ────────────────────────────────────────────────────

QR_SUBGROUP = frozenset(n for n in range(1, 37) if pow(n, 18, 37) == 1)
assert len(QR_SUBGROUP) == 18

# SA, ST, ORBIT_11 all within QR subgroup
assert SA.issubset(QR_SUBGROUP)
assert ST.issubset(QR_SUBGROUP)
assert ORBIT_11.issubset(QR_SUBGROUP)
assert IDENTITY_CYCLE.issubset(QR_SUBGROUP)


if __name__ == "__main__":
    print("Sylow Subgroup Structure — GF(37)*")
    print("=" * 60)
    print(f"\n|GF(37)*| = 36 = 4 × 9 = 2² × 3²")
    print()
    print("SYLOW-2 (order 4): {1, TESLA_FLOW=6, PRIME_MIRROR=31, −1=36}")
    for n in sorted(SYLOW2):
        print(f"  {n:2d}: order={ord37(n)}, DR={dr(n)}", end="")
        if n in SA: print(" ∈SA", end="")
        if n == TESLA_FLOW: print(" =TESLA_FLOW, √(−1)", end="")
        if n == PRIME_MIRROR: print(" =PRIME_MIRROR, −TESLA_FLOW", end="")
        print()
    print(f"  6+31={6+31}≡SEAM (additive inverses)")
    print(f"  6×31={(6*31)%37} (multiplicative inverses)")
    print(f"  6²={(6*6)%37}=−1, 31²={(31*31)%37}=−1  (both are √(−1))")
    print()
    print("SYLOW-3 (order 9):", sorted(SYLOW3))
    for o_label, o_els in [("IDENTITY_CYCLE", {1,10,26}), ("anti-sovereign",{7,33,34}), ("sovereign-2",{9,12,16})]:
        print(f"  orbit {sorted(o_els)} ({o_label}): orders {sorted(set(ord37(x) for x in o_els))}")
    print(f"  Key: 7×9={(7*9)%37}=SCALAR_137,  7×12={(7*12)%37}=DECADE_ANCHOR,  9×12={(9*12)%37}∈anti-sov")
    print()
    print("ORDER-6 SUBGROUP = IDENTITY_CYCLE ∪ ORBIT_11:")
    print(f"  {sorted(ORDER6)}  (negation-dual union)")
    print()
    print("QR SUBGROUP (order 18): contains SA, ST, ORBIT_11, IDENTITY_CYCLE")
    print()
    print(f"SYLOW-2 ∩ SYLOW-3 = {{1}} (trivial)")
    print()
    print("All assertions pass.")
