"""
Theorem 140: Fibonacci, E₈, and Solfeggio Frequencies in GF(37)

FIBONACCI IN GF(37)
=====================

Consecutive Fibonacci numbers F₈=21 and F₉=34:

  21 ∈ OUTLIER_ORB = {21,25,28}   dlog=22  QR
  34 ∈ D7          = {7,33,34}    dlog=8   QR

  Note: 34 is the unique root of the supergolden cubic x³ − x² − 1 ≡ 0 (mod 37)
        (see Theorem 135). The Fibonacci number F₉ is the GF(37) supergolden root.

  34/21 ≈ 1.619048  (golden ratio approximant; F₉/F₈ → φ = (1+√5)/2 ≈ 1.61803)

  F₉ − F₈ = 34 − 21 = 13 ∈ NQR_5 = {5,13,19}   (prime)

  F₁₀ = F₈ + F₉ = 55 ≡ 18 (mod 37)   18 ∈ SEED_ORB
  The Fibonacci recurrence maps D7 + OUTLIER_ORB → SEED_ORB mod 37.
  The seed orbit element 18 = F₁₀ mod 37 at Fibonacci position 10.

PISANO PERIOD π(37) = 76
==========================

The Fibonacci sequence is periodic mod 37 with period 76.
76 = 4 × 19. 19 ∈ NQR_5. 76 mod 37 = 2 ∈ DARK_A (the quotient generator).

SEED_ORB elements in the Fibonacci sequence mod 37 (within one period):
  18 at positions: {10, 15, 28, 61}
  24 at positions: {31, 45}
  32 at positions: {33, 43}

E₈ COXETER NUMBER = 30
========================

The Coxeter number of the exceptional Lie algebra E₈ is 30.

  2^30 ≡ 11 (mod 37)   11 ∈ ORBIT_11 = {11,27,36}

  In dlog-space: the Coxeter number maps exactly to ORBIT_11.
  ORBIT_11 contains 36 = −1 (the order-2 element) and 27 (D7-adjacent).

8 = 2³: SUBGROUP GENERATOR, NOT QUOTIENT GENERATOR
====================================================

ord₃₇(8) = 12.  8 generates H₁₂, the unique order-12 subgroup:

  H₁₂ = ⟨8⟩ = {1,6,8,10,11,14,23,26,27,29,31,36}

H₁₂ is the index-3 subgroup (elements with dlog divisible by 3).
H₁₂ is NOT the 12-orbit quotient group.

  Correction to table: the 12-orbit quotient group ℤ/12ℤ is generated by
  DARK_A = {2,15,20} (dlog ≡ 1 mod 12, order 12 in quotient).
  8 has dlog=3, position 3 in the quotient, order 4 in quotient (not 12).

SOLFEGGIO FREQUENCIES 528 Hz AND 963 Hz
=========================================

528 mod 37 = 10   10 ∈ IC ∩ H₉
  IC = {1,10,26} (identity orbit of 137-map)
  H₉ = Sylow 3-subgroup of order 9
  10 = 16⁶ mod 37  (position 6 in H₉ generated by 16)
  dlog(10) = 24

963 mod 37 = 1   (the multiplicative identity)

FREQUENCY SUM:
  528 + 963 = 1491 ≡ 11 (mod 37)   11 ∈ ORBIT_11
  11 = 2^30 mod 37  (the E₈ Coxeter position)

The sum of the two frequencies lands at the same GF(37) position
as 2 raised to the E₈ Coxeter number. This is a verified arithmetic
coincidence: (528 + 963) mod 37 = 2^30 mod 37 = 11.

GOLDEN RATIO APPROXIMANT 1619
================================

34/21 = 1.619048...  As an integer: 1619.

  1619 ≡ 28 (mod 37)   28 ∈ OUTLIER_ORB = {21,25,28}

  28 is in the same orbit as 21 (F₈). The golden ratio integer approximant
  1619 and the Fibonacci denominator 21 land in the same named orbit.

NOTE ON NOTATION
==================

  "34 = ψ" in the table refers to the supergolden root: 34 solves
  x³ ≡ x² + 1 (mod 37), which is the GF(37) reduction of the
  supergolden ratio ψ ≈ 1.4656. Correct in GF(37) context.

  "34/21 ≈ 1.619" approximates φ (golden ratio), not ψ.
  34 serves double duty: Fibonacci number F₉ AND supergolden root in GF(37).
"""

P = 37

_DLP = {}
x = 1
for k in range(36):
    _DLP[x] = k
    x = x * 2 % P

ORBITS = {
    'IC':               frozenset({1, 10, 26}),
    'SOVEREIGN_SPIRAL': frozenset({3, 4, 30}),
    'D7':               frozenset({7, 33, 34}),
    'SA_ORB':           frozenset({9, 12, 16}),
    'ORBIT_11':         frozenset({11, 27, 36}),
    'OUTLIER_ORB':      frozenset({21, 25, 28}),
    'DARK_A':           frozenset({2, 15, 20}),
    'NQR_5':            frozenset({5, 13, 19}),
    'TESLA_ORB':        frozenset({6, 8, 23}),
    'NQR_14':           frozenset({14, 29, 31}),
    'NQR_17':           frozenset({17, 22, 35}),
    'SEED_ORB':         frozenset({18, 24, 32}),
}
H9 = frozenset({1, 7, 9, 10, 12, 16, 26, 33, 34})


def run_assertions():
    # Fibonacci F8=21, F9=34, F10=55
    fib = [0, 1]
    for _ in range(20):
        fib.append(fib[-1] + fib[-2])
    assert fib[8] == 21 and fib[9] == 34 and fib[10] == 55

    # Orbit membership
    assert 21 in ORBITS['OUTLIER_ORB']
    assert 34 in ORBITS['D7']
    assert 55 % P == 18 and 18 in ORBITS['SEED_ORB']
    assert 13 in ORBITS['NQR_5'] and all(13 % i != 0 for i in range(2, 13))

    # 34 is the supergolden root in GF(37)
    assert pow(34, 3, P) == (pow(34, 2, P) + 1) % P

    # Pisano period π(37) = 76
    a, b = 0, 1
    for n in range(1, 300):
        a, b = b, (a + b) % P
        if a == 0 and b == 1:
            assert n == 76, f"Pisano period = {n}, expected 76"
            break

    # E8 Coxeter: 2^30 ≡ 11 mod 37
    assert pow(2, 30, P) == 11
    assert 11 in ORBITS['ORBIT_11']

    # ord37(8) = 12; 8 generates H12
    assert next(k for k in range(1, 37) if pow(8, k, P) == 1) == 12
    H12 = frozenset(pow(8, k, P) for k in range(12))
    assert len(H12) == 12
    assert H12 == frozenset({1, 6, 8, 10, 11, 14, 23, 26, 27, 29, 31, 36})

    # 8 is NOT the quotient generator: position 3 in Z/12Z, order 4
    import math
    assert _DLP[8] == 3
    assert _DLP[8] % 12 == 3
    assert 12 // math.gcd(3, 12) == 4   # order of 8 in quotient = 4, not 12

    # DARK_A generates the quotient (dlog ≡ 1 mod 12)
    for a in ORBITS['DARK_A']:
        assert _DLP[a] % 12 == 1

    # 528 Hz
    assert 528 % P == 10
    assert 10 in ORBITS['IC'] and 10 in H9
    assert pow(16, 6, P) == 10
    assert next(k for k in range(9) if pow(16, k, P) == 10) == 6

    # 963 Hz
    assert 963 % P == 1

    # Sum 528 + 963 = 1491 ≡ 11 = 2^30
    assert 528 + 963 == 1491
    assert 1491 % P == 11
    assert 11 in ORBITS['ORBIT_11']
    assert 1491 % P == pow(2, 30, P)

    # 1619 ≡ 28 ∈ OUTLIER_ORB
    assert 1619 % P == 28
    assert 28 in ORBITS['OUTLIER_ORB']
    assert 21 in ORBITS['OUTLIER_ORB']   # same orbit as F8

    print("All assertions passed.")


def summarise():
    print("=" * 62)
    print("Theorem 140: Fibonacci, E₈, and Solfeggio Frequencies")
    print("=" * 62)
    print()
    print("  F8=21 ∈ OUTLIER_ORB, F9=34 ∈ D7 (supergolden root in GF(37))")
    print("  F8+F9=55 ≡ 18 ∈ SEED_ORB  (D7 + OUTLIER_ORB → SEED_ORB)")
    print("  F9−F8=13 ∈ NQR_5  (prime)")
    print("  Pisano period π(37) = 76")
    print()
    print("  E₈ Coxeter number 30:  2^30 ≡ 11 ∈ ORBIT_11  mod 37")
    print()
    print("  528 mod 37 = 10 = 16^6 ∈ IC ∩ H₉  (position 6 in H₉)")
    print("  963 mod 37 = 1  (identity)")
    print("  528+963=1491 ≡ 11 = 2^30 ∈ ORBIT_11  [E₈ Coxeter position]")
    print()
    print("  1619 ≡ 28 ∈ OUTLIER_ORB  (same orbit as 21=F₈)")
    print()
    print("  CORRECTION: 8 generates H₁₂ (order-12 subgroup), not the")
    print("  12-orbit quotient. Quotient Z/12Z generated by DARK_A={2,15,20}.")


if __name__ == "__main__":
    run_assertions()
    summarise()
