# CLASS: THEOREM
"""
T433 — The complete structure of the 12 orbits of x -> 26x on GF(37)*:
multiplicative side, decimal side, and (new) additive side.

Everything below follows from two definitions: p = 37, and the map x -> 26x
(26 = 137 mod 37). Each part is asserted in run(); parts already stated
elsewhere in the repo cite that file. Parts 7-10 have no prior art in the
repo (searched 2026-09-30 for cyclotomic numbers, Gauss periods, period
polynomial, Jacobi sums: 0 files).

NOTATION. g = 2 (a primitive root mod 37). ind(x) = discrete log base 2.
H = <26> = {1, 10, 26}, |H| = 3. e = 12 orbits, f = 3 elements each.
Orbit index of x: j(x) = ind(x) mod 12. Index -> name (functions.ORBITS):
  0 IC {1,10,26}    1 DARK_A {2,15,20}  2 C3 {3,4,30}       3 TESLA {6,8,23}
  4 SA_ST_A {9,12,16} 5 SEED {18,24,32} 6 NEG_H {11,27,36}  7 NQR17 {17,22,35}
  8 D7 {7,33,34}    9 C9 {14,29,31}    10 SA_ST_B {21,25,28} 11 CAS_EXT {5,13,19}

MULTIPLICATIVE SIDE (prior art cited)
 1. 26 = 10^2 (mod 37), so H = <26> = <10>: the 137-map is multiplication by
    100, i.e. a two-decimal-digit shift mod 37. ind(10) = 24, ind(26) = 12.
    [decimal_trinity.py: <10> = {1,10,26}]
 2. The orbits are the cosets xH; j is a group isomorphism G/H -> Z/12:
    j(xy) = j(x) + j(y). Orbit multiplication is well defined.
    [T138, T200, T285, T339]
 3. The subgroups between H and G correspond to divisors d of 12: the
    subgroup {x : d | j(x)} of order 36/d. Squares: j even (6 orbits);
    cubes: 3 | j (4 orbits); fourth powers: 4 | j (3 orbits); sixth powers:
    6 | j (2 orbits); twelfth powers: H itself.  [T118, T286]
 4. -1 = 2^18 has j = 6: negation is the shift j -> j + 6, pairing the orbits
    0-6, 1-7, 2-8, 3-9, 4-10, 5-11.  [T283 (lemma)]
 5. Every orbit {x, 10x, 26x} has 37 | x + 10x + 26x = 37x. With
    representatives in 1..36 the sum is 37 or 74, six orbits each; negation
    r -> 37 - r sends a sum S to 111 - S, swapping 37 and 74, which forces the
    6/6 split.  [basin_sum_wraparound_gf37.py, T331, T332]

DECIMAL SIDE
 6. The orbit of a (1 <= a <= 36) is exactly the set of remainders in the long
    division of a/37 (remainder_k = a*10^k mod 37, period 3 = ord(10)). The
    period of a/37 is the 3-digit block 27a (a/37 = 27a/999). Numbers that
    differ by a factor 10^k lie in the same orbit.  [abcabc_mod37_orbit.py]

ADDITIVE SIDE (new)
 7. Orbit ADDITION is not well defined. For x in O_a, y in O_b, the orbit of
    x + y is distributed by the cyclotomic numbers of order 12:
        (i, j) = #{u in O_i : 1 + u in O_j}.
    #{(x, y) in O_a x O_b : x + y in O_c} = 3 * (b - a, c - a).
    The full 12x12 table is asserted below. Row sums are 3 except row 6 (=2,
    since -1 in O_6); column sums 3 except column 0 (=2). Identities checked:
    (i, j) = (-i, j - i) and, f = 3 being odd, (i, j) = (j + 6, i + 6).
    No orbit pair has a single-orbit sum: every pair (a, b) yields between 2
    and 3 distinct result orbits (or 0 when x + y = 0).
 8. Gauss periods eta_j = sum over x in O_j of zeta^x, zeta = exp(2 pi i/37).
    sum_j eta_j = -1, and eta_{j+6} = conj(eta_j) (because -1 in O_6): the
    periods are 6 conjugate pairs, none real.
 9. MULTIPLICATION OF PERIODS = the cyclotomic numbers:
        eta_a * eta_b = sum_k (b - a, k) * eta_{a+k}  +  3 * [b - a = 6].
    Checked for all 144 pairs (a, b) to 1e-40. This is the bridge: the
    additive table of part 7 is exactly the multiplication table of the
    periods.
10. The period polynomial P(X) = prod_j (X - eta_j) has integer coefficients
    (asserted exactly) and is irreducible over Q: the fixed field of H in
    Q(zeta_37) has degree 12 and is generated by any single period.

ARITHMETIC OF 37 IN THE CHARACTER GROUP (new)
11. The 12 characters trivial on H are chi_m(x) = exp(2 pi i m j(x)/12).
    Jacobi sums J(chi, psi) = sum_x chi(x) psi(1 - x) have |J|^2 = 37 whenever
    chi, psi, chi*psi are nontrivial (all such pairs checked). Their values
    give the classical representations
        37 = 1^2 + 6^2        (order-4 character: J(chi_3, chi_3) = -1 +/- 6i)
        4*37 = 11^2 + 27*1^2  (order-3 character)
    Consistent with the classical criteria: 2 is not a cube mod 37 (L = 11 is
    odd) and not a fourth power (37 != a^2 + 64 b^2); both also read off j(2) = 1.

    Mod 37, P(X) = (X - 3)^12 exactly: 37 is totally ramified in Q(zeta_37), so
    zeta = 1 modulo the prime above 37 and each period (3 powers of zeta) = 3.

WHAT IS AND IS NOT FORCED
12. 137 = 100 + 37, so 137 = 100 (mod p) exactly when p | 37: the 137-map being
    the two-digit decimal shift (part 1) holds for p = 37 and no other prime.
13. The 37/74 orbit-sum split (part 5) is NOT decided by the orbit group. The
    sum-37 orbits are j in {11, 0, 1, 2, 3, 4}. Every even character chi_m
    sums to 0 over them (that is exactly the negation pairing of parts 4-5);
    every odd character is nonzero, so no character condition selects them.
    They form a run of 6 consecutive indices for only 6 of the 12 primitive
    roots used as index base (2, 5, 13, 15, 19, 20): the "arc" is an artifact
    of labeling, not an invariant. The split depends on representatives in
    1..36, an ordering property the group does not see.

THE TWIN-PRIME / PRIME-GAP BASELINES FOLLOW FROM PART 7
14. For any gap g (1 <= g <= 36) and residue r with r + g != 0, the orbit of
    r + g given the orbit of r is the cyclotomic table shifted by j(g):
        #{r in O_a : r + g in O_c} = (a - j(g), c - j(g)).
    So the transition matrix for every gap is a relabeling of ONE table, and its
    diagonal sums sum_b (b, b + d) are 2 for d = 0 and 3 for each d != 0
    (2 + 11*3 = 35). Hence, for every gap:
        P(orbit(r+g) = orbit(r))            = 2/35
        P(orbit(r+g) = negation dual)       = 3/35
        P(orbit shift = d), d != 0          = 3/35 each
    These are the baselines in T336 (twin primes: 2/35 at r = 6, 29; duals
    3/35), T347 (orbit(p) = orbit(p+g) iff 1 + g/p in <10>) and T362 (dj = 0 ->
    2/35, dj != 0 -> 3/35). They are not properties of twin primes or of any
    gap: they are the diagonal sums of the order-12 cyclotomic numbers of 37.

SCOPE. Parts 7-11 are classical theory (Gauss periods, Dickson's cyclotomic
numbers, Jacobi sums) evaluated at p = 37, e = 12. They hold in the same form
for every prime p = ef + 1; the specific tables and values are 37's. What is new
to this repo is that its 12 named orbits ARE the order-12 cyclotomic classes, so
this whole classical machinery applies to them verbatim, and that orbit addition
(used informally in several files) is governed by the table in part 7, not by a
well-defined operation.

FALSIFICATION: any assertion in run() failing.
"""
import itertools
import math
import os
import sys

from mpmath import mp, mpc, mpf, exp, pi, nint, fabs, conj

sys.path.append(next(os.path.dirname(p) for p in [os.path.abspath(__file__)] for _ in [0]) + "/../..")
from functions import ORBITS  # noqa: E402

P, G, E, F = 37, 2, 12, 3


def setup():
    ind = {pow(G, k, P): k for k in range(P - 1)}
    j = {x: ind[x] % E for x in range(1, P)}
    O = [sorted(x for x in range(1, P) if j[x] == a) for a in range(E)]
    return ind, j, O


def cyclotomic_numbers(j, O):
    return [[sum(1 for u in O[a] if (1 + u) % P and j[(1 + u) % P] == b) for b in range(E)] for a in range(E)]


CYCLO = [
    [0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0],
    [0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
]


def run():
    mp.dps = 60
    ind, j, O = setup()
    names = {a: next(n for n, s in ORBITS.items() if set(O[a]) == s) for a in range(E)}
    assert [names[a] for a in range(E)] == ['IC', 'DARK_A', 'C3', 'TESLA', 'SA_ST_A', 'SEED',
                                            'NEG_H', 'NQR17', 'D7', 'C9', 'SA_ST_B', 'CAS_EXT']

    # 1. 137-map = x100
    assert 137 % P == 26 == pow(10, 2, P) and ind[10] == 24 and ind[26] == 12
    assert {pow(26, k, P) for k in range(3)} == {pow(10, k, P) for k in range(3)} == {1, 10, 26}

    # 2. G/H -> Z/12 is a homomorphism
    assert all(j[x * y % P] == (j[x] + j[y]) % E for x in range(1, P) for y in range(1, P))

    # 3. intermediate subgroups
    for d in (1, 2, 3, 4, 6, 12):
        S = {x for x in range(1, P) if j[x] % d == 0}
        assert len(S) == 36 // d and all(x * y % P in S for x in S for y in S)
        assert S == {pow(x, d, P) for x in range(1, P)}          # d | j(x)  <=>  x is a d-th power
    assert {pow(x, 12, P) for x in range(1, P)} == {1, 10, 26}

    # 4. negation = shift by 6
    assert j[P - 1] == 6 and all(j[P - x] == (j[x] + 6) % E for x in range(1, P))

    # 5. orbit sums
    sums = [sum(o) for o in O]
    assert all(s in (37, 74) for s in sums) and sums.count(37) == sums.count(74) == 6
    assert all(sums[(a + 6) % E] == 111 - sums[a] for a in range(E))

    # 6. long-division remainders of a/37 = orbit of a; period block = 27a
    for a in range(1, P):
        rem, r = set(), a
        for _ in range(6):
            rem.add(r)
            r = r * 10 % P
        assert rem == set(O[j[a]])
        assert a * 27 < 1000 and round(a / 37 * 999) == 27 * a

    # 7. cyclotomic numbers and additive distribution
    C = cyclotomic_numbers(j, O)
    assert C == CYCLO
    assert [sum(r) for r in C] == [3] * 6 + [2] + [3] * 5
    assert [sum(C[a][b] for a in range(E)) for b in range(E)] == [2] + [3] * 11
    assert all(C[a][b] == C[(-a) % E][(b - a) % E] for a in range(E) for b in range(E))
    assert all(C[a][b] == C[(b + 6) % E][(a + 6) % E] for a in range(E) for b in range(E))
    outcomes = []
    for a in range(E):
        for b in range(E):
            cnt = {}
            for x in O[a]:
                for y in O[b]:
                    s = (x + y) % P
                    if s:
                        cnt[j[s]] = cnt.get(j[s], 0) + 1
            for c in range(E):
                assert cnt.get(c, 0) == 3 * C[(b - a) % E][(c - a) % E]
            outcomes.append(len(cnt))
    assert min(outcomes) == 2 and max(outcomes) == 3

    # 8. Gauss periods
    z = [exp(2 * pi * mpc(0, 1) * k / P) for k in range(P)]
    eta = [sum(z[x] for x in O[a]) for a in range(E)]
    assert fabs(sum(eta) + 1) < mpf(10) ** -50
    assert all(fabs(eta[(a + 6) % E] - conj(eta[a])) < mpf(10) ** -50 for a in range(E))
    assert all(fabs(eta[a].imag) > mpf("0.01") for a in range(E))

    # 9. multiplication of periods
    for a in range(E):
        for b in range(E):
            rhs = sum(C[(b - a) % E][k] * eta[(a + k) % E] for k in range(E)) + (3 if (b - a) % E == 6 else 0)
            assert fabs(eta[a] * eta[b] - rhs) < mpf(10) ** -40

    # 10. period polynomial: integer coefficients, irreducible
    coeffs = [mpc(1)]
    for a in range(E):
        coeffs = [c - eta[a] * d for c, d in zip(coeffs + [0], [0] + coeffs)]
    ints = [int(nint(c.real)) for c in coeffs]
    assert all(fabs(c - i) < mpf(10) ** -40 for c, i in zip(coeffs, ints))
    import sympy
    X = sympy.symbols('X')
    poly = sympy.Poly(ints, X)               # ints are highest power first
    assert poly.is_irreducible and poly.degree() == 12 and poly.LC() == 1
    assert ints[1] == 1                       # X^12 + X^11 + ...: trace of the periods is -1
    # mod 37: P(X) = (X - 3)^12. 37 is totally ramified in Q(zeta_37) (zeta = 1 mod the prime
    # above 37), so every period, a sum of f = 3 powers of zeta, is = 3 there.
    fl = sympy.factor_list(sympy.Poly(ints, X, modulus=P))
    assert fl == (1, [(sympy.Poly(X - 3, X, modulus=P), 12)])

    # 11. Jacobi sums of the characters trivial on H
    w = [exp(2 * pi * mpc(0, 1) * k / E) for k in range(E)]

    def chi(m, x):
        return mpc(0) if x % P == 0 else w[(m * j[x % P]) % E]

    def J(m, n):
        return sum(chi(m, x) * chi(n, 1 - x) for x in range(P))

    for m in range(1, E):
        for n in range(1, E):
            if (m + n) % E:
                assert fabs(abs(J(m, n)) ** 2 - 37) < mpf(10) ** -40
    j4 = J(3, 3)                               # chi_3 has order 4
    a4, b4 = int(nint(j4.real)), int(nint(j4.imag))
    assert fabs(j4 - mpc(a4, b4)) < mpf(10) ** -40 and a4 * a4 + b4 * b4 == 37 and (a4, abs(b4)) == (-1, 6)
    j3 = J(4, 4)                               # chi_4 has order 3; J = A + B*omega
    om = exp(2 * pi * mpc(0, 1) / 3)
    B = int(nint(j3.imag / om.imag))
    A = int(nint((j3 - B * om).real))
    assert fabs(j3 - (A + B * om)) < mpf(10) ** -40 and A * A - A * B + B * B == 37
    L, M3 = 2 * A - B, B
    assert L * L + 3 * M3 * M3 == 4 * 37 and abs(L) == 11 and M3 % 3 == 0 and abs(M3 // 3) == 1
    assert j[2] % 3 != 0 and j[2] % 4 != 0 and L % 2 == 1
    assert not any(a * a + 64 * b * b == 37 for a in range(7) for b in range(1))
    # 12. 137 = 100 mod p only for p = 37
    assert 137 - 100 == 37 and [q for q in range(2, 10 ** 4) if all(q % r for r in range(2, math.isqrt(q) + 1))
                                and (137 - 100) % q == 0] == [37]
    # 13. the 37/74 split is not a character condition, and its arc shape depends on the generator
    s37 = [a for a in range(E) if sums[a] == 37]
    assert s37 == [0, 1, 2, 3, 4, 11]
    chis = [abs(sum(w[(m * a) % E] for a in s37)) for m in range(1, E)]
    assert all(chis[m - 1] < mpf(10) ** -40 for m in range(2, E, 2))
    assert all(chis[m - 1] > mpf("0.5") for m in range(1, E, 2))
    arcs = []
    for g in (x for x in range(2, P) if len({pow(x, k, P) for k in range(36)}) == 36):
        ig = {pow(g, k, P): k for k in range(36)}
        t = {ig[x] % E for o in O if sum(o) == 37 for x in o}
        if any(t == {(st + i) % E for i in range(6)} for st in range(E)):
            arcs.append(g)
    assert arcs == [2, 5, 13, 15, 19, 20]
    # 14. every gap's orbit-transition matrix is the cyclotomic table shifted by j(g)
    diag = [sum(C[b][(b + d) % E] for b in range(E)) for d in range(E)]
    assert diag == [2] + [3] * 11
    for gap in range(1, P):
        sh = j[gap]
        D = [[0] * E for _ in range(E)]
        for r in range(1, P):
            if (r + gap) % P:
                D[j[r]][j[(r + gap) % P]] += 1
        assert D == [[C[(a - sh) % E][(c - sh) % E] for c in range(E)] for a in range(E)]
        assert sum(D[a][a] for a in range(E)) == 2 and sum(D[a][(a + 6) % E] for a in range(E)) == 3
    assert [r for r in range(1, P) if (r + 2) % P and j[r] == j[(r + 2) % P]] == [6, 29]   # T336
    return {"orbit_sums": sums, "outcomes": (min(outcomes), max(outcomes)), "period_poly": ints,
            "J4": (a4, b4), "J3": (A, B), "L": L}


if __name__ == "__main__":
    r = run()
    print("T433 orbit structure closure: all assertions pass")
    print("  period polynomial (X^12 ...):", r["period_poly"])
    print("  J(order 4) =", r["J4"], " J(order 3) = A + B*omega with (A, B) =", r["J3"], " L =", r["L"])
