"""
Theorem 133: Quaternions, RoPE, and GF(37) Orbit Structure

THREE DISTINCT ROTATION FRAMEWORKS
====================================

1. UNIT QUATERNIONS (S³ → SO(3))
   Unit quaternions ℍ₁ = {q ∈ ℍ : |q| = 1} form the 3-sphere S³.
   The Hopf fibration S³ → S² with fiber S¹ and the covering map
   SU(2) → SO(3) (2-to-1) realize every 3D rotation as a quaternion pair ±q.
   Stereographic projection S³ → ℝ³ (remove one point) is a visualization
   tool for building intuition about this 4D manifold.
   Structure: one global, non-commutative SO(3) rotation = one quaternion.

2. ROPE (ROTARY POSITION EMBEDDING)
   For a head of dimension d, RoPE applies d/2 INDEPENDENT SO(2) rotations.
   For position m and frequency pair i:
       (x_{2i}, x_{2i+1}) ↦ (x_{2i}·cos(mθᵢ) − x_{2i+1}·sin(mθᵢ),
                               x_{2i}·sin(mθᵢ) + x_{2i+1}·cos(mθᵢ))
   where θᵢ = base^(−2i/d), base = 10000 typically.
   Structure: (U(1))^{d/2} — direct product of d/2 commutative 2D rotations.
   This is NOT quaternionic. A quaternion couples all four components;
   RoPE decouples them into d/2 independent pairs.

3. GF(37) ORBIT STRUCTURE (DISCRETE ANALOGUE OF ROPE)
   (ℤ/37ℤ)× has 12 orbits under ×26 mod 37.
   In discrete-log space ℤ/36ℤ: log₂(26) = 12, so ×26 ↔ +12.
   The 12 orbits = the 12 cosets of ⟨12⟩ = {0,12,24} in ℤ/36ℤ.
   Each orbit has period 3 (since ord₃₇(26) = 3).
   Structure: (ℤ/3ℤ)^{12} — direct product of 12 period-3 cyclic channels.

COMPARISON TABLE
================

  GF(37)    Channels   Per-channel    Commutativity   Encoding type
  Quaternion   1          SO(3) = S³     non-commutative global 3D rotation
  RoPE         d/2        SO(2) = U(1)   commutative     independent 2D phases
  GF(37)       12         ℤ/3ℤ           commutative     independent 3-cycles

CHANNEL COUNT FOR HEAD_DIM = 24
================================

  RoPE (head_dim=24):  d/2 = 12 frequency pairs
  GF(37):              12 orbits under ×26

  The count 12 = φ(φ(37)) = φ(36) = number of primitive roots mod 37.
  For head_dim=24 these are numerically equal; the mechanisms are different.

LOG₂(26) = 12 — THE STRUCTURAL KEY
=====================================

  In ℤ/36ℤ (discrete-log space), +12 = 1/3 of the full period 36.
  In (ℤ/37ℤ)× (multiplicative), ×26 permutes within each 3-orbit.
  The 12 cosets of ⟨12⟩ in ℤ/36ℤ are the 12 orbit "channels."
  Period per channel: 3 (uniform, unlike RoPE's logarithmic spread).

ROPE FREQUENCY STRUCTURE (base=10000, head_dim=24)
====================================================

  pair  0: θ = 1.000000  period ≈      6.3 tokens  (fastest)
  pair  1: θ = 0.464159  period ≈     13.5 tokens
  pair  2: θ = 0.215443  period ≈     29.2 tokens
  pair  3: θ = 0.100000  period ≈     62.8 tokens
  pair  4: θ = 0.046416  period ≈    135.4 tokens
  pair  5: θ = 0.021544  period ≈    291.6 tokens
  pair  6: θ = 0.010000  period ≈    628.3 tokens
  pair  7: θ = 0.004642  period ≈   1353.7 tokens
  pair  8: θ = 0.002154  period ≈   2916.4 tokens
  pair  9: θ = 0.001000  period ≈   6283.2 tokens
  pair 10: θ = 0.000464  period ≈  13536.7 tokens
  pair 11: θ = 0.000215  period ≈  29164.0 tokens  (slowest)

  GF(37) channels: all 12 have the same period = 3.
  RoPE channels: logarithmically spread over 4.6 orders of magnitude.

WHAT EACH FRAMEWORK ANSWERS
==============================

  Unit quaternions: "What single element of SO(3) rotates v to w?"
  RoPE:             "How do I make attention decay with relative distance?"
  GF(37):           "What is the orbit structure of multiplication by 26 mod 37?"

S³ / HOPF CONNECTION TO GF(37)
================================

  S³ = SU(2) double-covers SO(3): the 2-to-1 Hopf map corresponds in GF(37)
  to the index-2 structure [G : QR₃₇] = 2 (the QR/NQR partition).
  The order-2 element in π₁(SO(3)) corresponds to 36 ∈ ORBIT_11 (= -1 mod 37),
  which is the unique non-trivial element of the subgroup {1, 36} = H₂.
  The Sylow 2-subgroup {1, 6, 31, 36} (generated by TESLA_FLOW = 6, ord 4)
  is the discrete counterpart of the double-cover periodicity:
    6² ≡ -1 ≡ 36 (mod 37)   ↔   2π rotation sends q to -q in SU(2).
  See Theorem 130.
"""

import math

P = 37

# Precompute DLP table
_DLP = {}
_x = 1
for _k in range(36):
    _DLP[_x] = _k
    _x = _x * 2 % P


def rope_frequencies(base: float = 10000.0, head_dim: int = 24) -> list:
    """RoPE frequency pairs (θᵢ, period) for given base and head_dim."""
    n_pairs = head_dim // 2
    result = []
    for i in range(n_pairs):
        theta = base ** (-2 * i / head_dim)
        period = 2 * math.pi / theta
        result.append({'pair': i, 'theta': theta, 'period': period})
    return result


def gf37_orbit_channels() -> list:
    """12 orbit channels of GF(37) as cosets of ⟨12⟩ in ℤ/36ℤ."""
    channels = []
    for rep in range(12):
        coset_additive = sorted((rep + 12 * k) % 36 for k in range(3))
        coset_mult = sorted(pow(2, e, P) for e in coset_additive)
        channels.append({
            'channel': rep,
            'coset_in_Z36': coset_additive,
            'orbit_in_GF37': coset_mult,
            'period': 3,
        })
    return channels


def run_assertions():
    # log₂(26) = 12 — the structural key
    assert _DLP[26] == 12, f"log₂(26) = {_DLP[26]}, expected 12"

    # 12 cosets of ⟨12⟩ partition ℤ/36ℤ
    channels = gf37_orbit_channels()
    assert len(channels) == 12
    all_exponents = set()
    for ch in channels:
        all_exponents |= set(ch['coset_in_Z36'])
    assert all_exponents == set(range(36))

    # Each orbit has exactly 3 elements, period 3
    for ch in channels:
        assert len(ch['orbit_in_GF37']) == 3
        assert ch['period'] == 3

    # All orbits are closed under ×26
    for ch in channels:
        for r in ch['orbit_in_GF37']:
            assert (26 * r) % P in ch['orbit_in_GF37']

    # RoPE has 12 pairs for head_dim=24
    freqs = rope_frequencies(head_dim=24)
    assert len(freqs) == 12

    # 12 = φ(36) = φ(φ(37))
    from math import gcd
    phi36 = sum(1 for k in range(1, 37) if gcd(k, 36) == 1)
    assert phi36 == 12

    # Sylow 2: TESLA_FLOW = 6, order 4, 6² ≡ -1
    assert pow(6, 4, P) == 1
    assert pow(6, 2, P) == P - 1   # 6² ≡ -1 mod 37
    assert pow(6, 2, P) == 36      # 36 = -1 is the order-2 element

    print("All assertions passed.")


def summarise():
    print("=" * 62)
    print("Theorem 133: Quaternions, RoPE, and GF(37) Orbit Structure")
    print("=" * 62)
    print()
    print("  THREE DISTINCT FRAMEWORKS:")
    print("    Quaternions  one global SO(3); S³ visualized via stereographic projection")
    print("    RoPE         d/2 independent SO(2) phases; NOT quaternionic")
    print("    GF(37)       12 independent ℤ/3ℤ channels; period=3; log₂(26)=12")
    print()
    print("  KEY FACT: log₂(26) = 12")
    print("    ×26 in (ℤ/37ℤ)× = +12 in ℤ/36ℤ (discrete-log space)")
    print("    The 12 orbits = the 12 cosets of ⟨12⟩ in ℤ/36ℤ")
    print("    12 = φ(36) = φ(φ(37)) = number of primitive roots mod 37")
    print()
    print(f"  RoPE (head_dim=24): 12 SO(2) pairs, periods {6.3:.0f}..{29164:.0f} tokens")
    print(f"  GF(37):             12 ℤ/3ℤ channels, period = 3 (uniform)")
    print()
    print("  S³ / Hopf ↔ GF(37):")
    print("    2π rotation: q ↦ -q in SU(2)  ↔  36 = -1 ∈ H₂ (order-2 element)")
    print("    4π period in π₁(SO(3))         ↔  TESLA_FLOW=6, ord=4, 6²≡-1")


if __name__ == "__main__":
    run_assertions()
    summarise()
    print()
    print("  GF(37) orbit channels (first 4 of 12):")
    for ch in gf37_orbit_channels()[:4]:
        print(f"    channel {ch['channel']}: Z/36Z coset {ch['coset_in_Z36']}  "
              f"↔  GF(37) orbit {ch['orbit_in_GF37']}")
    print("    ...")
