"""
T291 — Iterated Squaring Collapses Z/12Z onto its Sylow 3-Subgroup H_3

Extends T290 (one squaring = multiplication by 2 on Z/12Z).

After k squarings, the induced map on Z/12Z is multiplication by 2^k, whose
image is the subgroup of order 12/gcd(12, 2^k).  The descending chain is:

    k=0:  Z/12Z          order 12   all 12 orbits
    k=1:  H_6            order  6   {IC, C3, SA_ST_A, NEG_H, D7, SA_ST_B}
    k=2:  H_3            order  3   {IC, SA_ST_A, D7}
    k>=2: H_3            order  3   STABLE

Terminal image = H_3 = {IC, SA_ST_A, D7}.

WHY IT STOPS THERE: 12 = 2^2 x 3.  Repeated doubling annihilates the 2-part
and cannot touch the odd part, so the chain descends to the odd part of Z/12Z
— the Sylow 3-subgroup — and halts.  It stabilizes after exactly v_2(12) = 2
steps, where v_2 is the 2-adic valuation.

THE ANTIPODAL CONSEQUENCE (connects T283 / T286):
T286 identified H_3 as the UNIQUE subgroup above H_1 that is NOT closed under
the antipodal map.  Antipodal = +6 in Z/12Z (T283/T285), and H_3 = {0,4,8}
does not contain 6.  Therefore:

    Iterated squaring destroys the antipodal structure completely.
    The terminal image contains ZERO complete antipodal pairs.

Every other subgroup in the T286 lattice of order > 1 except H_3 (namely
H_2, H_4, H_6, H_12) is antipodal-closed.  Squaring drives the field onto the
single exception.

In GF(37)* directly: |GF(37)*| = 36 = 2^2 x 3^2.  Repeated squaring lands on
the 4th powers, 9 elements, = the three orbits IC, SA_ST_A, D7.

NOT A CRYPTOGRAPHIC CONSTRUCTION: GF(37)* has 36 elements. Any scheme built on
sequential squaring here (VDF, commitment, proof-of-knowledge) is exhaustively
searchable in 36 operations. This theorem is structural, not a security claim.
"""

from math import gcd

ORBITS = {
    'IC':      {1, 10, 26},
    'DARK_A':  {2, 15, 20},
    'C3':      {3, 4, 30},
    'CAS_EXT': {5, 13, 19},
    'TESLA':   {6, 8, 23},
    'D7':      {7, 33, 34},
    'SA_ST_A': {9, 12, 16},
    'NEG_H':   {11, 27, 36},
    'C9':      {14, 29, 31},
    'NQR17':   {17, 22, 35},
    'SEED':    {18, 24, 32},
    'SA_ST_B': {21, 25, 28},
}

ANTIPODAL = [
    ('IC', 'NEG_H'), ('DARK_A', 'NQR17'), ('C3', 'D7'),
    ('TESLA', 'C9'), ('SA_ST_A', 'SA_ST_B'), ('SEED', 'CAS_EXT'),
]

H_3 = {'IC', 'SA_ST_A', 'D7'}
H_6 = {'IC', 'C3', 'SA_ST_A', 'NEG_H', 'D7', 'SA_ST_B'}

ELEM_TO_ORBIT = {}
for _n, _s in ORBITS.items():
    for _e in _s:
        ELEM_TO_ORBIT[_e] = _n


def orb(x):
    return ELEM_TO_ORBIT.get(x % 37, 'SEAM')


# ─── Part 1: <10> == <26> == IC (same subgroup) ──────────────────────────────

def verify_generator_equivalence():
    """IC is generated by either 10 or 26; framework uses 26 = 137 mod 37."""
    g10 = {pow(10, i, 37) for i in range(3)}
    g26 = {pow(26, i, 37) for i in range(3)}
    assert g10 == g26 == ORBITS['IC'], f"{g10} {g26}"
    assert 137 % 37 == 26
    return g10


# ─── Part 2: image after k squarings = order 12/gcd(12, 2^k) ────────────────

def image_after_k(k):
    """Image classes of multiplication by 2^k on Z/12Z."""
    return sorted({(pow(2, k) * m) % 12 for m in range(12)})


def verify_image_formula():
    for k in range(0, 8):
        img = image_after_k(k)
        predicted = 12 // gcd(12, pow(2, k))
        assert len(img) == predicted, \
            f"k={k}: |image|={len(img)} != 12/gcd(12,2^{k})={predicted}"


# ─── Part 3: chain stabilizes at H_3 after v_2(12)=2 steps ──────────────────

def verify_stabilization():
    prev = None
    stable_at = None
    for k in range(0, 8):
        img = set(image_after_k(k))
        if img == prev:
            stable_at = k - 1
            break
        prev = img
    assert stable_at == 2, f"Stabilized at k={stable_at}, expected 2"

    terminal = {orb(pow(2, c, 37)) for c in prev}
    assert terminal == H_3, f"Terminal image {terminal} != H_3"

    # v_2(12) = 2
    v2 = 0
    n = 12
    while n % 2 == 0:
        n //= 2
        v2 += 1
    assert v2 == 2, f"v_2(12) = {v2}"
    assert n == 3, f"odd part of 12 = {n}"
    return stable_at, terminal, v2, n


# ─── Part 4: terminal image has zero antipodal pairs ────────────────────────

def verify_antipodal_destruction():
    pairs_in_H3 = [(a, b) for a, b in ANTIPODAL if a in H_3 and b in H_3]
    assert pairs_in_H3 == [], f"H_3 contains antipodal pairs: {pairs_in_H3}"

    pairs_in_H6 = [(a, b) for a, b in ANTIPODAL if a in H_6 and b in H_6]
    assert len(pairs_in_H6) == 3, f"H_6 should have 3 antipodal pairs, got {pairs_in_H6}"

    # antipodal = +6; H_3 = {0,4,8} does not contain 6
    assert 6 not in {0, 4, 8}
    return pairs_in_H6


# ─── Part 5: direct verification in GF(37)* ─────────────────────────────────

def verify_direct():
    cur = set(range(1, 37))
    history = []
    for k in range(1, 6):
        cur = {(z * z) % 37 for z in cur}
        history.append((k, len(cur), sorted({orb(z) for z in cur})))
    assert history[0][1] == 18, "after 1 squaring: 18 elements"
    assert history[1][1] == 9, "after 2 squarings: 9 elements"
    assert set(history[1][2]) == H_3
    for k, n, orbs in history[1:]:
        assert n == 9 and set(orbs) == H_3, f"k={k} not stable"
    return history


def run():
    print("=" * 70)
    print("T291 — Iterated Squaring Collapses Z/12Z onto Sylow 3-Subgroup H_3")
    print("=" * 70)

    ic = verify_generator_equivalence()
    print(f"\n--- Part 1: <10> = <26> = IC = {sorted(ic)} ---")
    print("  Both 10 and 26 have order 3 and generate the same subgroup.")
    print("  Framework writes <26> because 26 = 137 mod 37 is the map multiplier.")

    verify_image_formula()
    print("\n--- Part 2: image after k squarings = order 12/gcd(12, 2^k) ---")
    for k in range(0, 5):
        img = image_after_k(k)
        orbs = sorted({orb(pow(2, c, 37)) for c in img})
        print(f"  k={k}: |image|={len(img):2d} = 12/gcd(12,2^{k})  classes={img}")
        print(f"        orbits={orbs}")

    stable_at, terminal, v2, odd = verify_stabilization()
    print(f"\n--- Part 3: stabilization ---")
    print(f"  12 = 2^{v2} x {odd};  v_2(12) = {v2}")
    print(f"  Chain stabilizes after exactly {stable_at} steps.")
    print(f"  Terminal image = {sorted(terminal)} = H_3 = Sylow 3-subgroup of Z/12Z")
    print("  Doubling annihilates the 2-part and cannot touch the odd part.")

    pairs_h6 = verify_antipodal_destruction()
    print(f"\n--- Part 4: antipodal structure destroyed ---")
    print(f"  antipodal map = +6 in Z/12Z (T283/T285)")
    print(f"  H_3 classes = {{0,4,8}};  6 not in H_3")
    print(f"  H_6 contains {len(pairs_h6)} complete antipodal pairs: {pairs_h6}")
    print(f"  H_3 contains 0 complete antipodal pairs.")
    print("  T286: H_3 is the UNIQUE subgroup above H_1 that is not antipodal-closed.")
    print("  Iterated squaring drives the field onto exactly that exception.")

    history = verify_direct()
    print(f"\n--- Part 5: direct check in GF(37)* (|GF(37)*| = 36 = 2^2 x 3^2) ---")
    for k, n, orbs in history:
        print(f"  after {k} squaring(s): {n:2d} elements, orbits={orbs}")

    print("\n  Note: 36 elements total — far too small for any cryptographic use.")
    print("  This is a structural result, not a security construction.")

    print("\nAll T291 assertions passed.")


if __name__ == '__main__':
    run()
