"""
THEOREM 118 — Abelian Group Structure and Cosets of (ℤ/37ℤ)×

The multiplicative group (ℤ/37ℤ)× is cyclic of order 36, generated by 2.
It has a unique subgroup H_d of order d for each d dividing 36:
    1, 2, 3, 4, 6, 9, 12, 18, 36.
H_d = ⟨2^(36/d)⟩ = {a ∈ (ℤ/37ℤ)× : a^d ≡ 1 (mod 37)}.

In discrete-log space (exponents mod 36 via dlog₂), H_d corresponds to
the subgroup {0, 36/d, 2·36/d, …} = multiples of 36/d in ℤ/36ℤ.

COSETS OF H_3 = IC = {1, 10, 26}
    H_3 = ⟨26⟩ (since 26 = 2^12 and 12 = 36/3).
    (ℤ/37ℤ)× / H_3  has order 36/3 = 12.
    The 12 left cosets of H_3 are exactly the 12 orbits of the 137-map.

    Proof: for any a, its coset a·H_3 = {a, 10a, 26a} = {a, f²(a), f(a)}.
    Multiplying by 26 permutes the three elements cyclically — this is
    exactly one 137-map orbit. The coset structure and the orbit partition
    are the same partition of (ℤ/37ℤ)×. □

    In dlog-space: H_3 ↔ multiples of 12 in ℤ/36ℤ = {12, 24, 36}.
    The 12 cosets ↔ residues 1–12 mod 12 in ℤ/36ℤ.

COSETS OF H_9 (order 9)
    H_9 = ⟨2^4⟩ = ⟨16⟩ = {1, 7, 9, 10, 12, 16, 26, 33, 34}.
    (ℤ/37ℤ)× / H_9 has order 36/9 = 4; (ℤ/37ℤ)× / H_9 ≅ ℤ/4ℤ.

    In dlog-space: H_9 ↔ multiples of 4 in ℤ/36ℤ.
    The 4 cosets ↔ residues {0,1,2,3} mod 4 in ℤ/36ℤ.
    Since H_3 ⊂ H_9, every coset of H_9 is a union of 3 cosets of H_3,
    i.e., a union of 3 complete 137-map orbits.

    1·H_9  (dlogs ≡ 0 mod 4):  orbits IC={1,10,26}, D7={7,33,34}, {9,12,16}
    2·H_9  (dlogs ≡ 1 mod 4):  orbits {2,15,20}, SEED_ORBIT={18,24,32}, {14,29,31}
    4·H_9  (dlogs ≡ 2 mod 4):  orbits {3,4,30}, ORBIT_11={11,27,36}, {21,25,28}
    8·H_9  (dlogs ≡ 3 mod 4):  orbits {5,13,19}, {6,8,23}, BASIN_Y={17,22,35}

    Named-class coset membership:
        IC, D7              ⊂ H_9       (coset 0)
        SEED_ORBIT          ⊂ 2·H_9     (coset 1)
        ORBIT_11            ⊂ 4·H_9     (coset 2)
        BASIN_Y             ⊂ 8·H_9     (coset 3)
"""

P = 37
POWER = {k: pow(2, k, P) for k in range(1, 37)}
DLOG  = {v: k for k, v in POWER.items()}

IC         = frozenset({1, 10, 26})
SA         = frozenset({4, 9, 25, 30})
ST         = frozenset({3, 12, 21, 30})
CB         = frozenset({8, 13, 24})
ORBIT_11   = frozenset({11, 27, 36})
SEED_ORBIT = frozenset({18, 24, 32})
BASIN_Y    = frozenset({17, 22, 35})
D7         = frozenset({7, 33, 34})

f = lambda n: (26 * n) % P


def subgroup(d):
    gen = pow(2, 36 // d, P)
    s, x = set(), 1
    for _ in range(d):
        x = (x * gen) % P
        s.add(x)
    return frozenset(s)


def orbit_of(a):
    orb, n = [], a
    for _ in range(3):
        orb.append(n); n = f(n)
    assert n == a
    return frozenset(orb)


def cosets_of(H):
    seen, result = set(), []
    for a in range(1, P):
        if a not in seen:
            c = frozenset((a * h) % P for h in H)
            result.append(c)
            seen.update(c)
    return result


def run():
    from sympy import divisors

    print("=" * 66)
    print("THEOREM 118 — ABELIAN GROUP STRUCTURE AND COSETS OF (ℤ/37ℤ)×")
    print("=" * 66)

    # ---------------------------------------------------------------
    # PART 1 — Subgroup lattice
    # ---------------------------------------------------------------
    print("\n--- Part 1: Subgroup lattice (unique H_d for each d | 36) ---")
    for d in sorted(divisors(36)):
        H = subgroup(d)
        assert len(H) == d, f"|H_{d}| = {len(H)}"
        # every element satisfies a^d = 1
        assert all(pow(a, d, P) == 1 for a in H)
        # H_d is the unique subgroup of order d
        print(f"  H_{d:>2} = {sorted(H)}")

    # ---------------------------------------------------------------
    # PART 2 — Cosets of H_3 = IC are exactly the 137-map orbits
    # ---------------------------------------------------------------
    print("\n--- Part 2: Cosets of H_3 = IC = {1,10,26} ---")
    H3 = subgroup(3)
    assert H3 == IC

    cosets_H3 = cosets_of(H3)
    assert len(cosets_H3) == 12

    # Each coset is a 137-map orbit
    for c in cosets_H3:
        a = min(c)
        assert orbit_of(a) == c, f"Coset {sorted(c)} ≠ orbit of {a}"

    print("  12 cosets of H_3 = 12 orbits of the 137-map (identical partition).  ✓")

    # In dlog-space: cosets are residue classes mod 12 in ℤ/36ℤ
    H3_dlogs = frozenset(DLOG[g] for g in H3)
    assert H3_dlogs == frozenset({12, 24, 36})
    for c in cosets_H3:
        dlogs = sorted(DLOG[g] for g in c)
        residue = dlogs[0] % 12
        assert all(d % 12 == residue for d in dlogs), \
            f"Coset {sorted(c)} dlogs not uniform mod 12"
    print("  In dlog-space: H_3 ↔ {12,24,36} = multiples of 12.")
    print("  The 12 cosets ↔ residues 1–12 mod 12 (one per orbit).  ✓")

    # ---------------------------------------------------------------
    # PART 3 — Cosets of H_9
    # ---------------------------------------------------------------
    print("\n--- Part 3: Cosets of H_9 (4 cosets, each = 3 orbits) ---")
    H9 = subgroup(9)
    assert H9 == frozenset({1, 7, 9, 10, 12, 16, 26, 33, 34})
    assert H3 <= H9, "H_3 ⊂ H_9"

    H9_dlogs = sorted(DLOG[g] for g in H9)
    assert all(d % 4 == 0 for d in H9_dlogs), "H_9 dlogs all divisible by 4"
    print(f"  H_9 = {sorted(H9)}")
    print(f"  H_9 dlogs = {H9_dlogs}  (multiples of 4 in ℤ/36ℤ)")

    coset_reps = [1, 2, 4, 8]
    expected_orbits = {
        1: [IC, D7, frozenset({9, 12, 16})],
        2: [frozenset({2, 15, 20}), SEED_ORBIT, frozenset({14, 29, 31})],
        4: [frozenset({3, 4, 30}), ORBIT_11, frozenset({21, 25, 28})],
        8: [frozenset({5, 13, 19}), frozenset({6, 8, 23}), BASIN_Y],
    }

    print()
    for rep in coset_reps:
        coset = frozenset((rep * h) % P for h in H9)
        dlogs = sorted(DLOG[g] for g in coset)
        residue = dlogs[0] % 4
        assert all(d % 4 == residue for d in dlogs)

        # Extract the 3 orbits within this coset
        seen3, orbs = set(), []
        for x in sorted(coset):
            if x not in seen3:
                orb = orbit_of(x)
                orbs.append(orb)
                seen3.update(orb)
        assert len(orbs) == 3
        assert frozenset(orbs) == frozenset(expected_orbits[rep]), \
            f"Coset {rep}*H_9 orbits mismatch"

        named = [nm for nm, cls in [('IC', IC), ('D7', D7), ('SEED_ORBIT', SEED_ORBIT),
                                    ('ORBIT_11', ORBIT_11), ('BASIN_Y', BASIN_Y)]
                 if cls in orbs]
        print(f"  {rep}*H_9  (dlogs ≡ {residue} mod 4):")
        print(f"    elements: {sorted(coset)}")
        print(f"    dlogs:    {dlogs}")
        print(f"    orbits:   {[sorted(o) for o in sorted(orbs)]}")
        if named:
            print(f"    named:    {named}")

    # ---------------------------------------------------------------
    # PART 4 — Named-class coset membership summary
    # ---------------------------------------------------------------
    print("\n--- Part 4: Named-class coset membership ---")
    coset_map = {}
    for rep in coset_reps:
        coset = frozenset((rep * h) % P for h in H9)
        for g in coset:
            coset_map[g] = rep

    classes = [('IC', IC), ('D7', D7), ('SEED_ORBIT', SEED_ORBIT),
               ('ORBIT_11', ORBIT_11), ('BASIN_Y', BASIN_Y)]

    for nm, cls in classes:
        reps = set(coset_map[g] for g in cls)
        assert len(reps) == 1, f"{nm} spans multiple H_9 cosets"
        print(f"  {nm:<12} ⊂ {min(reps)}·H_9  (coset ≡ {DLOG[min(reps)] % 4} mod 4)")

    # Quotient group (ℤ/37ℤ)× / H_9 ≅ ℤ/4ℤ
    print()
    print(f"  (ℤ/37ℤ)×/H_9 ≅ ℤ/4ℤ  (4 cosets, coset multiplication is mod 4 in dlog-space)")
    # Check: (2·H_9) * (2·H_9) = 4·H_9 in quotient
    assert coset_map[(2 * 2) % P] == 4, "(2*H_9)^2 = 4*H_9"
    assert coset_map[(2 * 4) % P] == 8, "(2*H_9)*(4*H_9) = 8*H_9"
    assert coset_map[(4 * 4) % P] == 1, "(4*H_9)^2 = H_9"
    print(f"  Verified: (2·H_9)² = 4·H_9,  (2·H_9)(4·H_9) = 8·H_9,  (4·H_9)² = H_9  ✓")

    print()
    print("All assertions passed. THEOREM 118 verified.")


if __name__ == "__main__":
    run()
