"""
T286 — Subgroup Lattice of Z/12Z and GF(37)* via the Orbit Quotient

From T285: GF(37)*/IC ≅ Z/12Z, generated by DARK_A = orbit_of(2).

The subgroups of Z/12Z correspond bijectively to divisors of 12:
  d | 12  →  H_d = unique subgroup of order d in Z/12Z
           = { orbit_of(2^(12k/d)) : k=0..d-1 }

In GF(37)*: H_d lifts to the subgroup generated by 2^(36/d).

Six divisors: 1,2,3,4,6,12.

For each subgroup:
  - orbit subset (which named orbits it contains)
  - GF(37)* generator and subgroup order (= 3d)
  - count of complete antipodal pairs it contains (T283: antipodal = +6 in Z/12Z)
  - index [GF(37)*:H_d] = 12/d

Verified quantities:
  H_1  (d=1,  order 1  in Z/12Z): {IC}                              — 0 antipodal pairs
  H_2  (d=2,  order 2  in Z/12Z): {IC, NEG_H}       = <11> (T284)  — 1 antipodal pair
  H_3  (d=3,  order 3  in Z/12Z): {IC, SA_ST_A, D7}                — 0 antipodal pairs
  H_4  (d=4,  order 4  in Z/12Z): {IC, TESLA, NEG_H, C9}           — 2 antipodal pairs
  H_6  (d=6,  order 6  in Z/12Z): {IC, C3, SA_ST_A, NEG_H, D7, SA_ST_B} — 3 antipodal pairs
  H_12 (d=12, order 12 in Z/12Z): all 12 orbits                    — 6 antipodal pairs

Chain (by inclusion):
  H_1 ⊂ H_2 ⊂ H_4 ⊂ H_12
  H_1 ⊂ H_2 ⊂ H_6 ⊂ H_12
  H_1 ⊂ H_3 ⊂ H_6 ⊂ H_12

The lattice is the divisor lattice of 12: {1,2,3,4,6,12}.
"""

ORBITS = {
    'IC':      {1, 10, 26},
    'DARK_A':  {2, 15, 20},
    'C3':      {3, 4, 30},
    'CAS_EXT': {5, 13, 19},
    'TESLA':   {6, 8, 23},
    'D7':      {7, 33, 34},
    'SA_ST_A': {9, 12, 16},
    'NEG_H':   {11, 27, 36},
    'C9':      {14, 29, 31},
    'NQR17':   {17, 22, 35},
    'SEED':    {18, 24, 32},
    'SA_ST_B': {21, 25, 28},
}

ANTIPODAL_PAIRS = [
    ('IC', 'NEG_H'), ('DARK_A', 'NQR17'), ('C3', 'D7'),
    ('TESLA', 'C9'), ('SA_ST_A', 'SA_ST_B'), ('SEED', 'CAS_EXT'),
]

ELEM_TO_ORBIT = {}
for name, elems in ORBITS.items():
    for e in elems:
        ELEM_TO_ORBIT[e] = name

ORBIT_CLASS = {}
for m in range(12):
    base = pow(2, m, 37)
    o = ELEM_TO_ORBIT[base]
    ORBIT_CLASS[o] = m


def orbit_of(x):
    return ELEM_TO_ORBIT.get(x % 37, 'SEAM')


def subgroup_orbits(d):
    """Return the set of orbit names in H_d (subgroup of order d in Z/12Z)."""
    classes = {(12 * k // d) % 12 for k in range(d)}
    class_to_orbit = {v: k for k, v in ORBIT_CLASS.items()}
    return {class_to_orbit[c] for c in classes}


def antipodal_count(orbit_set):
    """Count complete antipodal pairs (both members) in orbit_set."""
    return sum(1 for a, b in ANTIPODAL_PAIRS if a in orbit_set and b in orbit_set)


def gf37_subgroup_generator(d):
    """GF(37)* generator for the subgroup lifting H_d: 2^(36/(3d))."""
    return pow(2, 36 // (3 * d), 37)


def verify_gf37_subgroup(d, gen):
    """Verify <gen> has order 3d in GF(37)*."""
    order = 3 * d
    sg = set()
    x = 1
    for _ in range(order):
        sg.add(x)
        x = (x * gen) % 37
    assert x == 1, f"Generator doesn't return to 1 after {order} steps"
    assert len(sg) == order, f"Subgroup size mismatch: {len(sg)} != {order}"
    return sg


def verify_orbit_subset(d, sg, orbit_subset):
    """Verify GF(37)* subgroup elements exactly cover the orbit_subset."""
    covered = {orbit_of(x) for x in sg if x != 0}
    assert covered == orbit_subset, f"Orbit mismatch: got {covered}, expected {orbit_subset}"


def run():
    divisors = [1, 2, 3, 4, 6, 12]

    print("=" * 68)
    print("T286 — Subgroup Lattice of Z/12Z and GF(37)*")
    print("=" * 68)
    print()
    print("  GF(37)*/IC ≅ Z/12Z  (T285); primitive root 2 has ord_37(2) = 36")
    print("  H_d = subgroup of order d in Z/12Z = coset-closure of 2^(12/d)")
    print()
    print(f"  {'d':>3}  {'Z/12 ord':>8}  {'GF37 gen':>8}  {'GF37 ord':>8}  "
          f"{'anti-pairs':>10}  Orbit subset")
    print(f"  {'-'*3}  {'-'*8}  {'-'*8}  {'-'*8}  {'-'*10}  -----------")

    subgroups = {}
    for d in divisors:
        gen = pow(2, 36 // (3 * d), 37)
        sg = verify_gf37_subgroup(d, gen)
        os = subgroup_orbits(d)
        verify_orbit_subset(d, sg, os)
        ap = antipodal_count(os)
        subgroups[d] = os
        print(f"  {d:>3}  {d:>8}  {gen:>8}  {3*d:>8}  {ap:>10}  {sorted(os)}")

    print()
    print("  Inclusion chain: divisibility lattice of 12")
    print("    H_1 ⊂ H_2 ⊂ H_4 ⊂ H_12")
    print("    H_1 ⊂ H_2 ⊂ H_6 ⊂ H_12")
    print("    H_1 ⊂ H_3 ⊂ H_6 ⊂ H_12")

    # Verify inclusion chain
    for a, b in [(1,2),(2,4),(4,12),(2,6),(6,12),(1,3),(3,6)]:
        assert subgroups[a] <= subgroups[b], f"H_{a} not ⊂ H_{b}"

    print()
    print("  Antipodal pairs by subgroup:")
    for d in divisors:
        ap_list = [(a, b) for a, b in ANTIPODAL_PAIRS
                   if a in subgroups[d] and b in subgroups[d]]
        print(f"    H_{d:2d}: {ap_list}")

    print()
    print("  T284 connection: H_2 = {IC, NEG_H} = <11>/IC (operator group)")
    assert subgroups[2] == {'IC', 'NEG_H'}
    h2_gf37 = verify_gf37_subgroup(2, pow(2, 6, 37))
    print(f"    H_2 GF(37)* subgroup: {sorted(h2_gf37)} = <27> = <11> (T284)")
    assert 11 in h2_gf37 and 27 in h2_gf37, "<11> not in H_2 GF(37)* subgroup"

    print()
    print("  T285 connection: H_4 = {IC, TESLA, NEG_H, C9}")
    print("    Contains both imaginary-unit orbits (TESLA, C9) and their pair")
    assert subgroups[4] == {'IC', 'TESLA', 'NEG_H', 'C9'}

    print()
    print("  T283 connection: antipodal map = +6 in Z/12Z (T285)")
    print("    A subgroup H_d is closed under antipodal iff 6 ∈ H_d (as Z/12Z element)")
    print("    i.e., NEG_H ∈ orbit-subset  ↔  H_d contains its own antipodals")
    for d in divisors:
        closed = 'NEG_H' in subgroups[d]
        pairs = antipodal_count(subgroups[d])
        expected_pairs = d // 2 if closed else 0
        print(f"    H_{d:2d}: NEG_H in? {closed}  antipodal-closed: {closed}  "
              f"pairs={pairs}")

    print()
    print("All T286 assertions passed.")


if __name__ == '__main__':
    run()
