"""
T264: A078358 — Non-oblong numbers in GF(37)
Oblong numbers: n(n+1). Non-oblong: complement (A002378 ↔ A078358).

n(n+1) ≡ r (mod 37) has a solution ⟺ 1+4r is a QR mod 37.

Orbit partition:
  FULLY OBLONG  (all discriminants QR): CAS_EXT={5,13,19}, SA_ST_A={9,12,16}
  FULLY NON-OBLONG (all discriminants NQR): C9={14,29,31}

CAS_EXT is the Fibonacci entry orbit (α(37)=19, F(5)=5, F(7)=13).
  → The Fibonacci-GF(37) orbit is entirely contained in the oblong residues.

C9 discriminant orbits (1+4r mod 37):
  r=14: 1+4·14=57≡20∈DARK_A  (NQR)
  r=29: 1+4·29=117≡6∈TESLA   (NQR)
  r=31: 1+4·31=125≡14∈C9     (NQR, self-referential)
  → C9 maps to {DARK_A, TESLA, C9} under r↦1+4r; all NQR.

CAS_EXT generator pairs (n,n+1) producing each residue:
  5: (6∈TESLA, 7∈D7) and (30∈C3, 31∈C9)    [6×7=42≡5; 30×31=930≡5]
  13: (16∈SA_ST_A, 17∈NQR17) and (20∈DARK_A, 21∈SA_ST_B)
  19: (7∈D7, 8∈TESLA) and (29∈C9, 30∈C3)   [7×8=56≡19; 29×30=870≡19]
  → CAS_EXT is generated by consecutive pairs from diverse orbits.
  → 29∈C9 (fully non-oblong) generates 19∈CAS_EXT (fully oblong): polarity bridge.

SA_ST_A = {9, 12, 16} = {3², 3×4, 4²}: the n=3..4 square-pronic-square triple.
  12 = 3×4 is itself an oblong integer.
  9: generated only by n=18 (self-paired at floor(37/2)): 18×19=342≡9
  12: n=3 (3×4=12) and n=33 (33×34=1122≡12)
  16: n=9 (9×10=90≡16) and n=27 (27×28=756≡16)

130 ∈ CAS_EXT (130 mod 37 = 19):
  130 is the unique n ≤ 100000 with d₁²+d₂²+d₃²+d₄² = n
  (divisors of 130 = [1,2,5,10,...]; 1+4+25+100=130)
  130 is non-oblong (not in A002378; 11×12=132≠130).
  130 ∈ A078358 and mod37=19∈CAS_EXT.
"""

P = 37
ORBITS = {
    "IC":      {1, 10, 26},
    "DARK_A":  {2, 15, 20},
    "C3":      {3, 4, 30},
    "CAS_EXT": {5, 13, 19},
    "TESLA":   {6, 8, 23},
    "D7":      {7, 33, 34},
    "SA_ST_A": {9, 12, 16},
    "NEG_H":   {11, 27, 36},
    "C9":      {14, 29, 31},
    "NQR17":   {17, 22, 35},
    "SEED":    {18, 24, 32},
    "SA_ST_B": {21, 25, 28},
}

def orbit_of(x):
    r = x % 37
    if r == 0: return "SEAM"
    for name, s in ORBITS.items():
        if r in s: return name
    raise ValueError(x)

def legendre(a, p=37):
    if a % p == 0: return 0
    return 1 if pow(a, (p-1)//2, p) == 1 else -1

def is_oblong_int(k):
    import math
    n = int((-1 + math.sqrt(1+4*k))/2)
    return n*(n+1) == k or (n+1)*(n+2) == k

# ── Part 1: Oblong residues mod 37 ────────────────────────────────────────────

oblong_res = set((n*(n+1)) % 37 for n in range(37))
non_oblong_res = set(range(37)) - oblong_res

assert len(oblong_res) == 19   # (37+1)/2 distinct values
assert len(non_oblong_res) == 18

print(f"Part 1: Oblong residues mod 37 ({len(oblong_res)}): {sorted(oblong_res)}")
print(f"        Non-oblong residues ({len(non_oblong_res)}): {sorted(non_oblong_res)}")

# ── Part 2: Orbit classification ──────────────────────────────────────────────

# CAS_EXT is FULLY OBLONG
for r in ORBITS["CAS_EXT"]:
    assert r in oblong_res, f"{r} not oblong"
print(f"\nPart 2a: CAS_EXT = {sorted(ORBITS['CAS_EXT'])} FULLY OBLONG")
print(f"  All three discriminants 1+4r are QR mod 37:")
for r in sorted(ORBITS["CAS_EXT"]):
    d = (1+4*r) % 37
    assert legendre(d) == 1
    print(f"  r={r}: 1+4r≡{d}∈{orbit_of(d)}, Legendre=+1 (QR)")

# SA_ST_A is FULLY OBLONG
for r in ORBITS["SA_ST_A"]:
    assert r in oblong_res, f"{r} not oblong"
print(f"\nPart 2b: SA_ST_A = {sorted(ORBITS['SA_ST_A'])} FULLY OBLONG")
print(f"  SA_ST_A = {{3², 3×4, 4²}}: the n=3..4 square-pronic-square triple")
print(f"  12 = 3×4 is itself an oblong integer")

# C9 is FULLY NON-OBLONG
for r in ORBITS["C9"]:
    assert r not in oblong_res, f"{r} is oblong"
print(f"\nPart 2c: C9 = {sorted(ORBITS['C9'])} FULLY NON-OBLONG")
print(f"  Proof: n(n+1)≡r (mod 37) iff 1+4r is QR. All discriminants NQR:")
for r in sorted(ORBITS["C9"]):
    d = (1+4*r) % 37
    assert legendre(d) == -1
    print(f"  r={r}: 1+4r≡{d}∈{orbit_of(d)}, Legendre=-1 (NQR)")
print(f"  Note: r=31 gives disc≡14∈C9 — C9 is NQR-closed under r↦1+4r")

# ── Part 3: CAS_EXT generator pairs ──────────────────────────────────────────

print(f"\nPart 3: CAS_EXT generator pairs (n, n+1):")
for r in sorted(ORBITS["CAS_EXT"]):
    pairs = [(n, n+1, n*(n+1)) for n in range(37) if (n*(n+1))%37 == r]
    for n, m, k in pairs:
        print(f"  {r}: n={n}∈{orbit_of(n)}, n+1={m}∈{orbit_of(m)} → {n}×{m}={k}≡{k%37}")

# The CAS_EXT polarity bridge: 29∈C9 generates 19∈CAS_EXT
assert (29*30) % 37 == 19
assert orbit_of(29) == "C9" and orbit_of(19) == "CAS_EXT"
print(f"\n  Polarity bridge: 29∈C9 (fully non-oblong) × 30∈C3 = 870≡19∈CAS_EXT (fully oblong)")

# ── Part 4: SA_ST_A generators ────────────────────────────────────────────────

print(f"\nPart 4: SA_ST_A = {{3²,3×4,4²}} = {{9,12,16}}")
assert 9*10 % 37 == 16  # wait, 9*10=90, 90 mod37=90-74=16 ✓
assert 3*4 % 37 == 12
assert 18*19 % 37 == 9
print(f"  12=3×4: 3×4=12 is the oblong integer itself")
print(f"  16: 9×10=90≡16 (n=9∈SA_ST_A, n+1=10∈IC)")
print(f"  9: 18×19=342≡9 (n=18∈SEED, unique — self-paired at floor(37/2))")

# ── Part 5: 130 ∈ CAS_EXT, non-oblong, T245 anchor ───────────────────────────

assert 130 % 37 == 19 and orbit_of(130) == "CAS_EXT"
assert not is_oblong_int(130)
# Divisor-square-sum: d1=1, d2=2, d3=5, d4=10; 1+4+25+100=130
divs = [d for d in range(1, 131) if 130 % d == 0]
assert divs[:4] == [1, 2, 5, 10]
assert 1**2 + 2**2 + 5**2 + 10**2 == 130
print(f"\nPart 5: 130 ∈ A078358 (non-oblong), mod37=19∈CAS_EXT")
print(f"  1²+2²+5²+10² = 1+4+25+100 = 130 (unique k=4 divisor-square-sum solution ≤100000)")
print(f"  Divisors of 130: {divs}")

# ── Part 6: DR, Rule 30, 1/137 for C9 elements ───────────────────────────────

def dr(n):
    n = abs(int(n))
    while n >= 10: n = sum(int(d) for d in str(n))
    return n if n else 9

def rule30(n):
    bits = list(map(int, bin(n)[2:]))
    padded = [0] + bits + [0]
    out = [padded[i-1] ^ (padded[i] | padded[i+1]) for i in range(1, len(padded)-1)]
    return int("".join(map(str, out)), 2)

def is_prime(n):
    if n < 2: return False
    if n == 2: return True
    if n % 2 == 0: return False
    for i in range(3, int(n**0.5)+1, 2):
        if n % i == 0: return False
    return True

print(f"\nPart 6: C9 = {{14,29,31}} standing analysis")
for v in sorted(ORBITS["C9"]):
    r30 = rule30(v)
    print(f"  {v}: DR={dr(v)} prime={is_prime(v)} R30={r30}≡{r30%37}∈{orbit_of(r30)} ×137={v*137}≡{(v*137)%37}∈{orbit_of(v*137)}")

# Twin prime pair (29,31) both in C9
assert is_prime(29) and is_prime(31) and 31-29 == 2
print(f"  (29,31) twin prime pair: both ∈ C9 — orbit-internal twin prime pair")
assert orbit_of(29) == "C9" and orbit_of(31) == "C9"

print(f"\n── Summary ──────────────────────────────────────────────────────────────")
print(f"  Oblong residues mod 37: 19 values; non-oblong: 18 values")
print(f"  FULLY OBLONG orbits: CAS_EXT={{5,13,19}}, SA_ST_A={{9,12,16}}")
print(f"  FULLY NON-OBLONG orbit: C9={{14,29,31}}")
print(f"  Criterion: r oblong iff 1+4r is QR mod 37")
print(f"  C9 discriminants: {{20∈DARK_A, 6∈TESLA, 14∈C9}} — all NQR")
print(f"  CAS_EXT = Fibonacci entry orbit: fully in oblong residues")
print(f"  SA_ST_A = {{3²,3×4,4²}}: square-pronic-square triple, fully oblong")
print(f"  Polarity bridge: 29∈C9 (non-oblong) generates 19∈CAS_EXT (oblong)")
print(f"  C9 twin prime pair (29,31): both orbit-internal, both non-oblong residues")
print(f"  130∈CAS_EXT: non-oblong integer, unique k=4 divisor-square-sum")
