"""
Theorem 199: Squaring Generation of SA and ST from SEED and 137-Map Cycle in GF(37)
Author: Michael Warren Song (CyclicAmp)

GENERATIVE STRUCTURE VIA SQUARING:
  SA = {4, 3^2, 32^2, 30} = {4, 9, 25, 30}  (exact)
  ST = {3, 30^2, 24^2, 30} = {3, 12, 21, 30}  (exact)

  Sources:
    4∈SA:   primitive element in 137-map cycle {3,4,30}
    3∈ST:   primitive element in 137-map cycle {3,4,30}
    9∈SA:   3^2 (squaring the ST element 3 gives SA element 9)
    12∈ST:  30^2 (squaring the SA∩ST element 30 gives ST element 12)
    21∈ST:  24^2 (squaring SEED element 24 gives ST element 21)
    25∈SA:  32^2 (squaring SEED element 32 gives SA element 25)
    30∈SA∩ST: the shared element, source of both SA and ST

UNIVERSAL SQUARING CYCLE:
  All sovereign elements eventually enter the unique 6-cycle {9,7,12,33,16,34}
  under iterated squaring (x → x^2 mod 37).
  Cycle sum = 9+7+12+33+16+34 = 111 = 3×37 ≡ 0 mod 37.
  DR(111) = 3 = ST value.
  Cycle length 6 = ord(2) mod 9.
  Sovereign elements in cycle: 9∈SA (position 0), 12∈ST (position 2).

SQUARING TAIL STRUCTURE:
  Tail-0 (already in cycle):  {9∈SA, 12∈ST}
  Tail-1 (one square to cycle):
    3(ST) → 9(SA)          [ST→SA connection]
    4(SA) → 16(free)
    21(ST) → 34(free)
    25(SA) → 33(free)
    30(SA∩ST) → 12(ST)     [SA∩ST→ST connection]
  Tail-2 (two squares to cycle):
    18(SEED) → 28(free,DR=1) → 7(free) [head-crash in tail]
    24(SEED) → 21(ST)      → 34(free) [SEED→ST→cycle]
    32(SEED) → 25(SA)      → 33(free) [SEED→SA→cycle]

SEED SQUARING PATHS:
  24^2 = 21 ∈ ST:  SEED produces a new ST element by squaring.
  32^2 = 25 ∈ SA:  SEED produces a new SA element by squaring.
  18^2 = 28 (free, DR=1): SEED element 18 produces head-crash signature.

137-MAP CYCLE CONNECTION:
  {3,4,30}: 137-map cycle containing ST(3), SA(4), SA∩ST(30).
  Squaring of elements in this cycle:
    3(ST)^2 = 9∈SA:     feeds the ORDER-9 sovereign elements.
    4(SA)^2 = 16∈free:  dissipates to free.
    30(SA∩ST)^2 = 12∈ST: feeds the ORDER-9 sovereign elements.
  The order-9 sovereigns {9∈SA, 12∈ST} receive squares from the order-18 cycle {3,4,30}.

COSET ALGEBRA (from Theorem 197/198):
  <26> = {1,10,26}: the 137-map subgroup, order 3.
  6 QR cosets = 3^k×<26> for k=0..5:
    k=0: {1,10,26} — multiplier group
    k=1: {3,4,30} — KEY sovereign cycle (ST+SA+SA∩ST)
    k=2: {9,12,16} — SA+ST+free
    k=5: {21,25,28} — ST+SA+free
  6 NQR cosets = 2×3^k×<26>:
    k=1: {6,8,23} = SEED generators (3×each gives SEED)
    k=2: {18,24,32} = SEED (the unique pure-sovereign coset)
  SEED generators = 8×<26>. SEED = 24×<26>.

SQUARE-ROOT MAP:
  sqrt(30) mod 37 = {17,20} — both NQR.
  sqrt(-1) mod 37 = {6,31} — both NQR, ord=4.
  6 = i (primitive 4th root of unity mod 37).
  6^2 = 36 = -1. SEED generator 6 is the imaginary unit mod 37.
  3×6 = 18∈SEED: multiplying i by 3 gives the first SEED element.
"""

P = 37
SA = {4, 9, 25, 30}
ST = {3, 12, 21, 30}
SEED = {18, 24, 32}


def dr(n):
    n = abs(int(n))
    return 9 if n % 9 == 0 and n != 0 else n % 9


def legendre(a, p):
    return pow(a, (p - 1) // 2, p)


def sector(r):
    if r == 0: return 'SEAM'
    if r in SA and r in ST: return 'SA∩ST'
    if r in SA: return 'SA'
    if r in ST: return 'ST'
    if r in SEED: return 'SEED'
    if legendre(r, P) == P - 1: return 'NQR'
    return 'free'


CYCLE_6 = [9, 7, 12, 33, 16, 34]


def squaring_tail(x):
    orbit = [x]
    v = pow(x, 2, P)
    while v != x and v not in orbit:
        orbit.append(v)
        v = pow(v, 2, P)
    if v == x:
        return [], orbit   # pure cycle
    idx = orbit.index(v)
    return orbit[:idx], orbit[idx:]  # tail, cycle


def run_assertions():
    # 1. SA and ST generated by squaring
    assert {4, pow(3, 2, P), pow(32, 2, P), 30} == SA
    assert {3, pow(30, 2, P), pow(24, 2, P), 30} == ST

    # 2. Specific squaring paths
    assert pow(3, 2, P) == 9 and 9 in SA    # ST→SA
    assert pow(30, 2, P) == 12 and 12 in ST  # SA∩ST→ST
    assert pow(24, 2, P) == 21 and 21 in ST  # SEED→ST
    assert pow(32, 2, P) == 25 and 25 in SA  # SEED→SA
    assert pow(18, 2, P) == 28 and dr(28) == 1  # SEED→head crash

    # 3. Universal squaring cycle {9,7,12,33,16,34}
    # Verify it's actually a cycle
    v = 9
    for i in range(6):
        assert v == CYCLE_6[i]
        v = pow(v, 2, P)
    assert v == 9  # closes

    # 4. Cycle sum = 3P
    assert sum(CYCLE_6) == 3 * P
    assert sum(CYCLE_6) % P == 0
    assert dr(sum(CYCLE_6)) == 3

    # 5. All sovereign elements eventually enter this cycle
    for x in sorted(SA | ST | SEED):
        tail, cycle = squaring_tail(x)
        assert sorted(cycle) == sorted(CYCLE_6)

    # 6. Tail lengths: SEED=2, {9,12}=0, others=1
    for x in SEED:
        tail, cycle = squaring_tail(x)
        assert len(tail) == 2
    for x in [9, 12]:
        tail, cycle = squaring_tail(x)
        assert len(tail) == 0
    for x in {3, 4, 21, 25, 30}:
        tail, cycle = squaring_tail(x)
        assert len(tail) == 1

    # 7. Cycle length = ord(2) mod 9 = 6
    assert len(CYCLE_6) == 6
    assert pow(2, 6, 9) == 1
    assert all(pow(2, k, 9) != 1 for k in range(1, 6))

    # 8. sqrt(-1) mod 37 = {6,31}
    sqrt_neg1 = [x for x in range(1, P) if pow(x, 2, P) == P - 1]
    assert sorted(sqrt_neg1) == [6, 31]
    assert pow(6, 2, P) == P - 1  # 6 = imaginary unit

    # 9. 3×6=18∈SEED (multiplying i by 3 gives first SEED element)
    assert 3 * 6 % P == 18 and 18 in SEED

    # 10. Coset structure
    sg26 = {1, 10, 26}
    assert {3 * h % P for h in sg26} == {3, 4, 30}   # 3×<26> = KEY cycle
    assert {8 * h % P for h in sg26} == {6, 8, 23}   # SEED generators
    assert {24 * h % P for h in sg26} == SEED          # SEED coset

    # 11. SEED generators sum to P
    assert sum({6, 8, 23}) == P

    print("All assertions passed.")


if __name__ == "__main__":
    run_assertions()
