"""
Theorem 200: GF(37)*/<26> ≅ Z/12Z — Complete Quotient Structure
Author: Michael Warren Song (CyclicAmp)

THE QUOTIENT GROUP:
  GF(37)* has order 36. <26> = {1,10,26} has order 3.
  GF(37)*/<26> ≅ Z/12Z, generated by g = 2×<26> (the primitive root 2 projects to generator g).

SOVEREIGN COSETS IN Z/12Z (positions of all framework elements):
  g^2  = {3,4,30}    — KEY CYCLE: ST+SA+SA∩ST (only coset spanning all 3 classes)
  g^3  = {6,8,23}    — SEED generators = i×<26> where i=6=sqrt(-1)
  g^4  = {9,12,16}   — SA+ST+free (second SA∩ST coset)
  g^5  = {18,24,32}  — SEED (the unique pure-sovereign coset, all primitive roots)
  g^10 = {21,25,28}  — ST+SA+free (third SA∩ST coset; inverse of KEY)
  All other positions: free or NQR, no framework elements.

COSET ARITHMETIC (in Z/12Z):
  KEY × SEED_gens = SEED:      g^2 × g^3 = g^5  ✓
  KEY × KEY = SA+ST:           g^2 × g^2 = g^4  ✓
  SEED^2 = SA+ST (pos 10):     g^5 × g^5 = g^10 ✓
  KEY × SEED = pos 7 (free):   g^2 × g^5 = g^7  ✓
  KEY × KEY^{-1} = identity:   g^2 × g^10 = g^12 = g^0 = <26> ✓
  KEY and g^10 are multiplicative inverses.

IMAGINARY UNIT STRUCTURE:
  i = 6 = sqrt(-1) mod 37, ord(i) = 4.
  i corresponds to position 3 in Z/12Z (since 6 = 2^3 mod 37 in terms of generator).
  Wait: 2^3 mod37=8≠6. But in coset terms: g^3 contains 6. So i is IN g^3.
  i^2 = 36 = -1. i^4 = 1. The subgroup <i>/<26> = {g^0, g^3, g^6, g^9} ⊂ Z/12Z.
  SEED = g^5 = g^2 × g^3 = KEY × i-coset.
  SEED = i × KEY explicitly: 6×{3,4,30} = {18,24,32} = SEED (exact).

KEY IDENTITIES:
  SEED = i × KEY = i × {3,4,30} = 6×{3,4,30} = {18,24,32}
  SEED generators = i × <26> = 6×{1,10,26} = {6,8,23}
  SEED^2 (element-wise products) = {21,25,28} = g^10 coset
  KEY^{-1} = {21,25,28} (inverse coset in Z/12Z)
  KEY × KEY^{-1} = <26> = identity

COMPLETE SA∪ST COVERAGE IN QUOTIENT:
  SA = {4,9,25,30}: elements from g^2(4,30), g^4(9), g^10(25)
  ST = {3,12,21,30}: elements from g^2(3,30), g^4(12), g^10(21)
  SA∩ST = {30}: in g^2 only
  SEED = {18,24,32}: entirely in g^5
  All 7 unique SA∪ST elements are in g^{2,4,10}; SEED is in g^5.

POSITION ARITHMETIC:
  Sovereign positions sum: 2+4+5+10=21 ≡ 9 (mod 12) = SEAM (DR=9).
  KEY+SEED: 2+5=7 (non-sovereign; pure dissipation coset).
  KEY+KEY: 4 (SA+ST coset).
  SEED+SEED: 10 (inverse-KEY SA+ST coset).
  SEED+KEY^{-1}: 5+10=15≡3 (mod 12) = SEED generator position.
"""

P = 37
SA = {4, 9, 25, 30}
ST = {3, 12, 21, 30}
SEED = {18, 24, 32}
SG26 = {1, 10, 26}


def dr(n):
    n = abs(int(n))
    return 9 if n % 9 == 0 and n != 0 else n % 9


def legendre(a, p):
    return pow(a, (p - 1) // 2, p)


def sector(r):
    if r == 0: return 'SEAM'
    if r in SA and r in ST: return 'SA∩ST'
    if r in SA: return 'SA'
    if r in ST: return 'ST'
    if r in SEED: return 'SEED'
    if legendre(r, P) == P - 1: return 'NQR'
    return 'free'


def coset(rep):
    return frozenset(rep * h % P for h in SG26)


def coset_product(c1, c2):
    reps = {next(iter(c1))}
    return coset(next(iter(c1)) * next(iter(c2)) % P)


def run_assertions():
    # 1. Quotient is Z/12Z: 2 generates all 12 cosets
    all_cosets = set()
    for k in range(1, 13):
        all_cosets.add(coset(pow(2, k, P)))
    assert len(all_cosets) == 12

    # 2. All 12 cosets return to identity at k=12
    assert coset(pow(2, 12, P)) == SG26

    # 3. Sovereign coset positions
    assert coset(pow(2, 2, P)) == frozenset({3, 4, 30})   # KEY
    assert coset(pow(2, 3, P)) == frozenset({6, 8, 23})   # SEED gens
    assert coset(pow(2, 4, P)) == frozenset({9, 12, 16})  # SA+ST
    assert coset(pow(2, 5, P)) == SEED                     # SEED
    assert coset(pow(2, 10, P)) == frozenset({21, 25, 28})  # KEY^{-1}

    # 4. Coset arithmetic
    # KEY × SEED_gens = SEED (g^2 × g^3 = g^5)
    key_rep = 3   # representative of KEY coset
    sg_rep = 6    # representative of SEED gen coset
    assert coset(key_rep * sg_rep % P) == SEED

    # KEY × KEY = SA+ST coset (g^2 × g^2 = g^4)
    assert coset(key_rep * key_rep % P) == frozenset({9, 12, 16})

    # SEED^2 = {21,25,28} (g^5 × g^5 = g^10)
    seed_rep = 18  # representative of SEED coset
    assert coset(seed_rep * seed_rep % P) == frozenset({21, 25, 28})

    # KEY × KEY^{-1} = identity
    inv_key_rep = 21  # representative of pos-10 coset
    assert coset(key_rep * inv_key_rep % P) == SG26

    # 5. SEED = i × KEY (imaginary unit i=6 rotates KEY to SEED)
    i = 6
    assert i * i % P == P - 1  # i^2 = -1
    assert {i * x % P for x in {3, 4, 30}} == SEED
    assert {i * x % P for x in SG26} == {6, 8, 23}  # SEED gens

    # 6. Sovereign positions sum ≡ 9 mod 12
    assert (2 + 4 + 5 + 10) % 12 == 9

    # 7. SEED position + KEY^{-1} position = 15 ≡ 3 (SEED gen position)
    assert (5 + 10) % 12 == 3

    # 8. SA and ST elements distributed across positions 2,4,10
    sa_cosets = {frozenset({3, 4, 30}), frozenset({9, 12, 16}), frozenset({21, 25, 28})}
    for c in sa_cosets:
        assert any(x in SA for x in c)
    for x in SA:
        assert any(x in c for c in sa_cosets)

    for c in sa_cosets:
        assert any(x in ST for x in c)
    for x in ST:
        assert any(x in c for c in sa_cosets)

    # 9. SA∩ST = {30} is only in g^2 = KEY coset
    assert 30 in {3, 4, 30}
    assert 30 not in {9, 12, 16} | {21, 25, 28}

    # 10. All SEED elements have order 36 (primitive roots)
    assert all(pow(x, 36, P) == 1 and all(pow(x, d, P) != 1 for d in [2, 3, 4, 6, 9, 12, 18])
               for x in SEED)

    print("All assertions passed.")


if __name__ == "__main__":
    run_assertions()
